decentdao/decent-app

src/components/Body.tsx, src/components/DAOs/index.tsx, src/components/Home.tsx
Created a home page and set up correct routing
=> Home page + routing

src/components/DAOs/New/GovernanceDetails.tsx, src/components/DAOs/New/index.tsx
Added Gov Details to refactor branch
=> Refactor gov details

src/components/DAOs/New/index.tsx, src/components/Pending.tsx
Added pending page for when transaction is being called. then navigates to dao page once completed
=> Created pending component

src/components/DAOs/New/index.tsx, src/daoData/useDeployDAO.ts, src/web3/transactions.ts
* Updated useTransaction page - similar to DCNT airdrop
* Separated UseDeploy and createDao page
* Cleaned up ts/transaction vars/formatting
=> close #33 Updatetransactionpage

src/components/DAOs/DAO/Proposals/ProposalCard.tsx, src/components/DAOs/DAO/Proposals/ProposalCardDetailed.tsx, src/components/DAOs/DAO/Proposals/ProposalDetails.tsx, src/components/DAOs/DAO/Proposals/ProposalVotes.tsx, src/components/DAOs/DAO/Proposals/ProposalsList.tsx, src/components/DAOs/DAO/Proposals/index.tsx, src/components/ui/CopyToClipboard.tsx, src/components/ui/svg/Clipboard.tsx, src/components/ui/svg/Clock.tsx, src/daoData/useProposals.ts
This PR adds components / routes to support a proposal details page. This page shows details about the currently selected proposal, and the vote counts of the proposal as shown in the screenshot below.
=> Proposal details

src/components/DAOs/DAO/Proposals/ProposalCard.tsx, src/components/DAOs/DAO/Proposals/ProposalsList.tsx, src/components/DAOs/DAO/Summary.tsx, src/components/ui/ContentBox.tsx, src/components/ui/svg/Clock.tsx, src/daoData/daoData.ts, src/daoData/useProposals.ts
=> Dao summary style

src/components/ui/CopyToClipboard.tsx
Show a toast when text is copied.
- Timer is set to 1000ms
#72
=> Copied Text Toast

src/components/DAOs/DAO/Proposals/ProposalDetails.tsx
PR completes following:
Allow a user to refresh the page on proposal details. This was accomplished by rebuilding state by assigning address to the usedao hook.
=> Bug re fresh details

src/App.tsx
Place max width on body of 768px
=> Place max width on body of 768px

src/components/DAOs/DAO/DelegateVote.tsx, src/components/ui/forms/Input.tsx
Updates Delegate Vote component with new Inputs and Buttons.
=> Delegate vote update

src/components/DAOs/DAO/Proposals/ProposalCard.tsx, src/components/ui/ContentBox.tsx, src/components/ui/StatusBox.tsx, tailwind.config.js
Updates Proposals to match designs styles.
- I did add a shadow to the ContentBox, not in designs. let me know if there are any concerns
- Updates Fonts and spacing to match designs
- Adds StatusBox Component to handle displaying status text
=> Proposals Update

src/components/DAOs/DAO/Proposals/CastVote.tsx, src/components/DAOs/DAO/Proposals/ProposalCardDetailed.tsx, src/components/DAOs/DAO/Proposals/ProposalVotes.tsx, src/components/ui/forms/Button.tsx
Updates Component with new UI Button
Also updates fonts and spacing
=> Updates Proposal Details UI

src/components/DAOs/DAO/index.tsx, src/daoData/useModuleAddresses.ts, src/daoData/useProposals.ts, src/daoData/useTokenData.ts
Closes #96 
Resets the data layer properties back to `undefined` when the `DAO` component unloads
=> Unload DAO

src/components/DAOs/DAO/Delegate.tsx, src/components/DAOs/DAO/Proposals/ProposalCard.tsx, src/components/DAOs/DAO/Proposals/ProposalsList.tsx, src/components/DAOs/DAO/Summary.tsx, src/components/DAOs/DAO/index.tsx
Closes #86 
Closes #87 
- Moves "Delegate" component to own page
- Adds "Proposals" title to DAO Summary page
- Adds buttons to "Proposals" title row for "Delegate" and "New Proposal"
=> Dao dashboard actions

src/components/DAOs/DAO/Details.tsx, src/components/DAOs/DAO/Proposals/New/index.tsx, src/components/DAOs/DAO/Proposals/ProposalDetails.tsx, src/components/DAOs/DAO/Proposals/index.tsx, src/components/DAOs/DAO/Summary.tsx, src/components/DAOs/DAO/index.tsx, src/daoData/daoData.ts
Closes #104
First few commits tee up the codebase for the final commit, which moves the "loading DAO" logic up out of the `Summary` component, and into the DAO `index` component.
=> Keep dao loaded

src/components/Pending.tsx
Notice a few other absolute/fixed elements  would hover above this screen. so add a z-index of 50
=> Quick Fix: Pending Screen

src/index.tsx
Closes #94 
- haven't configured any of the transactional-level toasts yet (like the toasts that appear when transaction are pending/failed/completed. will handle those (and the proper styling, like a persistent progress bar / bottom border) in a future PR
=> Styled toast

src/components/Home.tsx
updates buttons to fit on mobile
- replaces with new Primary/Secondary Buttons
=> Mobile: Welcome Screen

src/components/DAOs/DAO/Delegate.tsx, src/components/DAOs/DAO/Proposals/ProposalCard.tsx, src/components/ui/StatusBox.tsx
=> QuickFix Proposal Responsive Update

src/components/DAOs/New/TokenDetails.tsx
Found Bug with errorMap as part of validation.
Updated to map the errorMap values to check for errors.
- I will add the card to update this section of error handling to be more similar to how Proposals handle transaction as well as update with 'amount' error handling
=> fixes errorMap validation

src/index.css, src/web3/providers.ts
Updates Web3Modal using css classes to override default theme
Added Theme Option to web3Modal. setting all to 'none'
At the bottom of file added web3modal css classes and `@apply` tailwind classes
=> updates web3Modal to match fractal theme

src/App.tsx
PR info:
Very simple tailwind change - added bg-fixed to keep bg static.
Before:
After:
=> fixed background

src/components/DAOs/DAO/Delegate.tsx, src/components/DAOs/DAO/Proposals/New/Transaction.tsx, src/components/DAOs/New/TokenDetails.tsx, src/components/DAOs/New/index.tsx, src/components/ui/EtherscanLink.tsx, src/components/ui/Header/HeaderMenu.tsx, src/components/ui/Header/MenuItems.tsx, src/daoData/useAccessControlContract.ts, src/daoData/useCastVote.ts, src/daoData/useCreateProposal.ts, src/daoData/useDAOContract.ts, src/daoData/useDelegateVote.ts, src/daoData/useDeployDAO.ts, src/daoData/useExecuteTransaction.ts, src/daoData/useGovernorModuleContract.ts, src/daoData/useProposals.ts, src/daoData/useQueueTransaction.ts, src/daoData/useTimelockModuleContract.ts, src/daoData/useTokenContract.ts, src/daoData/useTokenData.ts, src/hooks/use165Contract.ts, src/hooks/useAddress.ts, src/hooks/useAvatar.ts, src/hooks/useCurrentBlockNumber.ts, src/hooks/useCurrentTimestamp.ts, src/hooks/useENSName.ts, src/web3/index.tsx, src/web3/providers.ts
- This should be reviewed/merged _after_ #165 
This doesn't explicitly close any issues, but it does create a smoother app experience when disconnecting an account, because it no longer requires a window reload.
=> No reload on disconnect

src/components/DAOs/DAO/Delegate.tsx
adds address and ens validation hook to Delegate Vote
There isn't currently a full way to test this in action as ENS Domains are currently only mainnet, and this screen isn't currently accessible on mainnet
=> Delegate Vote Address validation

src/components/Breadcrumbs.tsx
First loaded name, if not that then verified DAO address, if not that then address from url params, if not that then "..."
Closes #138
=> Give an order for how DAO Name should display in breadcrumb

src/components/DAOs/DAO/Proposals/index.tsx
=> Auto navigate up a level if user tries to go to /daos/:address/proposals

src/components/DAOs/DAO/Delegate.tsx
fixes #175 
error message i now handle by state/useEffect. It was being caused by `newDelegatee.trim() === ""` as part of the conditional.
N/A
=> Delegate Vote Input Bug Fix

src/components/DAOs/DAO/Proposals/New/Transaction.tsx, src/components/DAOs/DAO/Proposals/New/Transactions.tsx, src/components/DAOs/DAO/Proposals/New/index.tsx, src/components/DAOs/New/TokenAllocationInput.tsx, src/components/DAOs/New/TokenAllocations.tsx, src/components/DAOs/New/TokenDetails.tsx, src/daoData/useDeployDAO.ts
After re-thinking about the workflow I had for Transactions and TokenAllocations and in reference to issue #48. I realized I may have grabbed a sword to handle the job of a knife. I removed the Javascript Maps and it's corresponding methods and state. 
- removed Map and added properties to transaction object to error handle simplifying the workflow
- for TokenAllocation I added a Amount error that would show when supply less than total allocated
=> Remove errorMap

package.json
@tbwebb22 just for u i made `npm run start-windows`
=> Remove third party sourcemap warnings on `npm run start`

package.json
Updates windows start script to not generate sourcemap
=> Update start:windows script to not generate sourcemap

src/components/DAOs/New/GovernanceDetails.tsx, src/components/DAOs/New/TokenDetails.tsx
=> moved content banner to correct screen

src/components/ui/forms/Input.tsx
=> `stripChars` should strip decimal places too

package-lock.json, package.json, public/index.html, src/components/DAOs/DAO/index.tsx, src/index.tsx
Closes #111 
- By default, the title in browser tab will say `Fractal`.
- Whenever a DAO is loaded (aka we're in a `daos/:address` route), the DAO's name is appended: `Fractal | Decent DAO`.
- Leaving the DAO (back to home page for example), clears the DAO's name out of the title.
Notes
- Requires `npm install` due to addition of `react-helmet` package
=> Fractal name in title

src/components/DAOs/DAO/Details.tsx, src/contexts/daoData/daoData.ts, src/contexts/daoData/useTokenData.ts
This PR adds the governance token address to the tokenData within the DAOData object.
This address is displayed on the DAO details page.
Users will need to know the governance token address for constructing transactions for proposals.
=> Token address

src/index.css
Closes #194
Some additional styling to web3Modal
=> styles wallet connect modal

src/components/DAOs/New/TokenAllocationInput.tsx
=> BugFix: Token Allocation Validation

src/index.tsx
Closes #197  
Here's a screenshot with some forced toasts:
If you want to see for yourself on the deployed site
* connect your wallet
* reload the DAO Search page
* this will trigger the "Connected" toast to start
* quickly disconnect your wallet
* this will trigger the "Plz connect wallet to search" toast
* if you do that quick enough, you'll see both toasts on the screen at once.
=> Add a bit of top margin to each toast

src/components/DAOs/DAO/index.tsx, src/hooks/useValidateDaoRoute.ts
=> Loading Proposal Twice

src/contexts/blockchainData/useCurrentTimestamp.ts
Closes #238
Fixes the console error.
=> Don't set timestamp with block.timestamp if block is null

src/pages/DaoSearch/index.tsx
closes #211
Based off #251 
Cleans up responsiveness of Find a Fractal form
=> 211-Find a Fractal button not aligned

src/components/Proposals/CastVote.tsx
=> removed unneeded copy

src/components/ui/StatusBox.tsx
Closes #213
Need to get consensus from the team that this visual design is acceptable.
My attempt at something better based off of previous comments:
=> Proposal status updates

src/components/ProposalCreate/Transaction.tsx, src/components/ProposalCreate/Transactions.tsx, src/pages/DaoCreate/index.tsx, src/pages/ProposalCreate/index.tsx
PR details
- Create DAO page
* disable prev button during pending transaction
- Create Proposal page
* disable prev button during pending
* disable add transaction during pending
* disable remove transaction during pending && valid dao transaction
=> Prev disable

src/components/Proposals/CastVote.tsx, src/components/Proposals/ProposalExecute.tsx, src/components/Proposals/ProposalQueue.tsx, src/hooks/useCastVote.ts, src/hooks/useExecuteTransaction.ts, src/hooks/useQueueTransaction.ts
PR details
- Disable Cast Vote button during transaction
* check transaction pending for cast vote button
* check pending for for, against, abstain button
- Disable queue button during transaction
* added pending state to check if transaction is being executed
- Disable execute button during transaction
* added pending state to check if transaction is being executed
=> Disable action

package-lock.json, package.json, src/App.tsx, src/index.tsx
Closes #275 
Show a "persistent" toast message to the user, indicating that the project is not audited.
On this toast, give the user a button indicating that they accept the risks involved.
When clicking "Accept", set a cookie in the browser's storage simply flagging that the user has accepted the risk and wants to dismiss the cookie.
When this cookie is set, the toast will go away and not be displayed again.
=> Not audited message

src/components/ProposalCreate/Transaction.tsx
Noticed that after submitting was able to change the form fields, this has been disabled while pending
=> disables form after submit

src/hooks/useENSName.ts
added a mounted variable to prevent unmounted setState
=> BugFix. Unmounted Component

src/contexts/daoData/treasury/useTreasuryAssets.ts, src/contexts/daoData/treasury/useTreasuryEvents.ts
closes #293 
Adds logic to reset state when DAO address is changed in URL
=> resets state when url is manually updated on page

.gitignore, src/components/Dao/Delegate.tsx
**Summary**
feat: delegate-explainer-tooltip
=> feat:delegate-explainer-tooltip

src/components/ProposalCreate/Transaction.tsx
[PR updates Changed example to include Bignumber w/ strings quotes.](https://github.com/decent-dao/fractal-interface/pull/322)
=>  #302 error when adding BN without quotes 

src/index.css
There are some inputs that have units. step counters are shown above it. This PR updates so that they are removed by default and can be added more specifically to any number inputs as needed
=> removes step counters from inputs

src/components/DaoCreate/DisplayStepController.tsx, src/components/DaoCreate/GovernanceDetails.tsx, src/components/DaoCreate/TokenDetails.tsx, src/components/ui/forms/Input.tsx, src/hooks/useDeployDAO.ts, src/pages/DaoCreate/index.tsx
PR Intentions 
Issue #308 intention was to make gov details on create DAO editable. Included in this PR
1. proposalThreshold
2. quorum
3. executionDelay
4. lateQuorumExecution
5. voteStartDelay
6. votingPeriod
Are now all editable fields with accompanying helper text and recommendations.
Each field is editable and will result in a governor module being setup to the users specifications
=> Governance edit

src/contexts/daoData/useTokenContract.ts, src/contexts/web3Data/Web3Provider.tsx, src/contexts/web3Data/helpers.ts, src/contexts/web3Data/types.ts, src/hooks/useCastVote.ts, src/hooks/useCreateProposal.ts, src/hooks/useDeployDAO.ts, src/hooks/useExecuteTransaction.ts, src/hooks/useQueueTransaction.ts
Commits in order show what's going on
=> Signer or provider

src/components/DaoCreator/DisplayStepController.tsx, src/components/ui/forms/Button.tsx, src/contexts/daoData/treasury/useTreasuryAssets.ts, src/contexts/daoData/treasury/useTreasuryEvents.ts, src/contexts/daoData/types/accessControlDAO.ts, src/contexts/daoData/types/governorModule.ts, src/contexts/daoData/types/index.ts, src/contexts/daoData/types/token.ts, src/contexts/daoData/useModuleAddresses.ts, src/contexts/daoData/useProposals.ts, src/contexts/daoData/useTokenData.ts, src/pages/Daos/index.tsx
Removed all todos and created issues for todos which should be handled at a separate time.
Todo handled in this PR
- Removed unused vars by exporting types
- Skipping native token and settlement layer
=> #300 completed todo

src/components/AddressDisplay.tsx, src/components/Dao/Details.tsx, src/components/ui/Header/HeaderMenu.tsx, src/contexts/daoData/daoData.ts, src/contexts/daoData/types/daoLegacy.ts, src/contexts/daoData/useDAOLegacy.ts, src/pages/DaoFavorites/index.tsx
Adds hook and UI to show a user DAO connections
- Branch has been rebased on top of #298 
- Extracted UI components for reuse
- Update Favorites UI and functionality to match Details Page.
There are a few issues with loading and component leaks.
- When navigating from Fractal DAO 'home' to details page. a component leak error is shown. There is a second render after load that needs be looked into not sure what is causing it?
=> DAO Legacy

src/components/Dao/ClaimToken.tsx, src/components/Dao/Summary.tsx, src/contexts/daoData/daoData.ts, src/contexts/daoData/types/token.ts, src/contexts/daoData/useClaimModule.ts, src/contexts/daoData/useTokenData.ts, src/hooks/useClaimToken.ts, src/hooks/useExecuteTransaction.ts
This PR:
- Adds hooks and types for getting user token claim amounts
- Adds a claim token component that enables a user to claim tokens for a new child DAO. This component renders on  the DAO summary page only when a user has more than zero tokens to claim
=> Token claim

src/components/ui/Header/MenuItems.tsx
Fixes Broken Header Links
closes #368
=> fixes broke links

src/components/ui/forms/Button.tsx
Removed the default outline on buttons when button is focused
closes #391
=> removed 'focus' outline on buttons

src/hooks/useDeployDAO.ts
When updating the dependencies, this error popped. weird it didn't show it's face before. Anyway added the missing types
=> fix missing types

.github/PULL_REQUEST_TEMPLATE.md
A straight forward PR template.
- Open to discussion and changes
- Let's get everyone's approval to move forward.
n/a
- Will test once merged in develop and next PR is open.
- should have useful sections for reviewer
- should have useful descriptions for author
n/a
=> adds a pr template

src/components/DaoCreator/gnosis/GnosisConfig.tsx, src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx, src/components/DaoCreator/tokenVotingGovernance/SubsidiaryFunding/index.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx, src/components/ui/forms/Input.tsx
replaces the char restriction props into a single ENUM controlled prop
Solves issue where the Input component can be implemented with `isWholeNumbers` and `isFloatNumbers`, This will cause the two methods to conflict with each other.
discussed in #474
no Visual QA is needed. More just a technical review
n/a
=> Combine char restrictions

src/components/DaoCreator/DisplayStepController.tsx, src/components/DaoCreator/SubsidiaryFunding/FundingOptions.tsx, src/components/DaoCreator/SubsidiaryFunding/index.tsx, src/components/DaoCreator/SubsidiaryFunding/types/index.ts, src/components/DaoCreator/provider/types/index.ts, src/controller/Modules/GovernanceController.tsx, src/controller/Modules/injectors/GnosisGovernanceInjector.tsx, src/controller/Modules/injectors/GnosisTreasuryInjector.tsx, src/controller/Modules/injectors/GovernanceInjectorConext.tsx, src/controller/Modules/injectors/TokenGovernanceInjector.tsx, src/controller/Modules/injectors/TreasuryInjectorContext.tsx
Removes Subsidiary Funding dependency on Fractal Treasury Module.
closes #479
Creating a subDAO should continue working as usual.
n/a
=> 479 Removes Subsidiary Funding dependency

src/components/DaoCreator/SubsidiaryFunding/index.tsx, src/components/DaoCreator/SubsidiaryFunding/types/index.ts, src/controller/Modules/TreasuryController.tsx, src/controller/Modules/injectors/TokenGovernanceInjector.tsx
This small update adds subsidiary funding bignumber support
n/a
- Create a 1:1 Token Voting subDAO from a 1:1 Token Voting Parent and fund using a large decimal number.
n/a
=> subsidary funding to support big numbers

src/providers/treasury/types/coingecko.ts
Add semicolons which were causing linter warnings.
n/a
n/a
On `develop` run `npm run lint` and notice that there are errors.
On this branch run `npm run lint` and notice that there are no more errors.
n/a
=> Add semicolons

package-lock.json
The existence of this PR is a failure of our previous processes.
=> Updates to package-lock.json from `npm install`

package-lock.json, src/components/DaoCreator/StepButtons.tsx
Sets the label to Skip on Funding if no assets are added for funding.
https://github.com/decent-dao/fractal-interface/issues/457
On your DAO, go to +Transaction -> Create a subDAO -> Next -> Next ->
Observe the button now says 'Skip'
Add a token or NFT, button changes to 'Next'
Remove all tokens and NFTs, button changes back to 'Skip'
=> Skip label for Funding

src/providers/treasury/hooks/useTreasuryEvents.ts
Remove `getPastEvents` function in `useTreasuryEvents`, which loses typing on event filtering. Adds typing back into code that gets data from those events.
n/a
n/a
n/a
n/a
=> Replace typing on Treasury Module Event Filtering

.github/ISSUE_TEMPLATE/bugs.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/features.yml
Fixed a typo and made some modifications, now that I can actually see what this looks like..
=> issue template updates

package-lock.json, package.json, src/App.tsx, src/components/menus/AccountDisplay/MenuButtonDisplay.tsx, src/components/menus/AccountDisplay/MenuItems.tsx, src/components/menus/AccountDisplay/index.tsx, src/components/menus/DAONavigation/index.tsx, src/components/ui/Header/Avatar.tsx, src/components/ui/Header/index.tsx, src/components/ui/toasts/useActionToast.tsx
Relies on #553
adds the basic layout of header
- There will be follow up PRs for the individual pieces of the header
- I also will be updating the theme's global css to better style the web3Modal wallet selection popup in a future release of the fractal-ui package
close #539
close #540
Now able to connect/disconnect. I'll be updating the tests in a future PR.
=> V1 design | Header Layout

package-lock.json, package.json, src/assets/theme/index.ts, src/assets/theme/web3modal.ts, src/index.tsx
Originally this existed as part of the theme's global object that contains some css classes. Needing to adjust a few classes I realized that either Web3Modal would need to be added to the Design System repo, and create a story, etc there, or I need to bring the styling here.
This PR moves the styling back to Fractal-Interface codebase and updates the Decent-UI version to the lastest
I tried to clean the styling very similar to what it was previously. see screenshots
=> V1 Design | Web3Modal Style Update

.github/ISSUE_TEMPLATE/bugs.yml, .github/PULL_REQUEST_TEMPLATE.md
Add a note to the PR template to add accompanying Notion doc to the PR, and fix the newline madness of the Issue template
=> PR template update, and fix Issues template

src/App.tsx, src/components/Body.tsx, src/components/ui/ContentBox.tsx, src/components/ui/ContentBoxTitle.tsx, src/pages/Home/index.tsx, src/routes/FractalRoutes.tsx
First in a series of PRs to replace the current MVP components with Chakra-UI components, using similar designs to MVP. The goal is to change the UI as little as possible but get app back into a testable state for the USUL modules, as well as get to a place where we can focus on the updates to the new DAO screens
=> V1 design | MVP splash page

src/components/ui/Favorite.tsx
1. Added gnosis dao types to the Favorite component.
2. Added the address type to be able to be added and removed.
I kept the MVD DAO type within the favorite component; therefore, both dao types are supported. There will need to be the removal of this in the future.
=> Pivot: Favorites list #563

package-lock.json, package.json, src/components/DaoCreator/ChooseGovernance.tsx, src/components/DaoCreator/provider/types/index.ts, src/components/ui/Sidebar/index.tsx, src/components/ui/forms/Radio/RadioWithText.tsx
Updates Choose Governance component with Chakra components
- I took some liberties with the layout of the page, while we wait on the offical designs
=> V1-design | MVP Choose Governance

package-lock.json, package.json, src/components/DaoCreator/gnosis/GnosisConfig.tsx, src/components/DaoCreator/gnosis/GnosisSignature.tsx
Replaced Gnosis page with Chakra-UI components
=> V1 Design | gnosis pure deploy (mvp)

package-lock.json, package.json, src/components/DaoCreator/DAODetails.tsx, src/components/DaoCreator/provider/hooks/useNextDisabled.ts, src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx, src/components/ui/ContentBanner.tsx
=> V1 Design | Gnosis Usul

src/components/ui/Sidebar/index.tsx, src/routes/DAORoutes.tsx, src/routes/constants/dao.ts
Within a DAO
Splash (removed DAO navigation in sidebar)
=> V1-Design | Reenable DAO Routes

src/App.tsx, src/pages/Home/index.tsx, tests/home/visit.spec.ts
This fixes the app stretching to large on big screens
1440x1000
1815x1000
=> V1 Design | content breakpoint

.github/workflows/e2e-tests.yml, docker/webapp/Dockerfile, playwright.config.ts
=> testing playwright image container

.github/workflows/e2e-tests.yml, docker/webapp/Dockerfile, playwright.config.ts, src/contexts/web3Data/utils/injectedProvider.ts
Quick Bug fix. Low Priority, the wallet menu wasn't showing after disconnecting and clicking connect. when local provider envs are provided. (this might affected some tests)
=> Bug | Wallet Disconnect

package-lock.json, package.json
Quick PR to update to lastest `@decent-org/fractal-ui` version.
=> Package Update | `decent-org/fractal-ui`

src/App.tsx, src/components/DaoCreator/gnosis/GnosisConfig.tsx, src/components/ui/proposal/ProposalTime.tsx, src/i18n/locales/en/common.json, src/i18n/locales/en/proposal.json, src/pages/Treasury/hooks/useFormatTransfers.tsx
- adds bottom margin to the app main content
- fixes treasury "days ago" text that changed when proposals text changed it
- prevents rendering too many inputs in the Safe DAO creation page
closes https://github.com/decent-dao/fractal-interface/issues/701
Before
After
=> Misc bug fixes

src/pages/ProposalCreate/index.tsx, src/utils/arrays.ts, src/utils/dev.ts
Adds a secret dev environment only function to populate test data into the create proposal fields.
In the Proposal Creation screen, click the "Create Proposal" title header to populate proposals.
=> Proposal testing

src/pages/Proposals/index.tsx, src/pages/Treasury/index.tsx
- only shows Delegate for Usul DAOs
- hides Send Assets permanently, for now pending transaction work needed
closes https://github.com/decent-dao/fractal-interface/issues/728
=> only show delegate on Usul, and hide send assets completely

src/components/DaoCreator/tokenVotingGovernance/GovernanceDetails.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx, src/components/DaoCreator/tokenVotingGovernance/TokenDetails.tsx, src/i18n/locales/en/daoCreate.json
Moving a few more hardcoded strings from DAO create over to json file.
=> missing DAO create strings in JSON

src/i18n/LanguageSwitcher.tsx
Showing the switcher on dev, for the copy meeting
=> show the language switcher regardless of platform

package-lock.json, package.json
Something is off. in recent release. MenuItem shows white background for some reason
=> revert package version

src/components/ui/cards/DAOInfoCard.tsx
=> adds cursor pointer and increases size of copy icon

src/components/ui/cards/DAOInfoCard.tsx
=> Hotfix | Show correct DAO name on Node Page.

src/components/Proposals/MultisigProposalDetails/index.tsx, src/components/Proposals/ProposalsList.tsx, src/components/Proposals/UsulDetails/index.tsx, src/components/ui/cards/DAOInfoCard.tsx, src/hooks/DAO/useDAOController.ts, src/pages/Proposals/index.tsx, src/providers/Fractal/governance/hooks/useGnosisGovernance.ts, src/providers/Fractal/hooks/useGnosisApiServices.ts
=> Update | No account DAO viewing

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/hooks/DAO/useDAOController.ts, src/hooks/DAO/useSearchDao.ts, src/hooks/safe/useIsSafe.ts
A bit of a refactor of components involved in DAO search to improve usability.
closes https://github.com/decent-dao/fractal-interface/issues/830
closes https://github.com/decent-dao/fractal-interface/issues/780
Also fixes attempting to load an address via the URL manually for a non Safe
Search field no longer requires clicking twice to focus it
=> Search refactor

src/constants/url.ts, tests/home/visit.spec.ts
Fixes broken link. Updates to main section of site to fix tests
=> Bug Fix | update documentation depreciated link

src/pages/DaoCreate/index.tsx
Auto favorites a DAO upon deployment
Create a new multisig or Usul DAO, verify that the DAO is added to the favorites list
=> Automatically favorite the DAO upon deployment

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx
This PR: 
1) Makes DAO search string be selected when clicked
2) Makes the cursor have pointer state when hovering over "View DAO" button
https://github.com/decent-dao/fractal-interface/issues/882
https://github.com/decent-dao/fractal-interface/issues/883
=> Search select

package-lock.json, package.json
see [tag release](https://github.com/decent-dao/decent-ui/releases/tag/release-v0.1.7)
=> Update |  `@decent-org/fractal-ui` version to 0.1.7

tests/models/FractalPage.ts, tests/models/HomePage.ts
The tab tests were failing again. may have been a slight merge mix up. but combined some what I saw in the timeline into a new solution. should be done with this issue now 🤞
=> BugFix | fixes new tab tests

src/components/ProposalCreate/Transaction.tsx
Replaces TextareaComponent with InputComponent.
Closes #939
=> BugFix: Remove scroll bars on Inputs

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/hooks/DAO/useSearchDao.ts
Switched over the component to use `Popover` instead of the `Menu` Component
Closes #902
=> BugFix: Search Bar Issues

playwright.config.ts, tests/home/visit.spec.ts, tests/models/FractalPage.ts, tests/models/HomePage.ts
Hopefully (🤞) fixes the new tab jankiness, and brings back a homepage test for a disconnected wallet.
=> tab fix, bring back disconnected test, and refactor

src/providers/NetworkConfig/rainbow-kit.config.ts
Adds support for coinbase wallet connection.
=> add coinbase wallet support

src/hooks/DAO/useDAOName.ts
=> BugFix: Not using lastest registry event for name

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/i18n/locales/en/proposalMetadata.json, src/pages/Treasury/hooks/useSendAssets.ts
- [better send assets title / description](https://github.com/decent-dao/fractal-interface/commit/5165a82d43b1f495577913a0b88d606e677db461)
- [search box UI tweaks](https://github.com/decent-dao/fractal-interface/commit/d509b610d313162a68091cfe205dde69a6eb1e50)
**Before**:
**After**:
- [close search and clear text when clicking to view the result or outside](https://github.com/decent-dao/fractal-interface/commit/35703e5177e2b7a5825f1a6ac45e97a2f6dc935d)
=> minor bug fixes

NETWORK_SUPPORT.md
Documenting steps necessary to add additional EVM support
=> network support doc

src/hooks/DAO/proposal/useQueueProposal.ts
=> update queue proposal hook to use correct contract when queuing

.github/workflows/release-ipfs-dev.yaml, .github/workflows/release-ipfs-prod.yaml, IPFS_HOSTING.md, README.md
Documentation for our IPFS hosted version of the app.
=> IPFS hosting documentation

src/hooks/DAO/useDAOName.ts, src/providers/Fractal/governance/hooks/useUsulProposals.ts, src/providers/Fractal/governance/hooks/useVotingContracts.ts, src/providers/Fractal/hooks/useGnosisModuleTypes.ts, src/providers/Fractal/hooks/useVetoContracts.ts, src/providers/Fractal/utils/usul.ts, src/providers/NetworkConfig/NetworkConfigProvider.tsx
This PR, replaces queryFilters using `asProvider` to using the connected wallet's RPC when requesting events from the blockchain. This PR also removes support for Polygon network for now
=> Refactor | Use Signer when connected for querying events

src/hooks/DAO/useCreateSubDAOProposal.ts, src/i18n/locales/en/proposalMetadata.json, src/providers/Fractal/hooks/account/useLocalStorage.ts
a small tweak to reduce total cache size, as these keys will be used constantly in future caching
=> single character cache keys

src/components/Proposals/ProposalSummary.tsx, src/components/ui/utils/ProgressBar.tsx, src/i18n/locales/en/proposal.json, src/i18n/locales/uk/proposal.json
Removes the redundant quorum bar and shifts the indicator line slightly so it's touching the progress indicator
closes https://github.com/decent-dao/fractal-interface/issues/1010
=> remove quorum bar and tweak quorum indicator

src/constants/url.ts
Change Discord URL from Decent's to Fractal's
=> Discord url update

src/components/ui/cards/DAOInfoCard.tsx, src/constants/url.ts, src/providers/Fractal/FractalProvider.tsx, src/providers/Fractal/hooks/useNodes.ts, tests/home/external-links.spec.ts
- add another use of getEventRPC
- make subDAO count clickable to take you to Hierarchy
- update Discord URL to Tom's invite
=> asProvider fix

src/components/ProposalCreate/Transaction.tsx, src/components/Proposals/ProposalVotes.tsx, src/components/ui/containers/ProposalDetailsGrid.tsx, src/pages/ProposalCreate/index.tsx
Last in the ETH Denver Happy Path Mobile Ready. I would open the Deploy Preview on your mobile phone for mobile screens viewing. You can do in the dev tools as well. just keep in mind in the ExecutedCode in Proposal Details the scroll bar is different on mobile.
=> Refactor | Mobile Ready Usul Details and Create Proposal 

src/providers/NetworkConfig/rainbow-kit.config.ts
Adds support for Injected wallet other than Metamask. NOTE: This won't show anything new in the UI, This covers other 'injected wallets' that are not metamask.
> Rainbow kit recommends that this is always added
https://www.rainbowkit.com/docs/custom-wallet-list
=> add injected wallet support

src/hooks/DAO/useDAOController.ts
While looking for where the `eth_call` are coming from discovered a issue with our DAOController being called multiple times in one render. Removed some unneeded dependencies and is now working normally only dispatching once.
=> BugFix | DAO controller loads more than once

src/pages/ProposalCreate/index.tsx
=> ensures proposal details goes to one column on smaller screens

src/components/ui/cards/DAOInfoCard.tsx, src/pages/DaoDashboard/Info/InfoDAO.tsx, src/pages/FractalNodes/DaoNode.tsx, src/pages/FractalNodes/NodeLines.tsx, src/pages/FractalNodes/index.tsx, src/pages/FractalNodes/useFetchNodes.tsx, src/providers/Fractal/FractalProvider.tsx, src/providers/Fractal/constants/actions.ts, src/providers/Fractal/hooks/useGnosisModuleTypes.ts, src/providers/Fractal/hooks/useNodes.ts, src/providers/Fractal/reducers/gnosis.ts, src/providers/Fractal/types/actions.ts, src/providers/Fractal/types/state.ts
Fixes and updates loading and UI issues on Node page.
- Move childNodes out of main app state
- Created a Recursive pattern for loading nodes page
- Fixed UI being messed up for 3 generational DAOs
- I did what I could from a small level to fix some multiple requests on load that was happening in the `useNode` hook. There are still a few extra requests here that makes it way to the Nodes page. But these will be resolved as we look at straightening out the Data Layer of the app
- I left the border alone. I could update this to be the Gold `boxShadow` thats used elsewhere in the app? but needed to have something to indicate when you are on the parent DAO (as subtle as it currently is)
- And no longer have the top little bubble. I'm also using `black.900` here instead of the transparent …
=> Bugfix | Slight refactor of node hierarchy

.github/workflows/release-ipfs-dev.yaml, .github/workflows/release-ipfs-prod.yaml
Hardcode env variables that don't need to change or be secret
=> remove unneeded secrets

src/components/ui/cards/DAOInfoCard.tsx, src/pages/FractalNodes/DaoNode.tsx, src/pages/FractalNodes/NodeLines.tsx
A fresh pair of eyes and a quick look I was able to those lines. As a added bonus realized I had control where the line ended now. so vertical line now matches designs
EDIT: new screenshots fixes all node line problems!
Also fixes copy area being long
Closes #1052 
Closes #1071
Closes #1073
=> BugFix | DAO Hierarchy 

src/components/ui/menus/DAOSearch/SearchDisplay.tsx
Found that the error was within the display component which was preventing showing the found DAO
=> Bugfix | ENS lookup error causing component not to update

app/daos/[daoAddress]/layout.tsx, package-lock.json
This PR adds back functionality to showing DAO name in the browser page title - this was removed and not replaced during Next.js migration
Also, made `npm i` which updated `package-lock.json`
N/A
1. Go to any DAO page (Dashboard/Treasury/Proposals/Hierarchy)
2. Verify that DAO name appears in the page title after few moments.
=> Show daoRegistryName in browser title

src/components/Proposals/MultisigProposalDetails/TxActions.tsx
=> Fix typo in TxActions.tsx

src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/useFractalTreasury.ts, src/providers/App/treasury/action.ts, src/providers/App/treasury/reducer.ts, src/types/fractal.ts
Adds fractal treasury into state
=> Refactor DataLayer | fractal treasury

src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/loaders/useFractalGuardContracts.ts, src/providers/App/guard/action.ts, src/providers/App/guard/reducer.ts
=> Refactor DataLayer | Freeze Guard and Contracts

app/daos/[daoAddress]/proposals/page.tsx, src/components/Proposals/ProposalsList.tsx, src/components/Proposals/index.tsx, src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts, src/components/pages/DaoDashboard/Activities/index.tsx, src/components/pages/DaoDashboard/Info/InfoProposals.tsx, src/hooks/DAO/loaders/governance/useSafeMultisigProposals.ts, src/hooks/DAO/loaders/useFractalNode.ts, src/hooks/DAO/proposal/useProposals.ts, src/hooks/DAO/useDAOController.ts, src/hooks/utils/useSafeTransactions.ts, src/providers/App/AppProvider.tsx, src/providers/App/governance/reducer.ts, src/providers/App/node/reducer.ts, src/types/fractal.ts
=> Refactor DataLayer |  DAO proposals page

app/daos/[daoAddress]/hierarchy/page.tsx, src/components/pages/DaoHierarchy/DaoNode.tsx, src/components/pages/DaoHierarchy/NodeLines.tsx, src/components/ui/cards/DAOInfoCard.tsx, src/components/ui/menus/OptionMenu.tsx, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/loaders/useFractalGuardContracts.ts, src/hooks/DAO/loaders/useFractalNode.ts, src/hooks/DAO/useDAOController.ts, src/hooks/DAO/useSubDAOData.ts, src/types/common.ts, src/types/daoGeneral.ts
Update Node Heirarchy with new setup
This PR updates the loader hooks for reuse here. `useFractalNode`, `useFractalFreeze`, `useFractalGuardContracts` to pull all the needed information for the child DAO.
This updates `useFetchNodes` to use these loader hooks to pull each and every childDAO all the way down!
=> Refactor DataLayer | node hierarchy

app/daos/[daoAddress]/treasury/page.tsx, src/components/pages/DAOTreasury/components/Assets.tsx, src/components/pages/DAOTreasury/components/Transactions.tsx, src/components/ui/links/EtherscanLinkAddress.tsx, src/components/ui/modals/SendAssetsModal.tsx, src/hooks/DAO/loaders/useFractalTreasury.ts, src/hooks/DAO/useDefaultNonce.ts, src/hooks/utils/useUpdateTimer.tsx
Updates Treasury Page with new Context Provider. No big changes in this one
=> Refactor DataLayer | Update Fractal treasury with new provider

app/daos/[daoAddress]/proposals/page.tsx, src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/loaders/useFractalGuardContracts.ts, src/hooks/DAO/loaders/useGovernanceContracts.ts
Noticed that the logic I had here was a little off and was preventing updates when DAOs are changed.
This also updates the `showDelegate` variable on the proposals page. it would sometimes error out trying to calculate token balance on first load.
=> Refactor Bugfix | erc20 account update

src/components/pages/DaoHierarchy/DaoNode.tsx, src/components/ui/cards/DAOInfoCard.tsx, src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts, src/hooks/DAO/loaders/useFractalGuardContracts.ts, src/hooks/DAO/loaders/useFractalNode.ts, src/hooks/DAO/proposal/useCastVote.ts, src/hooks/DAO/useDAOName.ts, src/hooks/utils/useAddress.ts
Some more bugs from the list.
On top the above, saw some issues with the listeners when voting. I separated into separate `useEffect` and seem to work smoother
=> Refactor |  Next set of various bug fixes

.github/ISSUE_TEMPLATE/bugs.yml, .github/PULL_REQUEST_TEMPLATE.md
=> simplify bug reporting and PR template

src/components/ProposalCreate/ProposalHeader.tsx, src/components/pages/ManageSigners/AddSignerModal.tsx, src/components/pages/ManageSigners/RemoveSignerModal.tsx, src/components/ui/forms/CustomNonceInput.tsx
This PR adds custom nonce inputs for both the add signers and remove signers modals.
=> Signers custom nonce

src/components/pages/DaoDashboard/Info/InfoDAO.tsx, src/components/ui/cards/DAOInfoCard.tsx, src/components/ui/containers/InfoBox.tsx, src/hooks/DAO/proposal/useSubmitProposal.ts
=> Node lines fix

src/utils/crypto.ts
We don't parse array params correctly in the proposal creator, this fixes that.
=> fix not supporting array params

.github/workflows/release-ipfs-dev.yaml, .github/workflows/release-ipfs-prod.yaml, .github/workflows/release-ipfs-staging.yaml
This PR adds missing step of building GraphQL assets during IPFS release
=> Add missing graphql assets building

src/components/Activity/ActivityAddress.tsx, src/components/ui/links/EtherscanLinkBase.tsx, src/helpers/activity.ts, src/hooks/DAO/loaders/useFractalGovernance.ts, src/hooks/utils/useParseSafeTxs.tsx, src/hooks/utils/useSafeTransactions.ts, src/utils/crypto.ts, src/utils/guard.ts
This fixes an issue where multisig subDAOs weren't displaying the timelocked state, so it would always appear as executable, although execution would fail.
I also cleaned up and refactored the state determination logic to hopefully make that cleaner.
=> Fix timelock state not appearing for multisig subDAOs

src/components/CreateProposalTemplate/ProposalTemplateDetails.tsx, src/components/ui/modals/ProposalTemplateModal.tsx, src/components/ui/utils/LineBreakBlock.tsx
=> handle displaying line breaks in templates

src/components/Proposals/AzoriusDetails/index.tsx, src/components/ui/proposal/ProposalCountdown.tsx, src/components/ui/proposal/useProposalCountdown.tsx, src/hooks/DAO/proposal/useExecuteProposal.ts, src/hooks/DAO/proposal/useUpdateProposalState.ts, src/hooks/utils/cache/cacheDefaults.ts, src/hooks/utils/useSafeTransactions.ts, src/hooks/utils/useTimeHelpers.tsx, src/utils/azorius.ts
Still using seconds in timelock calculation, rather than ms
=> Fix timelock state

src/components/pages/DaoDashboard/Info/index.tsx, src/components/pages/DaoHierarchy/DaoNode.tsx, src/components/ui/cards/DAOInfoCard.tsx
Fixes two issues described here:
https://discord.com/channels/1047935566060212335/1078336474862333962/1129404074136195113
=>  Fix DAO home info cards and non Fractal Safe hierarchy

app/daos/[daoAddress]/proposal-templates/new/page.tsx, src/components/DaoCreator/formComponents/GuardDetails.tsx, src/components/ProposalCreate/ProposalHeader.tsx, src/components/ui/forms/CustomNonceInput.tsx
Fixes nonce reverting to default during subDAO creation
Fixes incorrect nonce input alignment everywhere except proposal creation
=> Nonce fixes

.github/SECURITY.md, public/.well-known/security.txt
This needs to hold on merging until https://discord.com/channels/839548879216181309/938459863745445898/1135540302006980659 is resolved.
=> update email references to decent-dao.org

package-lock.json, package.json
Cherry-picked @mudrila 's commit from https://github.com/decent-dao/fractal-interface/pull/1263, but based off of Develop branch so we don't get other changes.
=> Update Next.js version

package-lock.json, package.json
This reverts commit a4024f01c7d0ee1f8c0a259e2382e7f6e8073f15, which broke DAO homepages from loading
=> Revert "Update Next.js version"

src/hooks/utils/cache/useLocalDB.ts, src/providers/App/hooks/useSafeAPI.ts
1. Caches all Safe API get requests to a database for 1 minute
2. Caches all get requests in local memory as well, to avoid multiple API requests before one has resolved
=> Safe Api caching

src/components/DaoCreator/formComponents/EstablishEssentials.tsx, src/hooks/DAO/useBuildDAOTx.ts, src/providers/NetworkConfig/networks/goerli.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/polygon.ts, src/types/network.ts
only allow the NFT governance option on Goerli, for now
switch between chains on the /create page
=> createOptions param

app/layout.tsx
updating the description meta tag to align with current branding/copy
=> update app description tag

package.json
Finish the git flow, started via release process in #1377
=> Bumped version number to 0.1.6

src/components/DaoCreator/hooks/usePrepareFormData.ts
Closes #1433 
An extra conditional was preventing deployment of new multisig DAOs.
=> BugFix: Multisig Deployment Fix

package-lock.json, package.json, src/providers/Providers.tsx
This PR updates the decent UI version. This version removes the background gold glow
Closes #1424
=> Remove Background Glow

src/components/pages/DaoDashboard/Info/InfoTreasury.tsx
=> Fix Treasury Total Format on Dashboard

package-lock.json, package.json
=> BugFix Dev

src/components/ui/menus/AccountDisplay/MenuButtonDisplay.tsx, src/components/ui/menus/AccountDisplay/MenuItemButton.tsx, src/components/ui/menus/AccountDisplay/MenuItemNetwork.tsx, src/components/ui/menus/AccountDisplay/MenuItemWallet.tsx, src/components/ui/menus/AccountDisplay/MenuItems.tsx, src/components/ui/menus/AccountDisplay/index.tsx, src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/components/ui/menus/FavoritesMenu/Favorite.tsx, src/components/ui/menus/FavoritesMenu/FavoritesList.tsx, src/components/ui/menus/FavoritesMenu/index.tsx
- Updates Wallet and Favorites Menu, as well as the Search displays
- We did not have screens for Search displays Designed (realized late). But I think I was able to update these based on other components in the designs
- The Header `MenuButton` and `MenuItems` use the tertiary variant of the button. On closer inspect, This doesn't match the figma design 1:1. Design has been advised on this.
=> `Reskin` | App Layout and Header [Part 2] 

src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/baseSepolia.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts
Tested, and this works as intended
=> Fix subgraph version in network config files

src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
Wrap the JSON.parse in a try catch, so as to not break when metadata is malformed.
Sepolia DAO sep:0x0FAB989675bcbE3adFBAE4eC8E54061CcCE85020 includes a proposal with bad JSON (prop # 29).
See how this DAO doesn't load proposal 29 (or below) on dev, but will load properly (but not display a proposal title, description, or url) for the malformed proposal 29 on this PR.
=> Don't crash with malformed proposal metadata

src/components/Activity/ActivityModule.tsx, src/components/Activity/ActivityTreasury.tsx, src/components/ui/containers/ActivityBox.tsx
=> `Reskin` | fix activity hover

src/components/Proposals/ProposalSummary.tsx, src/hooks/DAO/loaders/governance/useERC20Claim.ts, src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/safe/useSafeContracts.ts
Please review and merge https://github.com/decentdao/fractal-interface/pull/1643 first.
Remove votesTokenMasterCopyContract from useSafeContracts, fix downstream typescript issues.
=> Remove votesTokenMasterCopyContract from useSafeContracts

src/components/pages/DaoSettings/components/Metadata/index.tsx, src/hooks/DAO/useBuildDAOTx.ts, src/types/fractal.ts
Please review and merge https://github.com/decentdao/fractal-interface/pull/1650 first.
Remove keyValuePairsContract from FractalContracts interface, deal with downstream typescript issues
=> Remove key value pairs contract from base contracts

src/hooks/safe/useSafeContracts.ts
Please review and merge https://github.com/decentdao/fractal-interface/pull/1653 first.
=> Remove fractalRegistryContract from useSafeContracts

src/assets/abi/ModuleProxyFactory.ts, src/helpers/crypto.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/DAO/useDeployAzorius.ts, src/hooks/utils/useMasterCopy.ts, src/models/AzoriusTxBuilder.ts, src/models/DaoTxBuilder.ts, src/models/FreezeGuardTxBuilder.ts, src/models/TxBuilderFactory.ts, src/models/helpers/fractalModuleData.ts, src/models/helpers/utils.ts, src/types/contract.ts, src/types/fractal.ts
Please review and merge https://github.com/decentdao/fractal-interface/pull/1656 first.
=> Remove module proxy factory from fractal contracts and base contracts

src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/safe/useSafeContracts.ts
Please review and merge https://github.com/decentdao/fractal-interface/pull/1660 first.
=> Remove the safeSingletonContract object from useSafeContracts

src/components/ui/menus/DAOSearch/index.tsx, src/hooks/utils/useAddress.ts, src/utils/hierarchy.ts
Fixes #1716:
Edit: And #1673 :
=> Fix search box crashing app on manual input

src/i18n/LanguageSwitcher.tsx
Closes #1683 
Implementation screenshot:
=> `Reskin` update languages menu positioning

src/components/Proposals/ProposalCard/ProposalCard.tsx, src/components/Proposals/ProposalSummary.tsx, src/components/ui/badges/QuorumBadge.tsx, src/utils/hierarchy.ts
`votesSummary` is apparently something that _might_ be undefined, as implied by existing undefined checks. I've added those checks to `reachedQuorum` as well. 
_Might possibly address:_ #1724 
Edit for context:
I did search for references in the codebase for a `.no` access attempt, which led me to these files. Untested, obviously, esp since the issue itself isn't consistent. Not linking this PR (or assigning myself to the issue) as I'm not sure if it for sure fixes it. Not sure what to do here actually, in terms of issue management.
=> Memoize reached quorum

src/i18n/locales/en/daoCreate.json, src/i18n/locales/en/dashboard.json, src/i18n/locales/en/proposal.json, src/i18n/locales/uk/daoCreate.json, src/i18n/locales/uk/proposal.json
Closes #1692 
Closes #1739 
Closes #1740 
Closes #1741 
These are all simple text string updates. Just check out the "Files changed" on this PR to see what the updates are.
=> Grammar updates

src/components/ui/menus/AccountDisplay/ConnectedWalletMenuItem.tsx
Closes https://github.com/decentdao/fractal-interface/issues/1742
See screenshot from issue in above link.
Now, see screenshot from this branch:
=> Pfp consistency

src/components/ui/cards/DAOInfoCard.tsx, src/components/ui/cards/DAONodeInfoCard.tsx, src/components/ui/icons/FavoriteIcon.tsx, src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
Fixes #1685 
Fixes #1706 
Followed designs laid out here: https://www.figma.com/file/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?type=design&node-id=0-1&mode=design&t=8YsCQEATr7eLrXaT-0
=> `Reskin` Fix sizes and positionings of icons in DAO Home Info card

src/hooks/DAO/loaders/useFractalNode.ts, src/hooks/DAO/loaders/useLoadDAONode.ts
We need to get this commit backported onto `develop`
This code was originally merged into root reskin through PR https://github.com/decentdao/fractal-interface/pull/1763
=> Update DAOQueryDocument import in useFractalNode and useLoadDAONode

src/components/pages/DaoHierarchy/DaoHierarchyNode.tsx, src/components/ui/cards/DAONodeInfoCard.tsx, src/components/ui/icons/FavoriteIcon.tsx, src/components/ui/links/AddressCopier.tsx
Adds Hover states to Hierarchy card
Allows for children components to be clickable.
- I got everything to work here but did notice that the FavoriteIcon toggle is kinda a precise click. its pretty easy to navigate by mistake. But its really not too bad. 
Closing #1773
=> `Reskin` 1773 dao hierarchy node updates

src/router.tsx
Yikes. Forgot to remove error page before merge. Sneaking this in.
=> Remove hardcoded error page nav

src/hooks/DAO/loaders/useFractalNode.ts, src/providers/App/node/action.ts
TL:DR found that a conditional we have had around for a while was preventing `Safe Created` DAOs from loading properly
- Create a Safe via Safe's UI
- Everything should load correctly now in Decent's UI
=> `BugFix` 1827 Safe Created DAO Page doesn't work

src/components/pages/DaoDashboard/Info/DaoInfoHeader.tsx, src/components/pages/DaoDashboard/Info/InfoProposals.tsx, src/components/ui/cards/DAOInfoCard.tsx
Fixes #1789 
- Move DAO InfoCard's Icons to top row
- Fixes Proposal Title textStyle
- Updates DAOInfoCard Header to be adjust to screen size easier
=> `Reskin` 1789 Info Card Responsiveness update

src/components/DaoCreator/StepButtons.tsx
=> `BugFix` Create Button on Mobile

src/pages/home/AllSafesDrawer.tsx
Branched off #1823 
Done some messing around before with draggable drawer. Thoughts?
=> `Enhancement` Draggable Safe Drawer

src/components/Proposals/ProposalActions/CastVote.tsx, src/components/Proposals/ProposalVotes/ProposalERC20VoteItem.tsx, src/components/Proposals/ProposalVotes/ProposalERC721VoteItem.tsx, src/hooks/DAO/proposal/useCastVote.ts, src/providers/App/governance/reducer.ts, src/types/daoProposal.ts, src/utils/azorius.ts
=> `Reskin` | 1810 rearrange vote choice

.graphclientrc.yml, src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/baseSepolia.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts
=> Bump subgraph version to 0.1.1

src/hooks/utils/useUpdateTimer.tsx, src/pages/404.tsx, src/pages/DAOController.tsx, src/providers/NetworkConfig/web3-modal.config.ts
- Remove instances of VITE_APP_TESTING_ENVIRONMENT because we don't do that anymore
- Use a bigger icon in wagmi metadata for wallet connect and coinbase wallet and things like that
=> Smol update

src/components/ui/menus/DAOSearch/index.tsx, src/pages/home/MySafes.tsx, src/pages/home/SafeDisplayRow.tsx
=> Turn safe list into individual cards

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx, src/components/DaoCreator/index.tsx, src/hooks/DAO/useDeployAzorius.ts, src/pages/daos/[daoAddress]/edit/governance/index.tsx, src/types/createDAO.ts
=> Custom nonce for 'modify' governance workflow

src/components/ui/page/Header/index.tsx
=> increase gap between icons on mobile

src/components/pages/DaoDashboard/Info/ParentLink.tsx, src/components/ui/cards/DAONodeInfoCard.tsx, src/components/ui/menus/SafesMenu/SafeMenuItem.tsx, src/components/ui/menus/SafesMenu/SafesList.tsx, src/hooks/DAO/loaders/useFractalNode.ts, src/pages/home/SafeDisplayRow.tsx
Fixes #1515 
Fixes #1582 
Fixes #1911
=> Safe Loading/Unloading Problems

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/components/ui/menus/SafesMenu/index.tsx, src/components/ui/page/Header/index.tsx, src/components/ui/page/Layout/index.tsx, src/i18n/locales/en/dashboard.json, src/pages/home/HomePage.tsx, src/pages/home/MySafes.tsx, src/pages/home/SafeDisplayRow.tsx
Closes https://github.com/decentdao/decent-interface/issues/1905
Implements everything in the attached issue except for `max-width: 400px` on the search input. That causes all kinds of issues, including:
- ethereum address doesn't fit
- struggling to _not_ apply that max-width on the search input in full-screen modal, _and_ make the search result popup have the correct width
=> Home designs desktop top nav changes

src/assets/theme/components/index.ts, src/assets/theme/index.ts
Works on #1930 
Last PR before final PR (removing Decent-UI package)
=> `1930` Update theme file to replace decent-ui import

package-lock.json, package.json
This will give better and more useful error messages when Bug Report widget can't submit feedback.
=> Bump sentry library to latest version

src/hooks/utils/useTransaction.ts, src/i18n/locales/en/transaction.json
=> `1916` Add insufficient funds error

src/assets/abi/ERC20FreezeVoting.ts, src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/DAO/useDeployAzorius.ts, src/hooks/safe/useSafeContracts.ts, src/models/FreezeGuardTxBuilder.ts, src/models/TxBuilderFactory.ts, src/types/contract.ts, src/types/fractal.ts
Depends on https://github.com/decentdao/decent-interface/pull/1997
=> Remove erc20 freeze voting typechain

src/assets/abi/ERC721FreezeVoting.ts, src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/DAO/useCastFreezeVote.ts, src/hooks/DAO/useDeployAzorius.ts, src/hooks/safe/useSafeContracts.ts, src/hooks/utils/useMasterCopy.ts, src/models/FreezeGuardTxBuilder.ts, src/models/TxBuilderFactory.ts, src/types/contract.ts, src/types/fractal.ts
Depends on https://github.com/decentdao/decent-interface/pull/1999
=> Remove erc721 freeze voting typechain

src/assets/abi/MultisigFreezeVoting.ts, src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/DAO/useCastFreezeVote.ts, src/hooks/DAO/useDeployAzorius.ts, src/hooks/safe/useSafeContracts.ts, src/hooks/utils/useMasterCopy.ts, src/models/FreezeGuardTxBuilder.ts, src/models/TxBuilderFactory.ts, src/types/contract.ts, src/types/fractal.ts
Depends on https://github.com/decentdao/decent-interface/pull/2000
=> Remove multisig freeze voting typechain

src/components/Proposals/MultisigProposalDetails/TxActions.tsx, src/components/pages/DaoDashboard/ERC20Claim.tsx, src/components/ui/modals/DelegateModal.tsx, src/components/ui/modals/UnwrapToken.tsx, src/components/ui/modals/WrapToken.tsx, src/hooks/DAO/proposal/useCastVote.ts, src/hooks/DAO/proposal/useExecuteProposal.ts, src/hooks/DAO/useCastFreezeVote.ts, src/hooks/DAO/useDeployDAO.ts, src/hooks/utils/useApproval.tsx, src/hooks/utils/useTransaction.ts
Depends on https://github.com/decentdao/decent-interface/pull/2003
- Remove unused `contractCall` function from `useTransaction`
- Rename `contractCallViem` to `contractCall` and reorder return properties of `useTransaction`
=> Remove typechain cleanup 3

src/components/DaoCreator/hooks/usePrepareFormData.ts, src/components/Proposals/MultisigProposalDetails/TxActions.tsx, src/components/pages/DaoDashboard/Info/InfoGovernance.tsx, src/components/pages/DaoSettings/components/Signers/modals/AddSignerModal.tsx, src/components/ui/modals/DelegateModal.tsx, src/components/ui/modals/ForkProposalTemplateModal.tsx, src/components/ui/modals/WrapToken.tsx, src/components/ui/proposal/useProposalCountdown.tsx, src/hooks/DAO/loaders/governance/useAzoriusListeners.ts, src/hooks/DAO/loaders/governance/useAzoriusProposals.ts, src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts, src/hooks/DAO/loaders/governance/useERC721LinearStrategy.ts, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/proposal/useCreateProposalTemplate.ts, src/hooks/DAO/proposal/usePrepareProposal.ts, src/hooks/DAO/proposal/useSubmitProposal.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/DAO/useClawBack.ts, src/hooks/schemas/DAOCreate/useDAOCreateTests.ts, src/hooks/schemas/common/useValidationAddress.tsx, src/hooks/utils/useAddress.ts, src/hooks/utils/useBlockTimestamp.ts, src/hooks/utils/useCurrentBlockNumber.ts, src/hooks/utils/useSafeTransactions.ts, src/utils/azorius.ts, src/utils/contract.ts, src/utils/guard.ts
Depends on https://github.com/decentdao/decent-interface/pull/2006
- Remove _almost_ all uses of `useSignerOrProvider`, `useSigner`, and `useProvider`
=> Remove typechain cleanup 6

src/components/DaoCreator/formComponents/GuardDetails.tsx, src/components/Proposals/ProposalVotes/context/VoteContext.tsx, src/components/ui/modals/DelegateModal.tsx, src/components/ui/modals/UnwrapToken.tsx, src/components/ui/modals/WrapToken.tsx, src/hooks/DAO/loaders/governance/useAzoriusListeners.ts, src/hooks/DAO/loaders/governance/useAzoriusProposals.ts, src/hooks/DAO/loaders/governance/useERC20Claim.ts, src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts, src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/governance/useERC721LinearStrategy.ts, src/hooks/DAO/loaders/governance/useERC721Tokens.ts, src/hooks/DAO/loaders/governance/useLockRelease.ts, src/hooks/DAO/loaders/useFractalGovernance.ts, src/hooks/DAO/loaders/useGovernanceContracts.ts, src/hooks/DAO/proposal/useCastVote.ts, src/hooks/DAO/proposal/useExecuteProposal.ts, src/hooks/DAO/proposal/useSubmitProposal.ts, src/hooks/DAO/proposal/useUpdateProposalState.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/utils/useCanUserSubmitProposal.ts, src/providers/App/governanceContracts/reducer.ts, src/types/fractal.ts
Depends on https://github.com/decentdao/decent-interface/pull/2007
- Rename and retype the `FractalGovernanceContracts` properties
=> Remove typechain cleanup 7

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/SafesMenu/SafeMenuItem.tsx, src/components/ui/menus/SafesMenu/SafesList.tsx, src/hooks/DAO/loaders/useFractalGuardContracts.ts, src/hooks/DAO/loaders/useFractalModules.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/DAO/useDeployDAO.ts, src/models/TxBuilderFactory.ts, src/pages/create/index.tsx, src/pages/home/AllSafesDrawer.tsx, src/pages/home/MySafes.tsx, src/pages/home/SafeDisplayRow.tsx, src/types/fractal.ts
Depends on https://github.com/decentdao/decent-interface/pull/2008
- Make a success callback hook use Address type
- Update SafeMenuItem and SafeDisplayRow to accpet Address type
- No more strings that should be Addresses in the TX Builder Factory classes
- Update moduleAddress property from FractalModuleData interface to type Address
=> Remove typechain cleanup 8

src/components/Proposals/ProposalSummary.tsx, src/components/Proposals/ProposalVotes/context/VoteContext.tsx, src/components/pages/DaoDashboard/ERC20Claim.tsx, src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/governance/useLockRelease.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/utils/useCanUserSubmitProposal.ts, src/providers/App/useReadOnlyValues.ts, src/types/fractal.ts
Depends on https://github.com/decentdao/decent-interface/pull/2009
- Change address property type on ReadOnlyUser to Address
=> Remove typechain cleanup 9

src/components/Proposals/MultisigProposalDetails/TxActions.tsx, src/components/pages/DaoHierarchy/DaoHierarchyNode.tsx, src/components/pages/DaoHierarchy/useFetchNodes.tsx, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/loaders/useGovernanceContracts.ts, src/hooks/DAO/proposal/useSubmitProposal.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/DAO/useClawBack.ts, src/hooks/DAO/useCreateSubDAOProposal.ts, src/hooks/DAO/useDeployDAO.ts, src/hooks/DAO/useGetDAOName.ts, src/hooks/stake/lido/useLidoStaking.ts, src/hooks/utils/useAddress.ts, src/hooks/utils/useVotingStrategyAddress.ts, src/providers/App/hooks/useSafeAPI.ts, src/providers/App/node/reducer.ts, src/types/safeGlobal.ts
Depends on https://github.com/decentdao/decent-interface/pull/2011
- Clean up unneeded getAddress calls throughout codebase
- Update SafeInfoResponseWithGuard to have Address address
=> Remove typechain cleanup 11

src/components/Proposals/MultisigProposalDetails/TxActions.tsx, src/components/pages/DAOTreasury/sendAssets.ts, src/components/pages/DaoSettings/components/Signers/hooks/useAddSigner.ts, src/components/pages/DaoSettings/components/Signers/hooks/useRemoveSigner.ts, src/components/pages/DaoSettings/components/Signers/modals/AddSignerModal.tsx, src/components/pages/DaoSettings/components/Signers/modals/RemoveSignerModal.tsx, src/components/ui/modals/SendAssetsModal.tsx, src/helpers/crypto.ts, src/types/transaction.ts
Depends on https://github.com/decentdao/decent-interface/pull/2013
- Slight changes to useAddSigner and useRemoveSigner and associated Modals
- Move some getAddress code
- Update some Safe types to Address
=> Remove typechain cleanup 13

src/components/Activity/ActivityDescriptionGovernance.tsx, src/components/ui/icons/FavoriteIcon.tsx, src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx, src/components/ui/menus/SafesMenu/SafesList.tsx, src/components/ui/modals/DelegateModal.tsx, src/components/ui/page/Header/Avatar.tsx, src/hooks/DAO/loaders/useFavorites.ts, src/hooks/DAO/loaders/useFractalFreeze.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/DAO/useDAOData.ts
Depends on https://github.com/decentdao/decent-interface/pull/2014
- Remove getAddress from a few more files
- Remove more instances of getAddress
- Let Avatar props be Address type
=> Remove typechain cleanup 14

src/hooks/DAO/loaders/loadDemoData.ts, src/hooks/DAO/loaders/useFractalNode.ts, src/hooks/DAO/loaders/useLoadDAONode.ts, src/hooks/DAO/useGetDAOName.ts
Revert "Merge pull request #1964 from decentdao/undo-hardcoded-snapshots"
This reverts commit bee0a5c8b57ec516300f668a48b7f79aeeabca71, reversing changes made to f467566127e308385d8e7dd27543ba67996a4edd.
=> Readd hardcoded snapshots

src/components/Proposals/ProposalActions/CastVote.tsx
=> zero is falsey

src/hooks/DAO/loaders/useHatsTree.ts, src/state/useRolesState.ts
When loading in a Hat Tree, sanitize the Hats Tree by making sure it fits the shape we care about perfectly
=> Tree and Hats type sanitization

src/hooks/DAO/loaders/governance/useAzoriusProposals.ts, src/hooks/DAO/loaders/governance/useERC20Claim.ts, src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/governance/useERC721Tokens.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/utils/useCanUserSubmitProposal.ts, src/hooks/utils/useMasterCopy.ts, src/hooks/utils/useVotingStrategyAddress.ts, src/providers/NetworkConfig/web3-modal.config.ts
This PR represents the first time I'm trying to actually load the app in a browser since this whole project started.
=> Remove typechain cleanup 17

src/components/pages/Roles/RolesDetailsDrawer.tsx
=> `Bugfix` Handle Role Detail drawer closing properly

src/hooks/DAO/useKeyValuePairs.ts
=> Wait 20 seconds for subgraph to index new Hats tree

src/providers/NetworkConfig/NetworkConfigProvider.tsx, src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/index.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts
=> Tentative fix for broken treasury

src/pages/daos/[daoAddress]/roles/edit/index.tsx
=> Set default custom nonce

src/i18n/locales/en/roles.json, src/pages/daos/[daoAddress]/roles/edit/index.tsx
=> Add pluralisation to roles text

src/components/pages/Roles/EditBadge.tsx, src/components/pages/Roles/RolesTable.tsx
=> `2101` add EditBadge to Table

src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
Fixes #2115 
Also noticed that the 'delete role' menu button wasn't aligned correctly (justified with space between) so fixed that too
=> `2115` Don't cover button with sentry

src/components/pages/Roles/forms/RoleFormTabs.tsx, src/i18n/locales/en/roles.json
=> `2135` Add missing translation

src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
=> `2129` Drawer Closing Bug

src/components/pages/Roles/forms/RoleFormCreateProposal.tsx, src/pages/daos/[daoAddress]/roles/edit/index.tsx
=> `2127` Disable submit proposal when submitting

src/components/pages/Roles/forms/RoleFormCreateProposal.tsx, src/components/ui/modals/SendAssetsModal.tsx, src/hooks/utils/useCanUserSubmitProposal.ts, src/i18n/locales/en/modals.json, src/pages/daos/[daoAddress]/proposals/index.tsx, src/pages/daos/[daoAddress]/roles/index.tsx
Closes #2168 
Connected, delegated wallet:
Unconnected wallet, or connect wallet but not yet delegated:
Also blocked from role details:
=> Disallow edit roles navigation if user cannot create proposals

src/components/pages/Roles/RoleCard.tsx, src/components/pages/Roles/RolesDetailsDrawer.tsx, src/components/pages/Roles/RolesDetailsDrawerMobile.tsx, src/components/pages/Roles/RolesTable.tsx, src/components/pages/Roles/forms/RoleFormAssetSelector.tsx, src/components/pages/Roles/forms/RoleFormCreateProposal.tsx, src/components/pages/Roles/forms/RoleFormPaymentStream.tsx, src/components/pages/Roles/forms/RoleFormTabs.tsx, src/components/pages/Roles/forms/useRoleFormEditedRole.tsx, src/components/pages/Roles/types.tsx, src/hooks/DAO/loaders/useHatsTree.ts, src/hooks/schemas/roles/useRolesSchema.ts, src/hooks/utils/useCreateRoles.ts, src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx, src/pages/daos/[daoAddress]/roles/details/index.tsx, src/pages/daos/[daoAddress]/roles/edit/index.tsx, src/pages/daos/[daoAddress]/roles/index.tsx, src/state/useRolesState.ts
Part 1 of 2 of Role Form updates.
This updates all the form components and properties to prep for handling the new typing and structure.
=> `Roles 0.2.0` - Role Form updates 

src/components/pages/Roles/forms/RoleFormAssetSelector.tsx, src/hooks/DAO/loaders/useHatsTree.ts
=> `Bugfix` | Asset amount not properly parsed when going to form field 

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx, src/components/DaoCreator/formComponents/GuardDetails.tsx, src/components/DaoCreator/index.tsx, src/components/pages/DaoSettings/components/Signers/modals/AddSignerModal.tsx, src/components/pages/DaoSettings/components/Signers/modals/RemoveSignerModal.tsx, src/components/pages/Roles/forms/RoleFormCreateProposal.tsx, src/components/ui/forms/CustomNonceInput.tsx, src/components/ui/modals/ProposalTemplateModal.tsx, src/components/ui/modals/SendAssetsModal.tsx
=> `1857` allow 0 custom nonce

src/components/pages/Roles/RolePaymentDetails.tsx, src/hooks/DAO/loaders/useHatsTree.ts
- Was getting an error when Role details component would mount. Discovered that `linearStream.depositAmount` was coming in from subgraph as a string.
- Then I got an error about `payment.amount.bigIntValue` being undefined, added `?`
- Then I got an error about a `getTime()`
=> `Roles | Bugfix`: Typing Errors

src/components/pages/Roles/RoleCard.tsx, src/components/pages/Roles/RolePaymentDetails.tsx, src/components/pages/Roles/RolesDetailsDrawer.tsx, src/components/pages/Roles/RolesDetailsDrawerMobile.tsx, src/components/pages/Roles/RolesTable.tsx, src/components/pages/Roles/forms/RoleFormCreateProposal.tsx, src/components/pages/Roles/forms/RoleFormPaymentStream.tsx, src/components/pages/Roles/forms/useRoleFormEditedRole.tsx, src/components/pages/Roles/types.tsx, src/components/ui/modals/PaymentWithdrawModal.tsx, src/hooks/schemas/roles/useRolesSchema.ts, src/hooks/utils/useCreateRoles.ts, src/pages/daos/[daoAddress]/roles/index.tsx, src/store/roles/rolesStoreUtils.ts
While working on #2262 (Last commit). I noticed that values being properties into the components as `SablierPayment` but our typed different as each value in the form can be 'undefined'. I've added a new typing that extends `SablierPayment` with `Partial` then updated the other components accordingly.
=> `Roles | Update` Add typing for form values for Payments

src/components/pages/Roles/forms/RoleFormAssetSelector.tsx, src/hooks/schemas/roles/useRolesSchema.ts, src/i18n/locales/en/roles.json
Closes #2264 
Adds tests for Amount. and some typing fixes
=> `Roles | Bugfix: 2264` Role schema tests' updates

src/components/pages/Roles/forms/RoleFormPaymentStream.tsx, src/components/ui/utils/DecentDatePicker.tsx
Closes #2267
Did quite a refactor to the DatePicker. I branched off my previous PRs (probably will have conflicts when caught up to root (but I'll fix em). But need those errors cleared to work and test
- Separated Range Versus Single Date Logic
- Removed local component state
- moved drawer operating component `PaymentDatePicker` into `DecentDatePicker`'s container component.
=> `Roles | Update: 2267` Update DatePicker components

src/components/pages/Roles/RolePaymentDetails.tsx
=> Fix amount per week

src/components/pages/Roles/RolePaymentDetails.tsx, src/components/pages/Roles/RolesTable.tsx, src/components/pages/Roles/forms/RoleFormPaymentStream.tsx, src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx, src/components/pages/Roles/types.tsx, src/hooks/DAO/loaders/useHatsTree.ts, src/store/roles/rolesStoreUtils.ts
Closes https://github.com/decentdao/decent-interface/issues/2254
So this code doesn't work.
All the typing checks out, but over in `RolePaymentDetails`, on the line where this happens:
```ts
<GreenStreamingDot isStreaming={payment.isStreaming()} />
```
at runtime `payment` doesn't have an `isStreaming()` function when a new payment is being added.
Trying to figure this out on my own right now, but @Da-Colon if you have any hints plz holler
=> Active payments count

src/assets/theme/components/input/input.base.ts, src/assets/theme/components/input/input.sizes.ts, src/assets/theme/components/numberInput/numberInput.sizes.ts, src/assets/theme/components/textarea/textarea.sizes.ts, src/components/ui/menus/AccountDisplay/index.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/components/ui/menus/SafesMenu/SafesList.tsx, src/components/ui/menus/SafesMenu/index.tsx
Closes #2287 
@xraystyle1980 Given you've updated design for basic Input component - I've applied these changes globally. Just wanna make sure that's the intent with this Search Input update (to get all the inputs updated across da app).
See screenshots
=> Adjust styling for search input and header navigation

src/components/pages/Roles/RolePaymentDetails.tsx, src/components/pages/Roles/RolesDetailsDrawer.tsx, src/components/pages/Roles/RolesDetailsDrawerMobile.tsx, src/components/pages/Roles/forms/RoleFormCreateProposal.tsx, src/components/pages/Roles/forms/RoleFormPaymentStream.tsx, src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx, src/components/pages/Roles/types.tsx, src/hooks/utils/useCreateRoles.ts, src/pages/daos/[daoAddress]/roles/details/index.tsx, src/store/roles/rolesStoreUtils.ts
Spread the love, spread the props.
=> Typing the Push -> `RolePaymentDetails` and `RoleDetailsDrawers`

src/components/pages/Roles/RolesTable.tsx, src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx, src/components/pages/Roles/forms/RoleFormTabs.tsx, src/components/pages/Roles/types.tsx, src/components/ui/modals/ModalProvider.tsx, src/components/ui/modals/PaymentWithdrawModal.tsx, src/hooks/streams/useCreateSablierStream.ts, src/hooks/utils/useCreateRoles.ts, src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
The first commit was the last error preventing proposal submission. Will keep doing QA in the AM 
The rest is going through the comments from PR #2283
=> Typing the Push -> Bugfixes and Feedback

src/components/ui/page/Navigation/NavigationLinks.tsx, src/router.tsx
Turn roles back on
This reverts commit 7c2f9fbb483dbde3756cf5dc15304168833aa4ca, reversing changes made to 47f64f62cb81ac008b83898d5063687e9150b167.
=> Revert "Merge pull request #2324 from decentdao/no-roles"

.env, src/components/pages/Roles/RoleCard.tsx, src/components/pages/Roles/RolesDetailsDrawer.tsx, src/components/pages/Roles/RolesDetailsDrawerMobile.tsx, src/components/pages/Roles/RolesTable.tsx, src/components/pages/Roles/forms/RoleFormTabs.tsx, src/constants/common.ts
=> `2327` add feature flag for streams

src/providers/App/hooks/useIPFSClient.ts
=> Throw toast when IPFS infura errors

src/components/pages/DAOTreasury/components/Transactions.tsx, src/hooks/DAO/loaders/useDecentTreasury.ts, src/providers/App/treasury/action.ts, src/providers/App/treasury/reducer.ts, src/types/fractal.ts
Closes #2367
Also updated some logic around treasury loading indication, which was half-implemented and missing.
=> Treasury page fixes

src/components/pages/DaoDashboard/Info/InfoProposals.tsx, src/hooks/DAO/loaders/governance/useAzoriusProposals.ts, src/providers/App/governance/action.ts, src/providers/App/governance/reducer.ts, src/types/fractal.ts
Fixes https://github.com/decentdao/decent-interface/issues/2375
Reverts https://github.com/decentdao/decent-interface/pull/2074
We will now no longer artificially hide Decent's first proposal, which has invalid metadata (malformed JSON).
=> Don't artificially hide Decent's first prop

src/hooks/utils/useAddress.ts
=> Catch the error when `normalize` throws in `useAddress`

src/components/pages/Roles/forms/RoleFormPaymentStream.tsx, src/components/ui/utils/DecentDatePicker.tsx, src/hooks/schemas/roles/useRolesSchema.ts, src/i18n/locales/en/roles.json
=> Date range update

package-lock.json
Active payment missing from develop:
http://app.dev.decentdao.org/roles?dao=eth:0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064
But here it is on this deploy preview:
https://deploy-preview-2383.app.dev.decentdao.org/roles?dao=eth:0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064
=> Re-resolve correct version (1.2.14) of `@fractal-framework/fractal-contracts`

src/providers/App/hooks/useBalancesAPI.ts, src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts, src/types/network.ts
=> Prevent fetching DeFi positions when Moralis does not support it

src/i18n/locales/en/common.json, src/pages/DAOController.tsx
Pass success and error callback, use plain switchChain in DAOController
=> Attempted fix for flashing while automatically switching chain

src/hooks/utils/useAddress.ts, src/store/roles/rolesStoreUtils.ts
Make sure all hats going through sanitize have checksummed wearer addresses
=> Checksum wearer addresses

src/components/DaoCreator/StepController.tsx, src/components/pages/DaoSettings/DAOSettingsContent.tsx, src/components/pages/DaoSettings/components/GeneralSettingsContainer.tsx, src/components/pages/DaoSettings/components/GovernanceContainer.tsx, src/components/pages/DaoSettings/components/ModulesContainer.tsx, src/components/pages/DaoSettings/components/PermissionsContainer.tsx, src/components/pages/DaoSettings/components/SettingsSection.tsx, src/i18n/locales/en/settings.json, src/models/FreezeGuardTxBuilder.ts, src/pages/daos/[daoAddress]/SettingsPage.tsx, src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts, src/router.tsx, src/types/createDAO.ts
- This PR contains components restructuring in order to match new design (multiple pages on mobile, single page on desktop)
- Also slightly adjusts usages of `SectionSettings` and adjusts component itself to simplify further usage in newly created (but without actual implementation) components
=> `[Whitelisting]` Settings page restructuring

src/assets/abi/LinearERC20VotingWithHatsProposalCreation.ts, src/assets/abi/LinearERC721VotingWithHatsProposalCreation.ts, src/components/pages/Roles/forms/RoleFormInfo.tsx, src/components/pages/Roles/types.tsx, src/components/ui/cards/DAOInfoCard.tsx, src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx, src/hooks/DAO/loaders/useGovernanceContracts.ts, src/hooks/DAO/loaders/useHatsTree.ts, src/hooks/DAO/proposal/useSubmitProposal.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/schemas/roles/useRolesSchema.ts, src/hooks/utils/useCanUserSubmitProposal.ts, src/hooks/utils/useMasterCopy.ts, src/hooks/utils/useVotingStrategiesAddresses.ts, src/i18n/locales/en/roles.json, src/pages/daos/[daoAddress]/roles/edit/index.tsx, src/providers/App/governanceContracts/reducer.ts, src/store/roles/rolesStoreUtils.ts, src/store/roles/useRolesStore.ts, src/types/fractal.ts
- Support multiple voting strategies
- Read whether role is whitelisted for proposals creation
- Add UI control to toggle role whitelisting (only UI element so far)
=> `Whitelisting` Multiple voting strategies support

src/components/ui/DecentTooltip.tsx
=> [BUGFIX] Fix tooltip text color

src/components/pages/Roles/EditBadge.tsx, src/components/pages/Roles/RoleCard.tsx, src/components/pages/Roles/RoleTerm.tsx, src/components/pages/Roles/RoleTermDetails.tsx, src/components/pages/Roles/RolesTable.tsx, src/components/pages/Roles/types.tsx, src/pages/daos/[daoAddress]/roles/index.tsx
Adds the `inactive` badge to roles whose terms have ended
=> Termed roles badge

src/components/pages/Roles/RoleTerm.tsx, src/hooks/utils/useCreateRoles.ts
=> Termed roles start next term

src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
Quick little bugfix when creating a termed role proposal. 
There will be reckoning for this section of code but not today. in the meantime this removes this error. when creating a new role.
=> remove no wearer throw error

src/components/Roles/RoleCard.tsx, src/components/Roles/RoleDetailsTabs.tsx, src/components/Roles/RoleTerm.tsx, src/components/Roles/RoleTermDetails.tsx, src/components/Roles/RolesTable.tsx, src/pages/dao/roles/SafeRolesPage.tsx, src/store/roles/rolesStoreUtils.ts, src/types/roles.tsx
Doing some testing, noticed that the term status wasn't showing correctly the way I had originally set it up, cleaned up the typing to just be a boolean and updated the affected components
=> `Bugfix` Inactive not showing

src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts
Update network configs to enable all the available create options, since contract were deployed 🎉
=> Fix missing DAO creation 

src/hooks/utils/useAddressContractType.ts
`getAddressContractType` was causing an infinity loop in `useAzoriusListeners` cause it wasn't wrapped in `useCallback` but was coming from the hook.
=> Wrap `getAddressContractType` in `useCallback`

src/components/DaoCreator/StepButtons.tsx, src/components/DaoDashboard/ERC20Claim.tsx, src/components/Proposals/MultisigProposalDetails/SignerDetails.tsx, src/components/Proposals/MultisigProposalDetails/TxActions.tsx, src/components/Proposals/MultisigProposalDetails/index.tsx, src/components/Proposals/ProposalSummary.tsx, src/components/Proposals/ProposalVotes/ProposalERC20VoteItem.tsx, src/components/Proposals/ProposalVotes/ProposalERC721VoteItem.tsx, src/components/Proposals/ProposalVotes/context/VoteContext.tsx, src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVoteItem.tsx, src/components/Proposals/SnapshotProposalDetails/index.tsx, src/components/ui/menus/AccountDisplay/AccountMenuButton.tsx, src/components/ui/menus/AccountDisplay/ConnectedWalletMenuItem.tsx, src/components/ui/menus/AccountDisplay/WalletMenu.tsx, src/components/ui/modals/DelegateModal.tsx, src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/governance/useLockRelease.ts, src/hooks/DAO/loaders/snapshot/useSnapshotProposal.ts, src/hooks/DAO/proposal/useUserERC721VotingTokens.ts, src/hooks/DAO/useBuildDAOTx.ts, src/hooks/utils/useCanUserSubmitProposal.ts, src/pages/dao/edit/governance/SafeEditGovernancePage.tsx, src/providers/App/AppProvider.tsx, src/providers/App/combinedReducer.ts, src/providers/App/useReadOnlyValues.ts, src/types/fractal.ts
This PR only does one thing, removes the `address` property from the `user` object in the `readOnlyValues` state.
=> Remove "address" from user object in read only values

src/components/ui/menus/SafesMenu/index.tsx, src/components/ui/page/Footer.tsx, src/i18n/locales/en/dashboard.json, src/i18n/locales/en/home.json, src/i18n/locales/en/transaction.json
=> Global copy updates

src/components/DaoCreator/formComponents/EstablishEssentials.tsx, src/components/ui/forms/InputComponent.tsx, src/components/ui/forms/LabelWrapper.tsx
closes #2537
No screens. Test validation updates in deploy preview
=> 2537 create safe ens validation

src/hooks/schemas/roles/useRolesSchema.ts
=> `[Issue #2563]` Schema uncaught error

src/components/DaoHierarchy/DaoHierarchyNode.tsx, src/components/ui/cards/DAONodeInfoCard.tsx, src/types/fractal.ts
Closes #2530 
So i'd like this PR -> #2574  -> #2566 to all be merged together and then merged into develop, This will keep the caching for organization page all the same for version one.
=> `[PRD]` | `[Issue #2530]` | Hierarchy voting strategies display

src/assets/theme/components/switch/switch.base.ts, src/components/ui/menus/AccountDisplay/WalletMenu.tsx, src/components/ui/menus/AccountDisplay/index.tsx, src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/components/ui/menus/OptionMenu/index.tsx, src/components/ui/modals/ModalProvider.tsx, src/components/ui/page/Header/index.tsx, src/components/ui/page/Navigation/NavigationLinks.tsx, src/i18n/locales/en/dashboard.json, src/i18n/locales/en/home.json, src/pages/home/GettingStarted.tsx, src/pages/home/HomePage.tsx, src/pages/home/MySafes.tsx, src/pages/home/SafeDisplayRow.tsx
Closes https://github.com/decentdao/decent-interface/issues/2586
Closes https://github.com/decentdao/decent-interface/issues/2589
=> `[PRD]` | New homepage

src/i18n/locales/en/daoCreate.json
Closes https://github.com/decentdao/decent-interface/issues/2602
=> Configure Parent Controls => Configure Administration

src/components/Roles/RoleDetails.tsx, src/components/Roles/forms/RoleFormMember.tsx, src/components/Roles/forms/RoleFormTabs.tsx, src/pages/dao/roles/edit/SafeRolesEditPage.tsx
Addresses https://www.notion.so/hulking-cosmos-3e8/Q4-2024-QA-Requirements-13e2ee9c5bc280a88458e7a935d17488?pvs=4#14d2ee9c5bc280e9a264c3fd107623d7
closes #2582
=> Role details/edit pages cleanup

src/components/ui/cards/DAONodeInfoCard.tsx
=> Remove duplicate display of type in DAONodeInfoCard component

src/pages/dao/roles/edit/details/SafeRoleEditDetailsPage.tsx
Noticed that clicking 'add new role' was resulting in blank page.
=> `[Bugfix | No Issue assigned]` Add New Role not linking to form

src/models/AzoriusTxBuilder.ts, src/models/DaoTxBuilder.ts
Closes https://linear.app/decent-labs/issue/ENG-2/unable-to-create-erc-20-dao-on-dev
=> `[Eng-2]` Unable to create ERC-20 DAO on dev

src/components/ui/menus/SafesMenu/index.tsx
Was lilac, should be white
https://decentdao.slack.com/archives/C06QGNZ83JP/p1734378063082249?thread_ts=1734376631.144939&cid=C06QGNZ83JP
=> Fix color of "My DAOs" button in header

src/hooks/DAO/loaders/useDecentTreasury.ts
Closes https://linear.app/decent-labs/issue/ENG-45/addess-xxx-is-invalid
=> `ENG-45` | Fix Address xyz is invalid bug

.dev.vars.example, .gitignore, README.md, functions/balances/balanceCache.ts, functions/balances/index.ts, functions/balances/middleware.ts, functions/balances/transformers.ts, functions/index.ts, functions/shared/kvCache.ts, functions/shared/moralisApi.ts, functions/shared/moralisTypes.ts, functions/types.ts, package-lock.json, package.json, src/types/daoTreasury.ts, tsconfig.json, vite.config.mts, wrangler.toml
This PR implements all of the infrastructure code necessary to stand up our implementation of our balances API.
This code does not yet hook up the client to use this new API. So, Treasury data will still be missing. You can, however, view the API through direct calls.
https://cf-cloudflare-functions-api.decent-interface.pages.dev/api/balances?address=0xB98d45F9021D71E6Fc30b43FD37FB3b1Bf12c064&network=1
=> [Cloudflare] Cloudflare functions api

src/hooks/DAO/proposal/useSubmitProposal.ts
Closes [ENG-124](https://linear.app/decent-labs/issue/ENG-124/can-not-submit-proposal-multisig)
Not really sure how this one has been here for a month...Look like it happen during a type clean up commit but I ended up removing this.
=> `[ENG-124]` Multisig Proposal Fix

package-lock.json, package.json, src/hooks/DAO/loaders/useFractalNode.ts
Closes ENG-170 
Does not load: https://app.decentdao.org/home?dao=base%3A0x4F6F99828B204bBe6F7a2D014166537e37aCb82C&page=1&size=10
Should load: https://fix-subgraph-bug.decent-interface.pages.dev/home?dao=base%3A0x4F6F99828B204bBe6F7a2D014166537e37aCb82C&page=1&size=10
=> [Hotfix/v0.4.7] Base DAO not loading

src/hooks/DAO/loaders/governance/useERC20LinearToken.ts, src/hooks/DAO/loaders/governance/useLockRelease.ts, src/types/account.ts
Closes [ENG-168](https://linear.app/decent-labs/issue/ENG-168/remove-unused-variable-votingweight-from-votestoken)
=> `[ENG-168]` Unused Variable

src/store/roles/useRolesStore.ts, src/types/roles.tsx
Closes [ENG-176](https://linear.app/decent-labs/issue/ENG-176/termed-payments-showing-on-different-daos)
Before:
After:
=> `[ENG-176]` Termed Payments following user to different DAO

src/components/Roles/RolePaymentDetails.tsx, src/components/Roles/forms/RoleFormPaymentStreams.tsx
Closes [ENG-187](https://linear.app/decent-labs/issue/ENG-187/payment-card)
Works on [ENG-68](https://linear.app/decent-labs/issue/ENG-68/role-payment-ui-tweak)
Changes:
- Extracted out bottom and top components for readibility
- Removed the inline cancel on mobile. Desktop cancel functionality has already been removed.
- Adjusted the textStyle of token label
- Adjusted size of token icon
- Remove center alignment of active streaming green dot.
=> `[ENG-187]` Payment Card UI Update

src/hooks/DAO/loaders/useFractalGovernance.ts, src/hooks/DAO/loaders/useFractalNode.ts, src/providers/NetworkConfig/networks/polygon.ts
Fixes a regression(?) on polygon causing polygon dao subgraph data to not load. Happens only on development since a different url is used in deployed sites.
Also fix an infinite reload bug directly resulting from the failed data load.
=> Fix polygon

package-lock.json, package.json
=> Release candidate for v0.6.0

src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx
Closes [ENG-238](https://linear.app/decent-labs/issue/ENG-238/sub-dao-cannot-create-proposals)
=> `[ENG-238]` Add safe address to proposal submission in SafeGeneralSettingsPage

src/hooks/DAO/loaders/useFractalGovernance.ts
Closes [ENG-260](https://linear.app/decent-labs/issue/ENG-260/sarcophagus-proposal-templates-do-not-load-if-the-safe-is-imported)
=> `[ENG-260]` Handle undefined DAO case by dispatching empty proposal templates

package-lock.json, package.json
=> Release v0.9.0

src/components/GaslessVoting/GaslessVotingToggle.tsx, src/components/ui/modals/GaslessVoting/RefillGasTankModal.tsx, src/i18n/locales/en/gaslessVoting.json
Allow connected wallet to refill paymaster directly without having to go through a proposal
Closes ENG-403
=> `gasless-voting-6` | cleanup 2

src/assets/abi/EntryPoint07Abi.ts, src/components/GaslessVoting/GaslessVotingToggle.tsx, src/components/Proposals/ProposalActions/CastVote.tsx, src/components/Proposals/ProposalSummary.tsx, src/components/Roles/forms/RoleFormPaymentStream.tsx, src/components/ui/modals/GaslessVoting/RefillGasTankModal.tsx, src/constants/common.ts, src/hooks/DAO/useKeyValuePairs.ts, src/hooks/utils/useAddressContractType.ts, src/hooks/utils/useCreateRoles.ts, src/hooks/utils/useInstallVersionedVotingStrategy.ts, src/i18n/locales/en/gaslessVoting.json, src/models/AzoriusTxBuilder.ts, src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx, src/providers/NetworkConfig/networks/base.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/optimism.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts, src/types/network.ts, src/utils/dao/prepareRefillPaymasterActionData.ts
Closes ENG-400
Closes ENG-407
Closes ENG-404
Closes ENG-405
Closes ENG-399
also addresses some of @adamgall's comments on #2760
=> `gasless-voting-5` | cleanup 1

src/components/DaoHierarchy/DaoHierarchyNode.tsx
Closes [ENG-250](https://linear.app/decent-labs/issue/ENG-250/imported-sarcophagus-safe-parent-dao-loads-fine-but-not-subdao#comment-6c4e9614)
Che made a good point that this wasn't quite complete. looking at the code further noticed some redundant error handling going on.
=> `[ENG-250]` Show organization page with imported DAO

src/components/ProposalBuilder/ProposalBuilder.tsx
Closes [ENG-369](https://linear.app/decent-labs/issue/ENG-369/create-proposal-updating-actions-reset-proposal-metadata)
=> `[ENG-369]` Prevent Proposal Metadata from reseting

package-lock.json, package.json, src/hooks/DAO/proposal/useCastVote.ts, src/providers/NetworkConfig/networks/mainnet.ts, src/providers/NetworkConfig/networks/polygon.ts, src/providers/NetworkConfig/networks/sepolia.ts
and adjust gasless voting minimum stake values in network configurations
=> chore: update @fractal-framework/fractal-contracts to version 1.6.0

src/hooks/DAO/proposal/useCastVote.ts
=> Explicity set light smart account index

public/locales/en/actions.json, src/components/ProposalBuilder/ProposalActionCard.tsx, src/components/ui/modals/AddActions.tsx
- actions.json: Add localized strings for single and multiple transaction actions
- ProposalActionCard.tsx: Update rendering logic to use new localized strings
=> `[ENG=679]` feat: Enhance transaction builder action card messages

src/components/GaslessVoting/GaslessVotingToggle.tsx
=> Use network token icon

public/locales/de/proposal.json, public/locales/en/proposal.json, public/locales/es/proposal.json, public/locales/fr/proposal.json, public/locales/it/proposal.json, public/locales/ja/proposal.json, public/locales/ko/proposal.json, public/locales/pt/proposal.json, public/locales/ru/proposal.json, public/locales/uk/proposal.json, public/locales/zh/proposal.json, public/locales/zh_hant/proposal.json, src/components/Proposals/ProposalCard/ProposalCard.tsx, src/components/ui/proposal/ProposalCreatedBy.tsx, src/hooks/DAO/loaders/snapshot/useSnapshotProposals.ts, src/hooks/utils/useSafeTransactions.ts, src/types/daoProposal.ts, src/types/fractal.ts
=> `[ENG-775]` update proposal card 

src/components/ui/modals/AddActions.tsx
=> [ENG-771] fix ActionCard alignment on mobile

public/locales/de/proposal.json, public/locales/en/proposal.json, public/locales/es/proposal.json, public/locales/fr/proposal.json, public/locales/it/proposal.json, public/locales/ja/proposal.json, public/locales/ko/proposal.json, public/locales/pt/proposal.json, public/locales/ru/proposal.json, public/locales/uk/proposal.json, public/locales/zh/proposal.json, public/locales/zh_hant/proposal.json, src/components/Activity/ActivityDescription.tsx, src/components/Activity/ActivityDescriptionGovernance.tsx, src/components/Proposals/ProposalCard/ProposalCard.tsx
=> `[ENG-794]` update proposal author UI

src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx, src/pages/dao/settings/permissions/SafePermissionsCreateProposal.tsx
Merge only after https://github.com/decentdao/decent-app/pull/2991 is merged
=> Remove modify governance settings menu

src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/hooks/DAO/useSearchDao.ts
- src/components/ui/menus/DAOSearch/SearchDisplay.tsx: update search result rendering logic
- src/components/ui/menus/DAOSearch/index.tsx: update main search component logic and props
- src/hooks/DAO/useSearchDao.ts: update DAO search hook logic
=> `[ENG-289]` update DAO search error handling

src/components/GaslessVoting/GaslessVotingToggle.tsx, src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx
=> Update General settings page

public/locales/de/settings.json, public/locales/en/settings.json, public/locales/es/settings.json, public/locales/fr/settings.json, public/locales/it/settings.json, public/locales/ja/settings.json, public/locales/ko/settings.json, public/locales/pt/settings.json, public/locales/ru/settings.json, public/locales/uk/settings.json, public/locales/zh/settings.json, public/locales/zh_hant/settings.json, src/components/SafeSettings/SettingsNavigation.tsx, src/pages/dao/settings/modules-and-guard/SafeModulesSettingsPage.tsx
=> `Eng 456` | Modules and guards UI

src/components/ui/containers/NoDataCard.tsx, src/pages/dao/settings/permissions/SafePermissionsSettingsContent.tsx
=> `ENG-706` | Update permissions UI

src/components/ui/forms/CustomNonceInput.tsx
See comment: https://linear.app/decent-labs/issue/ENG-535/section-metadata-form#comment-5058499e
=> `[ENG-535]` feedback updates to `CustomNonceInput`

src/components/Proposals/ProposalCard/ProposalCard.tsx, src/components/Proposals/ProposalInfo.tsx, src/components/ui/badges/SignerThresholdBadge.tsx
=> `[ENG-814]` update rejection state handling in SignerThresholdBadge component

src/pages/home/SafeDisplayRow.tsx
Just added the reset store action prior to navigating. Seems like the main navigating issue has been taken care of on the home screen.
=> `[ENG-893 ~ to Release]` Reset global store when navigating from home screen

src/components/Proposals/ProposalCard/ProposalCard.tsx, src/components/Proposals/ProposalInfo.tsx
Align the Nonce Label on Dashboard:
Remove the Nonce label on Non-multisig proposals
=> `[ENG-856 ~ to Release]` adjust nonce label

public/locales/en/common.json, public/locales/en/dashboard.json, src/components/ui/menus/DAOSearch/SearchDisplay.tsx, src/components/ui/menus/DAOSearch/index.tsx, src/hooks/DAO/useSearchDao.ts, src/providers/App/hooks/useDecentAPI.ts
- Search DAO with API if input is not valid address or ENS.
- Search DAOs by name through our API, implemented by directly request which should be replace by our sdk when ready.
- Limit height of DAO list and enable scroll if needed, this prevent long list exceed the current screen.
=> `[ENG-869]` support to search daos by name

src/components/Proposals/MultisigProposalDetails/MultisigConflictingProposals.tsx, src/components/ui/containers/AccordionDropdown.tsx
I knew I had thought of this, forgot to switch out a variable. Also went ahead and took care of an alignment issue I discussed with Josh. 
also Closes [ENG-843](https://linear.app/decent-labs/issue/ENG-843/update-to-dropdown-design)
=> `[ENG-850]` remove rejection from count, and alignment updates

public/locales/de/proposal.json, public/locales/en/proposal.json, public/locales/es/proposal.json, public/locales/fr/proposal.json, public/locales/it/proposal.json, public/locales/ja/proposal.json, public/locales/ko/proposal.json, public/locales/pt/proposal.json, public/locales/ru/proposal.json, public/locales/uk/proposal.json, public/locales/zh/proposal.json, public/locales/zh_hant/proposal.json, src/components/Proposals/MultisigProposalDetails/MultisigConflictingProposals.tsx, src/constants/common.ts
=> `[ENG-845]` Rejection threshold pass warning

src/helpers/featureFlags.ts
=> `[ENG-941]` feat: add feature agreement flag to feature flags list

src/store/listener.ts, src/store/listeners/governance.ts, src/store/slices/governances.ts
- listener.ts: implement onProposalExecuted callback
- governance.ts: integrate onProposalExecuted in governance listeners
- governances.ts: add setProposalExecuted to update proposal state
=> `[ENG-1140 | ~ Release]` Add missing Proposal Executed listener

src/hooks/DAO/loaders/useHatsTree.ts, src/store/fetcher.ts, src/store/listener.ts, src/store/roles/useRolesStore.ts, src/types/roles.tsx
Some more testing revealed a little more left to do. I opted to push this closer the pattern in the global store without actually moving and refactoring code into the global store.
=> `[ENG-1143 ~ Release]` Phew Roles loading updated

src/pages/dao/deploy-token/SafeDeployTokenPage.tsx
- Implemented `PageHeader.buttonProps.onClick` to navigate to DAO home page
- Moved `Box` and `PageHeader` component inside `Formik`, to be abled to use `isDisabled: isSubmitting`.
=> `[ENG-1152]` back button should navigate to DAO homepage

src/components/SafeSettings/SettingsNavigation.tsx, src/components/ui/modals/GaslessVoting/RefillGasTankModal.tsx, src/components/ui/modals/SafeSettingsModal.tsx, src/providers/NetworkConfig/networks/sepolia.ts
Simple PR. Min stake on sepolia is suddenly higher. Wonder if the same's happened on mainnet or it's just been updated to match mainnet. Need tests to confirm @cbajandas
=> Inc sep min stake

public/locales/en/proposalMetadata.json, public/locales/en/settings.json, src/components/SafeSettings/SettingsNavigation.tsx, src/components/ui/modals/SafeSettingsModal.tsx, src/pages/dao/settings/token/SafeTokenSettingsPage.tsx, src/store/fetchers/governance.ts, src/store/slices/governances.ts, src/types/account.ts, src/types/fractal.ts, src/utils/valueCheck.ts
- Only display token management inputs when there's token deployed already.
- Display current whitelist parsing from on-chain `Whitelisted` events.
- Support for adding and removing whitelist.
- Batch these changes into single proposal.
=> `[ENG-1070]` Add transfer whitelist to Token tab

src/components/DaoCreator/formComponents/AzoriusNFTDetails.tsx
=> `[ENG-1350]` BugFix: Error Message overlapping description helper text

public/locales/en/revenueSharing.json, src/components/SafeSettings/RevenueShare/RevenueSplitWallets.tsx, src/components/ui/forms/AddressInputInfo.tsx
=> `[ENG-1374]` feat: add staking contract display

src/components/SafeSettings/RevenueShare/RevenueSplitWallets.tsx, src/components/SafeSettings/RevenueShare/SplitPercentageDisplay.tsx
=> `[ENG-1378]` Feedback update on Revenue Share Percentage error UX

src/components/DaoStaking/BalanceCard.tsx, src/store/fetchers/governance.ts, src/store/listener.ts, src/store/listeners/account.ts, src/store/slices/governances.ts, src/types/account.ts
Followed the same pattern we have in place with `VotesToken` and `StakedToken`. where fetch the balance in a separate flow to update the user's current balance.
=> `[ENG-1399]` Support ERC20 token in Staking Page.

src/store/slices/governances.ts
=> `[ENG-1399]` fix erc20Token balance not correctly being hydrated

src/components/DaoStaking/RewardsCard.tsx, src/components/DaoStaking/StakeCard.tsx, src/store/fetchers/governance.ts, src/store/listener.ts, src/store/listeners/account.ts, src/store/slices/governances.ts, src/types/account.ts, src/types/fractal.ts
For consistency, moved to global store with added listener.
=> `[ENG-1441]` Fix Claimable Tokens section with proper data

src/components/SafeSettings/TabContents/staking/SafeStakingSettingTab.tsx, src/store/fetchers/governance.ts, src/store/listener.ts, src/store/listeners/account.ts, src/store/listeners/governance.ts, src/store/slices/governances.ts, src/types/account.ts
The biggest goal of this PR was to get the stakingData. But since I was already in there went ahead and added a few more updates to improve UX of the Settings Staking tab
=> `[ENG-1447 prep]` Move data fetch to governance fetcher, update listeners

src/components/ui/containers/ContentBox/index.tsx, src/components/ui/forms/SectionHeader.tsx, src/pages/dao/token-sale/SafeTokenSalePage.tsx, src/pages/dao/token-sale/components/BuyerRequirementsForm.tsx, src/pages/dao/token-sale/components/ProjectOverviewForm.tsx, src/pages/dao/token-sale/components/SaleTermsForm.tsx, src/pages/dao/token-sale/types.ts
Includes Project Overview, Token Sales and Requirement Sections, Project Overview is "input" completely. Meaning this first push is to get all inputs with general styling and layout ready to go from low-fi designs.
=> `[ENG-1281]` Token Sales Form Initial Setup

src/components/ui/forms/SectionHeader.tsx, src/pages/dao/token-sale/SafeTokenSalePage.tsx, src/pages/dao/token-sale/components/SaleTermsForm.tsx, src/pages/dao/token-sale/types.ts
Can skip filling out the form, and just hit 'create token deployment' currently will fail without a certain token. Push up for visibility
=> `[ENG-1468]` Mock Deployment. 

src/pages/dao/token-sale/SafeTokenSalePage.tsx, src/providers/App/AppProvider.tsx, src/store/fetcher.ts, src/store/fetchers/keyValuePairs.ts, src/store/fetchers/tokenSales.ts, src/store/listener.ts, src/store/listeners/keyValuePairs.ts, src/store/listeners/tokenSales.ts, src/store/slices/tokenSales.ts, src/store/store.ts, src/types/tokenSale.ts
Adds:
- new zustand slice, types, setter and getter functions, etc
- new contract listeners for all the tokenAddresses retrieved from keyValuePairs
- retrieve json data for 'newTokenSales' (currently name and address)
- using addresses, do a multicall to get token sale data
Currently this pretty much just hydrates state with data straight from contract. Will update and adjust as I build out the UI
=> `[ENG-1409]` Getting the Token Sales Data

src/components/TokenSales/TokenSaleCountdown.tsx, src/components/TokenSales/TokenSaleInfoCard.tsx, src/components/TokenSales/TokenSaleProgressCard.tsx, src/components/TokenSales/TokenSalesTable.tsx, src/constants/routes.ts, src/pages/dao/token-sale/SafeTokenSaleDetailsPage.tsx, src/router.tsx
Requirements are currently hardcoded, everything else is live data
=> `[ENG-1488]`  Implement Sale Page
