package-lock.json
package.json
src/App.tsx
src/components/Breadcrumbs.tsx
src/components/ui/svg/LeftArrow.tsx
src/components/ui/svg/RightArrow.tsx

Closes #42 
* Breadcrumbs only show up when within a loaded DAO
* `anyExcludeMatch` captures this -- don't even show the Breadcrumb bar if any of the given locations match
* When breadcrumbs _are_ displayed, "start" them at the "loaded DAO" level (exclude `Home`, and `DAOs`)
* `excludePaths` captures this
* Don't display certain paths (e.g. `Proposals`) when showing breadcrumbs
* path-specific `null` breadcrumbs capture this -- e.g. `{ path: '/daos/:address/proposals', breadcrumb: null },`
* Show dynamic information in Breadcrumbs -- e.g. DAO Name instead of the DAO's address (which is in the URL)
* custom Breadcrumb render components capture this -- e.g. `DAOName` and `ProposalId` components
* Make current path white text, previous paths gold links
No Breadcrumb 👇
No Breadcrumb 👇
Just …

Breadcrumbs

---

src/components/ui/forms/InputBox.tsx

This was going be for changing the  `mx-8` to `px-8` in `InputBox` but after looking at it and other screens. I noticed that all the other inputs have a smaller padding `px-4` in the designs so I just remove it all together

removes mx-8

---

src/components/DAOs/DAO/Proposals/ProposalsList.tsx
src/daoData/daoData.ts
src/daoData/useProposals.ts

Two main things in here:
* Extract contained logic out of `useProposals` and into their own hooks (`useUserVotes` and `useProposalsWithoutVotes`).
* Allowed these pieces of state (most importantly the `proposals` array) to be `undefined`, and made appropriate updates on the UI layer to differentiate between "proposals loading" and "no proposals".

Undefined proposals

---

src/components/ui/Header/HeaderMenu.tsx
src/components/ui/Header/MenuItems.tsx
src/components/ui/Header/index.tsx

Updates Header menu not to flicker when opening on mobile
- Also updates Disconnect text to be red
- removes transition effect when on small screens
- keeps address/menu right aligned when on small screens

Header Mobile update

---

src/daoData/useModuleAddresses.ts
src/daoData/useTokenData.ts

Closes #137 
Cleans up `useModuleAddresses` to allow for intermediate states to be undefined, which leads to a cleaner flow through the data building pipeline complete with early exits along the way.
Also includes a small fix to set `tokenDelegatee` to `undefined` in token information if early exit is happening

Allow intermediate states in useModuleAddresses to be undefined

---

src/components/DAOs/New/index.tsx
src/components/DAOs/Search/DAOSearch.tsx
src/components/DAOs/shared/ConnectWalletToast.tsx

Closes #164 
Extracts the "persistent toast" out of Create a DAO components and into it's own component, which can easily be added anywhere else, like the Search component here.
Also disables Search button unless account is connected.

Search only with account

---

src/daoData/useAccessControlAddress.ts
src/daoData/useDAOName.ts
src/daoData/useSafeRace.ts

The "data layer" in this app is very reactive, built using hooks. Hooks all the way down.
And all data comes from the initial "seed" of a DAO address. When the app is given some address, it'll use that to derive (in async network requests from teh blokchian) everything else it needs about the DAO data. The data layer can also be given an `undefined` address, which is a trigger to un-set all the state back to undefined. This is all achieved using patterns we've been implementing.
But there's a funny lil race condition problem that manifests whenever the data layer is told about different addresses to load, too quickly back to back.
Imagine
The UI layer of the app tells the data layer "here's a DAO address, please load it all up". The data layer is now triggered to fire off seriously many …

Data race safety

---

src/components/DAOs/DAO/Delegate.tsx
src/components/ui/loaders/DataLoadingWrapper.tsx
src/daoData/daoData.ts
src/daoData/useDelegateVote.ts
src/daoData/useTokenData.ts
src/web3/transactions.ts

Closes #130
Closes #154 
Changes include:
- Expose user token balance as a `BigNumber`, UI layer converts to human-readable string
- Remove full screen "transaction pending" modal from Delegate screen when transaction is in progress
- rely on the toast to show outstanding transaction information
- disable the Delegate button while transaction is outstanding
- add yellow bar to bottom of all "outstanding transaction" toasts
- after successful delegation transaction, clear out the Delegate address input box
- Add at-load and realtime-listener data fetching for getting the current account's voting weight (how much voting weight has been delegated to them), expose in `tokenData`
- Display the current account's voting weight on the Delegate page
- clean up the `useDelegateVote` hook a lot

Delegation Component updates and fixes

---

src/components/DAOs/DAO/Proposals/ProposalExecute.tsx
src/daoData/useProposals.ts

This PR updates the useProposals hook to support:
- Add voteCounts to ProposalData object
- Only show the ProposalExecute component when the proposal is queued
- Update voteCounts and votePercentages as new vote cast events are emitted
- Update proposal state from pending to active when the proposal start block passes

Add proposal listeners

---

src/components/DAOs/DAO/index.tsx

closes #182 
Adds a useEffect to fire when networkId is changed. reloading component and running address validating again. This would cause the user to be navigating back to "/" with toast error of "fractal doesn't exists"

Handle Network Change on DAO Route

---

.github/workflows/release-ipfs-dev.yaml

Closes #121 
if you have an IPFS node running (i do on my macbook, easy as brew install ipfs)
and the IPFS chrome extension installed
then simply going to app.dev.fractalframework.xyz will redirect you to app.dev.fractalframework.xyz.ipns.localhost:8080
which hosts the site directly from your local IPFS node
the way that works is:
- i created a github action
- that is triggered whenever a build happens
- what it does is
- build the app
- upload the build folder to pinata.cloud
- pin the files
- get the resulting IPFS hash
- update a DNS TXT record (_dnslink.app.dev.fractalframework.xyz) with the appropriate value (dnslink=/ipfs/<hash>)
- the existence of that record is what allows the IPFS browser extension to redirect to your local IPFS node and serve locally

Add IPFS dev workflow

---

package.json
public/index.html

In app start/build scripts, use git to capture the current git hash.
Put that git hash in an environment variable.
Stick that environment variable in a `meta` tag in the `head`.

Publish git hash

---

src/components/Proposals/CastVote.tsx
src/components/Proposals/ProposalCardDetailed.tsx
src/components/Proposals/ProposalDetails.tsx
src/components/Proposals/ProposalVotes.tsx

closes #225 
Based off #251 
Cleans up margin so DAO Summary and Proposal screen containers match

removes extra margin

---

src/components/Proposals/CastVote.tsx
src/components/Proposals/ProposalCard.tsx
src/components/Proposals/ProposalCardDetailed.tsx
src/components/Proposals/ProposalExecute.tsx
src/components/Proposals/ProposalQueue.tsx
src/components/ui/StatusBox.tsx
src/contexts/daoData/useProposals.ts
src/hooks/useProposalStateString.ts

Closes #249 
- Creates an enum type called `ProposalState` with the 8 states a proposal might be in.
- Updates the type of `state` in `ProposalData` from a `number` to `ProposalState`.
- Creates a hook for taking a `ProposalState` input and returning a string representation.
- Updates all UI components to no longer use `stateString`, but instead to logical comparisons using `state`, and visual display of state using the new hook.
- Removes `stateString` from `ProposalData`, instead exposing just `state`.
As always, the commits, when viewed in order, tell a story of the changes.

Proposal state enum

---

src/components/ui/Header/index.tsx

Closes #290
When anywhere in a DAO, the logo in header will go back to the DAO's home page.
When not loaded in a DAO, the logo will go back to the actual webapp's home page.

290 Remove the link to the webapp "homepage" in the Fractal logo

---

src/contexts/web3Data/transactions.ts
src/hooks/useCastVote.ts
src/hooks/useCreateProposal.ts
src/hooks/useDeployDAO.ts
src/hooks/useExecuteTransaction.ts
src/hooks/useQueueTransaction.ts

This was getting in the way of toast errors being displayed to the user.
We should be striving to never even allow users to attempt to make transactions that will fail. We can do that with smart logic (looking at on-chain data and comparing it with who the user is and what they're about to do) to enable/disable buttons that trigger transaction.
Seems like the primary use case for this functionality was to inform users of business logic (ur not the owner, can't do this), but again, that shouldn't be caught at the time of making a transaction, it should be caught before then.

Remove the rpc error callback from useTransaction hook

---

src/contexts/daoData/useProposals.ts

There were some prettier warnings 
I think there is one more step with `eslint/prettier`. We may need to make sure that the IDEs are displaying the errors/warnings correctly (IDE might not be setup to look for the `eslint`. 
The other question this poses, should this throw an error? instead of showing up as an error?

fixed prettier warnings

---

.eslintrc.json

Was working in another part of app and realized that `useEffect()` wasn't showing any warning or errors. This adds the linting rules for react-hooks.

adds react-hooks rules

---

src/contexts/web3Data/transactions.ts

Closes #306 
Adds a 2 second delay after transaction is mined, before reporting back to the business logic layer that that the transaction is no longer pending.

Pause for 2 seconds before informing app that Transaction is completed

---

package-lock.json
package.json
src/App.tsx
src/index.tsx

In `Draft` status until #332 is merged, since this PR builds on that one.
---
Implementing the Favorites PR (#332) made me realize that I should be using Local Storage for arbitrary local storage, not cookies.
So, this PR replaces the "not audited" acceptance state management from being cookie-based to LocalStorage-based.

Remove cookies

---

src/contexts/web3Data/README.md

adds a README to be a quick glance guide to the navigate and use Web3Provider

adds README for web3 provider

---

src/contexts/web3Data/Web3Provider.tsx

Updated Web3Provider to connect to defaultProvider (fallback or local) on load when no cacheProvider. A missing update from last PR when adding a loading state

connects to default provider on load

---

src/components/Dao/Delegate.tsx
src/components/Dao/Details.tsx
src/components/Proposals/ProposalDetails.tsx
src/components/Proposals/ProposalsList.tsx
src/contexts/blockchainData/blockchainData.ts
src/contexts/blockchainData/useMetaFactoryContract.ts
src/contexts/daoData/daoData.ts
src/contexts/daoData/useGovernorModuleContract.ts
src/hooks/useCastVote.ts
src/hooks/useCreateProposal.ts
src/hooks/useDelegateVote.ts
src/hooks/useDeployDAO.ts
src/hooks/useExecuteTransaction.ts
src/hooks/useQueueTransaction.ts
src/pages/Treasury/index.tsx

- Add some more structure to the `daoData`, made it less flat, to break the "governor" and "treasury" module data into their own sections.
- Use the global instance of the Governor contract throughout components, instead of always creating new instances of it whenever a transaction was being made to it.
- Add a global MetaFactory contract instance to the global `useBlockchainData` return object (didn't put in `daoData` cause it's not part of a DAO).

daoData module structure

---

src/components/ui/CopyToClipboard.tsx
src/components/ui/EtherscanLink.tsx
src/components/ui/Header/HeaderMenu.tsx
src/components/ui/Header/MenuItems.tsx
src/contexts/daoData/useProposals.ts
src/contexts/web3Data/Web3Provider.tsx
src/contexts/web3Data/types.ts
src/hooks/useAvatar.ts

@adamgall 
I think there are a few instances that does it fact take `undefined` from elsewhere in the app. But I think it's safe to update those types to include null as well so `string | undefined | null`.

redefines provider states as null

---

src/components/Dao/Details.tsx
src/contexts/daoData/daoData.ts
src/contexts/daoData/treasury/useTreasuryModuleContract.ts
src/contexts/daoData/useGovernorModuleContract.ts
src/contexts/daoData/useTimelockModuleContract.ts
src/hooks/use165Contracts.ts
src/hooks/useIsDAO.ts
src/hooks/useSupportsInterfaces.ts
src/types/contractMatch.ts

Build in support to "look for" the Treasury, Governor, and Timelock modules dynamically at runtime, instead of hardcoding their "index" in the `moduleAddresses` array.

Find modules

---

src/components/ui/Header/MenuItems.tsx

Noticed that the copy icon was showing up when account wasn't connected. added a conditional to prevent rendering

prevent component from rendering when not connected

---

src/hooks/useCreateDAODataCreator.ts

When Executing the create a SubDAO plugin, As the data is being prepared to be submitted it was pushing to `tokenAllocations`. Because of `currentBlockNumber` rerendering down the tree from the `useBlockChainDatas()` This push was causing the state to update in the form, which would sometimes cause an error when trying to submit the proposal, without a clear error.
Cloning the array and then pushing to that when executing prevents state from being updated.

414 Parent Token Allocation updating during execution

---

src/components/Dao/Delegate.tsx

Fixes bug where Delegate Input error state would not reset.
Saw an opportunity to clean up this file a little with replacing `useState` + `useEffect` with `useMemo`. I looked up to confirm what I was thinking that this way would be more performant. https://stackoverflow.com/questions/56028913/usememo-vs-useeffect-usestate
closes #412

412 delegate error state reset

---

src/components/DaoCreator/ChooseGovernance.tsx
src/components/DaoCreator/DisplayStepController.tsx
src/components/DaoCreator/provider/CreatorProvider.tsx
src/components/DaoCreator/provider/constants/index.ts
src/components/DaoCreator/provider/types/index.ts
src/components/ui/forms/Radio/RadioWithText.tsx

First part of adding support for creating a DAO with Gnosis Safe Governance. 
- Creates UI components for Choosing Governance
- Updates Creator Provider to store this information in state and dispatch to update it.
- Current this 'step' isn't included in the flow, so on the deploy site you will not be able to see it. If you want to view this page as it is. Pull down locally and change the `step` in `CreatorProvider` on line 23 to `CHOOSE_GOVERNANCE`. 
- The next PR will add this into the flow up to Deployment.

Choose Governance DAO Creation Components

---

src/helpers/crypto.ts

Original implementation produced "random 32 byte output" that looked like this (5 runs):
```
0x3136353030313932343636373834353935303438000000000000000000000000
0x3938383230373432363135353534383534353300000000000000000000000000
0x3432303730363134303735363932333532343800000000000000000000000000
0x3532323331373830313138333530313833393000000000000000000000000000
0x3234303332313132303933383834373131313700000000000000000000000000
```
New implementation produces "random 32 byte output" that looks like this (5 runs):
```
0x1ccff0d6a7c692aa72a689b1f96a61050ae19b7586955e052dc972d2d093be3d
0x91210c5d5bd957f42921873404db8dee4881766e5cd75cab144662641c519257
0x8045bd6b9a2122f629cfe28e2861eb79518efeaa84a491257fbf91d6ece31dba
0x05210e7ddc801216f37d2cf5783a5f6d56436e4e35758be7c590ca0c9ca3cb25 …
```

Update random byte generation code to be way more random

---

src/hooks/useCreateDAODataCreator.ts

Thankfully this bug was not caused by any math error, rather it caused by the update that changed from using the `tokenAllocation` prop. The prediction was mapping the original prop array and not the updated array with the additional allocations

BugFIx Token Supply/Amount Error

---

src/components/DaoCreator/tokenVotingGovernance/TokenAllocations.tsx

Convert `parentAllocationAmount` in `TokenAllocations` component to `BigNumber` while handling change
Issue appeared after merging #443

Fix SubDAO creation

---

src/components/DaoCreator/provider/hooks/useNextDisabled.ts

Problem: Next button disable state remains when navigating back to `Choose Governance`. Update switch statement for case for this step.

adds case for choose governance step

---

src/controller/Modules/TokenGovernanceInjector.tsx

PR changes one file - TokenGovernanceInjector.
The intent of this PR is to provide the user with the ability to propose a gnosis / token voting sub DAO. This is accomplished by utilising cases to determine if the proposal should include the gnosis or token voting encoded data.
Things to note: The 1:1 token voting does not work due to a small bug which has been addressed in #453 - the bug will be fixed during the merge.
To test this PR - please try to create a gnosis Safe subdao

Deploy a Gnosis Safe SubDAO with Token Voting Parent DAO

---

src/components/Dao/Delegate.tsx
src/components/DaoCreator/tokenVotingGovernance/TokenAllocationInput.tsx
src/components/ui/forms/Button.tsx
src/pages/Transactions/Plugins.tsx

- Refactor `Button` component. Because of components created within `Button` component directly - it was causing re-rendering of whole `Button` component for each render. See [blog post](https://levelup.gitconnected.com/code-review-avoid-declaring-react-component-inside-parent-component-1768a645f523) and [another one](https://dev.to/borasvm/react-create-component-inside-a-component-456b)
- Fix alignment for components in `TokenAllocationInput`
- Fix alignment for button on delegate page
Before: <img width="764" alt="Знімок екрана 2022-08-29 о 19 37 01" src="https://user-images.githubusercontent.com/25801162/187251919-e66df984-11bb-4603-9e97-36f3f9a28c00.png">
After: 
Closes #423

Buttons off alignment

---

src/controller/Modules/GovernanceController.tsx
src/controller/Modules/injectors/GnosisGovernanceInjector.tsx
src/controller/Modules/injectors/GovernanceInjectorConext.tsx
src/controller/Modules/injectors/TokenGovernanceInjector.tsx
src/pages/Transactions/Fractalize/index.tsx
src/pages/Transactions/Plugins.tsx

The objective of this PR is to prepare for removing subsidiary funding dependency on the treasury module hook. The first step here is to change the injector to return a context provider component. This will allow for the children of the injector to use the injector hook `useInjector` to access these props
n/a
Issue will be attached to next PR
There is really no visual or feature change with this PR. As long as there isn't any weird errors when the Transaction page loads it  should be good to go.
- Transactions Page still loads correctly
- (Extra) tested that plugin still works as expected.
n/a

replaces react.closeElement with context provider

---

src/components/Dao/Dashboard.tsx
src/components/ui/EtherscanTransactionLink.tsx
src/controller/Modules/TreasuryController.tsx
src/controller/Modules/injectors/GnosisTreasuryInjector.tsx
src/controller/Modules/injectors/TreasuryInjector.tsx
src/pages/Dao/index.tsx
src/providers/gnosis/hooks/useGnosisEvents.ts
src/providers/treasury/types/index.ts

As part of Activity Feed implementation - this PR scoped to enhancing `TreasuryController` and showing list of transaction events.
Next PR supposed to make same for Gnosis Safe Treasury-based DAO, so while making code review - mind that this PR is focusing "1:1" Treasury, but also enhances general boilerplate
Closes #486 
1. Visit DAO dashboard page that has 1:1 Token Governance (therefore "classic" Treasury) - example link http://localhost:3000/#/daos/0x68dB43B90E6284019c0513168b514d103F4e1092/dashboard
2. Observe transactions appearing there
3. Optional, if the DAO don't have much transactions in history - try to send tokens / NFTs / native token to the DAO, try to withdraw funds from there (not sure there's a way for that currently though 🤷🏼 )

Implement showing transaction events for classic Treasury

---

.eslintignore
.gitignore
package-lock.json
package.json
page-objects/components/HomePage.ts
playwright.config.ts
tests/ConfirmWalletConnect.spec.ts
tests/NavigateToFractal.spec.ts
tsconfig.json

Playwright has been installed in this PR with 2 tests. 
One test confirms navigation to the Fractal app via http://localhost:3000. 
The second test navigates to http://localhost:3000, confirms local wallet is present, and connects to the wallet. 
A GitHub Actions yml has not been included as of yet.
The user will need to run a local version of hardhat(_blockchain node_), start the fractal-interface app, then run the playwright tests. 
1. Clone repo
2. Open a terminal(A)
3. Install dependencies: `npm i` `npx playwright install`  
4. Add a `.env.local` file to the root of the project with the following information:
_Comment these out when not trying to run these tests_
```
REACT_APP_LOCAL_CHAIN_ID="31337"
REACT_APP_LOCAL_PROVIDER_URL="http://127.0.0.1:8545"
```
5. Open another terminal(B) …

Playwright config and Wallet Connection Test

---

package-lock.json
package.json

Slight updates to the Playwright config setup including:
- adding `playwright` as a dev dependency, which makes it so that we don't have to separately do `npx playwright install` after `npm install` to get the correct browsers installed.
- updates the run script to target both chromium and firefox, and doesn't explicitly say to use the default config file (it just uses it by default)
n/a
n/a
n/a
n/a

Playwright setup cleanup

---

src/App.tsx
src/components/menus/AccountDisplay/MenuItemButton.tsx
src/components/menus/AccountDisplay/MenuItemNetwork.tsx
src/components/menus/AccountDisplay/MenuItemWallet.tsx
src/components/menus/AccountDisplay/MenuItems.tsx

Quick bug fix. Noticed that the menu was being rendered behind some content on the page. Added 'sticky' zIndex. which is a chakra-ui key for 1100.
I also went ahead and updated the styling of the wallet menu. noticed the width and padding was quite off as I was creating a screenshot for the quick fix.

V1 Design | Header Depth and Wallet Menu

---

src/pages/Home/index.tsx
src/pages/Proposals/index.tsx
src/routes/DAORoutes.tsx
src/routes/FractalRoutes.tsx
src/routes/constants/base.ts
src/routes/constants/dao.ts
tests/home/visit.spec.ts
tests/models/DAOCreate.ts
tests/models/DAOHome.ts

Broken APP!! Changes that were made to the routes smashed together causing a bug that would cause 'daos' to be passed to as the address param instead. I've went in and updated the routes and nested them properly. 
Using a method of your choosing navigate to a DAO. should load correctly.
Navigate to sub pages (Governance is only one available at the moment) and make it sure they as well.

Bug | DAO not loading

---

package-lock.json
package.json
src/components/Proposals/ProposalVotes.tsx
src/pages/ProposalDetails/index.tsx
src/utils/numberFormats.ts
src/utils/percentFormat.spec.ts

Precision percentages using BigNumbers.
The issue is that BigNumbers are integers, so division using them will always lose precision, e.g. 1/2 = 0.
This PR uses the bigDecimal library to handle dividing BigNumbers, as well as adjusts the percent formatter method to take string, number, or BigDecimal.
I used @mudrila 's test DAO at http://localhost:3000/#/daos/0xeA4b1Ba101ed338BC72a35990a6c962c852Bc075/proposals/0 to view the changes

precision percentages with BigNumbers

---

src/components/ui/Sidebar/index.tsx
src/i18n/locales/en/sidebar.json
src/pages/Treasury/hooks/useFormatCoins.tsx

Fixes a bug where a line for Eth appears in the treasury when there is zero balance.
This is because the Eth asset is returned from the Gnosis API regardless of a zero amount.
Closes https://github.com/decent-dao/fractal-interface/issues/679
Create a new DAO and navigate to the treasury.
There should be no line item for $0 Eth in the treasury assets.

Treasury bug

---

src/hooks/DAO/useBuildDAOTx.ts

This PR fixes a bug by updating the logic within `useBuildDAOTx` to correctly predict the token contract address.
1) Create a new Usul DAO
2) Browse to the proposals, then delegate page
3) Ensure the token data is populated and that it updates with a new delegation

Fix predicted token address

---

src/components/Proposals/ProposalsList.tsx
src/components/ui/menus/OptionMenu.tsx
src/i18n/locales/en/proposal.json

Fixes two issues with the proposals filter:
1. Having zero filters selected still says "All Proposals"
2. No right margin between the checkbox and text
Before
After

Proposals filtering fixes

---

src/hooks/utils/useUpdateTimer.tsx
src/providers/Fractal/hooks/useGnosisApiServices.ts

Adds polling hook that will continuing call an async method to retrieve Safe information every 20s
Navigate to a DAO. (Dashboard). and send the safe some eth from wallet. after a while your event should appear

Enhancement | Polling safe data

---

src/hooks/DAO/useDAOController.ts
src/providers/Fractal/FractalProvider.tsx
src/providers/Fractal/reducers/gnosis.ts
src/routes/FractalRoutes.tsx

Added a useEffect to clear state when not within DAO.
- I tried a few different approaches here. I would prefer to have `DAOController` make this update, but because of how React Route is works. params of nested routes won't be recongnized by parent. So moving `useDAOController` isn't really an option and doesn't work. 
- There isn't any real way (and you shouldn't) update state on unMount.
- I believe I had a version of this before and had deleted it as it was causing some issues with loading. This version using routeMatch to check if state should be reset. instead of data from state.
Closes #793
Go to all the different routes and back home again. make sure state is changing correctly

BugFix | Clean DAO data when not viewing DAO

---

src/components/Proposals/MultisigProposalDetails/TxActions.tsx
src/components/ui/cards/DAOInfoCard.tsx
src/hooks/DAO/proposal/useExecuteProposal.ts
src/hooks/DAO/proposal/useSubmitProposal.ts
src/hooks/DAO/useCreateSubDAOProposal.ts
src/i18n/index.ts
src/i18n/locales/en/daoCreate.json
src/i18n/locales/en/proposalMetadata.json
src/i18n/locales/uk/daoCreate.json
src/pages/SubDaoCreate/index.tsx
src/providers/Fractal/FractalProvider.tsx
src/providers/Fractal/hooks/useGnosisApiServices.ts
src/providers/Fractal/types/state.ts

Going off the pattern I started to setup in #888, I've added a `refresh` method to the actions object in Fractal Provider. To start I've only included Transactions and SafeInfo as these retreive the info we need right now (to save on requests). When call these function don't return anything but update state. 
One other note. Since we don't really know what information we are trying to refresh when a proposal is executed. This isn't always going to catch the new DAO on the initial refresh. This PR also takes care of adding the SafeInfo into the interval as well. So child DAO will appear after some time.
I've also updated the copy based on the request in the card.
Closes #884

Bugfix | Proposal Execution Refresh

---

src/hooks/utils/useSubDomain.tsx

Noticed that I wasn't able to use the transaction hash link to etherscan properly. a conditional just needed to be flipped.

BugFix | Etherscan URL not linked correctly

---

src/i18n/locales/en/daoCreate.json
src/i18n/locales/en/proposal.json
src/i18n/locales/uk/daoCreate.json
src/i18n/locales/uk/proposal.json

internally these are termed different things depending on the governance details, but user facing we're just calling both time periods the Queue period.
This is just cleaning up two instances where we didn't change this.

change references to Timelock to Queue

---

src/components/ui/proposal/ProposalExecutableCode.tsx
src/i18n/locales/en/proposal.json
src/pages/ProposalCreate/index.tsx
src/pages/ProposalDetails/index.tsx
src/types/transaction.ts
src/utils/crypto.ts

This PR fixes set of bugs:
1. Whole "< Proposals" button area is clickable, and not just button content
2. Showing informational message that transaction's data decoding failed
3. Marking "Cancel" button as disabled during proposal creation
N/A
Closes #876 
Closes #921 
Closes #917 
Testing #876 
1. Create Proposal with broken data (you can put method that does not exist on target contract - that's sufficient enough)
2. Open proposal's executable code
3. There should be info message saying that it was unable to decode transaction data **for each transaction that was failed to decode**.
Note - this works only for Usul, as for Multisig we're not showing executable code if Gnosis API does not return decoded data. Since we're not decoding data through separate request - there's no sensible …

Handle decoding error for proposal executable code

---

src/constants/url.ts
src/i18n/locales/en/proposalMetadata.json
tests/home/visit.spec.ts

The Discord invite link fails if we run out of Discord server boosts, which has happened at least 2 times that I've noticed..
This switched to a permanent, non vanity link instead.

switch to permanent discord invite link

---

.github/workflows/release-ipfs-dev.yaml
.github/workflows/release-ipfs-prod.yaml

Both custom dependencies set up by @adamgall have been moved to the Decent repo:
https://github.com/decent-dao/ipfs-pinata-deploy-action
https://github.com/decent-dao/convert-cidv0-cidv1
Along with this update, we've also updated the Github secrets to a new account based on mike.herbig@decentlabs.io, which is also upgraded to the $20/month plan:
```
PINATA_API_KEY
PINATA_API_SECRET_KEY
PINATA_PIN_NAME (dev)
PINATA_PIN_NAME (prod)
```
I think we need to merge this in to see if the IPFS build works?
I will test with the IPFS browser plugin to make sure it has properly been uploaded and pinned in IPFS.

migrate IPFS dependencies into the Decent repo

---

src/providers/Fractal/governance/hooks/useUsulProposals.ts

Saw an opportunity to 'cache' some requests. When loading several Usul Token Proposals, For each tx, a request is sent to 'decode' the transaction. This happens on every interval. This data is only saved to a mapping within the `useUsulProposals` itself will help save costs per session.
This is only a quick bandaid, as we work towards a look at the data-layer of the app. On load I noticed that the proposals are loaded (the function is called) 3 times, and then on every the interval, noting for later.

Caching | Caches decoded transaction data

---

src/hooks/DAO/useDAOName.ts
src/hooks/utils/useDisplayName.ts
src/providers/Fractal/hooks/account/useLocalStorage.ts

Cache requests to look up ENS names, as well as our own DAO name contract.
We could refactor ENS resolving to use `useEnsResolver`, similar to what we're doing with `useEnsName` and get their built in caching, but I decided to leave as is for now.

Cache ENS and DAO name lookups

---

src/helpers/crypto.ts
src/hooks/DAO/useDAOName.ts
src/providers/Fractal/FractalProvider.tsx
src/providers/Fractal/governance/hooks/useGnosisGovernance.ts
src/providers/Fractal/governance/hooks/useUsulProposals.ts
src/providers/Fractal/governance/hooks/useVotingContracts.ts
src/providers/Fractal/hooks/useGnosisModuleTypes.ts
src/providers/Fractal/hooks/useVetoContracts.ts
src/providers/Fractal/utils/usul.ts
src/providers/NetworkConfig/NetworkConfigProvider.tsx

I took what was done in https://github.com/decent-dao/fractal-interface/pull/999 and put those calls into a method that delineates the calls depending on which network you're on.
This way we can bring back polygon, but not rely on the provider for other networks.

make polygon specific provider / signer calls dynamic to the network

---

src/components/Proposals/UsulDetails/index.tsx
src/components/ui/proposal/ProposalTime.tsx
src/providers/Fractal/governance/hooks/useGovernanceTokenData.ts

LFG. This PR makes 3 changes
- removes duplicate use of `useTokenData` hook. replaces with data that is already loaded in state
- removes unneeded dependencies in `useTokenData` useEffects
- adds local caching to `useTokenData` hook
- This reduces `eth_call` requests by 60-80%!!
- To see the `eth_call` requests you can add the following above in Fractal Provider
```ts
useEffect(() => {
const listener = (ev: any) => {
if (ev.data.data?.data?.method === 'eth_call') {
console.count('ETH_CALL COUNT');
}
};
window.addEventListener('message', listener);
return () => {
window.removeEventListener('message', listener);
};
}, []);
```

Bugfix rpc requests reduction

---

src/components/ui/cards/DAOInfoCard.tsx

Quick fix. Probably from the Mobile refactor? but the `InfoNodeCard` on Node pages had spacing issues with the menu elipsis hugging the DAO name.
One line fix

Bugfix | node page menu ellipsis spacing

---

src/pages/ProposalCreate/index.tsx

I had noticed that when navigating to Create Proposal on Usul DAOs. The Transaction form would flicker before the meta data form shows up. I updated the check slightly to just use the governance type versus the contract. as well as added a BarLoader that shows when type hasn't been set yet

removes rendering proposals when metadata

---

src/pages/Home/index.tsx

A requirement of applying for a Netlify open source account is to have an attribution to them on your app.
This adds a simple attribution, in order to apply.
We can discuss with @xraystyle1980 later on a better way to attribute Netlify, but I wanted to get this in now to put in the application.

Temporary Netlify attribution

---

src/components/Proposals/ProposalActions/Execute.tsx
src/components/Proposals/ProposalActions/ProposalAction.tsx
src/components/Proposals/ProposalActions/Queue.tsx
src/components/Proposals/ProposalActions/Vote.tsx
src/components/pages/DAOTreasury/hooks/useSendAssets.ts
src/components/ui/proposal/ProposalTime.tsx
src/hooks/DAO/proposal/useQueueProposal.ts
src/hooks/DAO/proposal/useUpdateProposalState.ts

This PR addresses some of the timer-related issues in our proposal system, focusing on providing better feedback to the user about the current proposal state
There are two remaining periods where either we could improve our timer's accuracy or add some kinda of indiction of 'why' its not ready yet.
- Period after voting period ends for roughly 1-2 block time before voting period ends
- Period after queuing where execution is unavailable for some time. 
This new setup will call `updateTxState` when the timer goes negative on a set interval. I currently have this set at 10 seconds, a little less than 1 block. 
This PR also adds 'days' to timer. pending response in chat
Closes #1051 
Closes #1045

Refactor BugFix | Proposal Time refactor

---

src/helpers/errorLogging.ts
src/utils/dev.ts

Prevents even initializing or calling any Sentry related functions on production builds.

Don't init Sentry on prod

---

src/components/DaoCreator/formComponents/AzoriusTokenAllocation.tsx
src/components/DaoCreator/formComponents/GnosisMultisig.tsx
src/components/pages/ManageSigners/AddSignerModal.tsx
src/components/ui/forms/EthAddressInput.tsx
src/components/ui/modals/DelegateModal.tsx

Fixes 1password appearing in address inputs by providing a new "AddressInput" Input extension.
closes https://github.com/decent-dao/fractal-interface/issues/1116
Please check the token allocation modal to ensure the input still works correctly.

fix 1password appearing in address inputs

---

src/components/ui/forms/BigNumberInput.tsx
src/components/ui/modals/SendAssetsModal.tsx
src/components/ui/modals/UnwrapToken.tsx
src/components/ui/modals/WrapToken.tsx
src/i18n/locales/en/common.json

This PR adds a "Max" button to the `BigNumberInput` component used in the `WrapToken`, `UnwrapToken`, and `Send Assets` modals. The button appears only when the `maxValue` prop is passed to the component. When clicked, the input value is set to the user's balance or the provided maximum value.
- Added a `maxValue` prop to the `BigNumberInput` component to control the display of the "Max" button and set the maximum value for the input.
- Updated the `WrapToken`, `UnwrapToken`, and `Send Assets` modals to pass the user's balance or the maximum value to the `BigNumberInput` component.
Fixes #1122
1. Navigate to the `WrapToken`, `UnwrapToken`, and `Send Assets` modals.
2. Ensure the "Max" button appears when the `maxValue` prop is passed to the `BigNumberInput` component.
3. Click the "Max" …

Add |  Max button on inputs

---

src/components/DaoCreator/formComponents/GnosisMultisig.tsx
src/hooks/schemas/DAOCreate/useDAOCreateSchema.ts
src/types/createDAO.ts

This PR updates the `GnosisMultisig` React component and the `useDAOCreateSchema` hook to simplify the process of updating and modifying the number of signers. The changes allow for easier removal and alteration of the number of signers by handling edge cases and streamlining the logic in the `handleSignersChanges` function.
- Refactored the `handleSignersChanges` function to make it more readable and maintainable
- Added helper functions to further simplify the code and handle edge cases
- Updated the `useDAOCreateSchema` hook to accommodate the new changes
Fixes #1111
1. Ensure all existing tests pass and that the component still functions as expected
2. Test adding, removing, and modifying the number of signers to ensure the new logic works correctly

BugFix | updates number of signers input for better UX

---

src/components/ui/forms/BigNumberInput.tsx
src/components/ui/modals/SendAssetsModal.tsx

This PR updates the `SendAssetModal` to clear asset amount input when asset is changed.

Bugfix | Clear send asset amount input

---

app/daos/[daoAddress]/hierarchy/page.tsx
src/components/pages/DaoHierarchy/DaoNode.tsx
src/components/pages/DaoHierarchy/NodeLines.tsx
src/components/pages/DaoSettings/components/Signers/index.tsx
src/components/ui/cards/DAOInfoCard.tsx
src/components/ui/cards/DAONodeRow.tsx
src/components/ui/forms/Radio/RadioWithText.tsx
src/components/ui/loaders/BarLoader.tsx
src/components/ui/page/Header/index.tsx

Fixes the issue with DAO node lines extending below the last node row:
https://deploy-preview-1241--fractal-framework-interface-dev.netlify.app/daos/0x36C19472D4CA942710cA9aF01a03cED4dBc6eC0a/hierarchy

Fix DAO node lines

---

src/components/pages/DAOTreasury/components/Assets.tsx

calculating a percentage with a zero denominator caused a divide by zero exception, this fixes that
checked other usages of `formatPercentage` and saw no other potential issues, also decided the fix should be outside `formatPercentage`, since not throwing the exception would mask future bugs

fix divide by zero in treasury

---

src/hooks/DAO/loaders/governance/useLockRelease.ts

The `LockRelease` contract has been cleaned up a bit, and two public functions have been removed. One of those functions was being used in this `fractal-interface` codebase, which necessitates and update here with some functionally equivalent code.
The `getPending` function is the one which was removed from `LockRelease`, and being used here. The old implementation of `getPending` in the contract simply subtracted one public number from another public number. So, that's what I've done in this PR: fetch both of those numbers then do the subtraction client side.
The other removed function, `getBeneficiaries`, I don't see being used in this `fractal-interface` codebase.
Here's the commit that introduced this change in the `DCNT` repo: …

Removed `getPending` from `LockRelease` contract

---

app/daos/[daoAddress]/treasury/page.tsx
src/components/Proposals/ProposalSummary.tsx
src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/components/ui/modals/DelegateModal.tsx
src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts

See linked issues
Closes #1299 
Closes #1300 
Closes #1201 
Closes #1301 
Closes #1302 
Closes #1303
Closes #1304

QA bug fixes

---

app/layout.tsx
src/providers/Providers.tsx

move providers out of App directory

---

src/components/pages/DaoHierarchy/DaoNode.tsx

Fixed continuous re-rendering issue on Hierarchy Page
This patch addresses a performance issue on the Hierarchy Page observed while navigating between DAOs. A persistent error was logged in the console, and the performance monitor in the development tools never stabilized. Additionally, navigating to a new DAO from this page was hindered due to this problem.
The issue was traced back to a `useEffect` hook that was continuously re-executing after component mounting, causing unnecessary re-renders. To resolve this, a `useRef` hook has been added to prevent the `useEffect` from re-executing, thus improving the page's performance and navigation stability.
I separated this fix from #1373 so that it can be merged separately, But this should be merged first.

Fix Multiple Re-render caused by `useEffect`

---

app/daos/[daoAddress]/proposals/new/page.tsx
src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
src/hooks/DAO/loaders/useFractalGuardContracts.ts
src/hooks/DAO/loaders/useFractalModules.ts
src/hooks/DAO/loaders/useGovernanceContracts.ts
src/hooks/DAO/proposal/useSubmitProposal.ts
src/hooks/DAO/proposal/useUserERC721VotingTokens.ts
src/hooks/DAO/useDeployAzorius.ts
src/hooks/utils/cache/cacheDefaults.ts
src/utils/azorius.ts

This PR strives to remove some of the loading errors from the 429 request error seen in the app. 
First I saw an opportunity to save on the strain of Event filtering by replacing the queryFilter for `EnabledStrategies()` with  just a call on the contract `getStrategies()` to retrieve the voting contract address (as its labeled in the code). 
The second part of the fix is to be considered a bandaid. After discussing with @adamgall There is a better and more efficient pattern for retrieving the master copy instead of relying on the event `queryFilter`. This will be detailed later in a card in `Fractal Maintenance` Project Board. 
For now I'm using the `useLocalStoage` hook that we have in place to store `master_copy_of`. to save `proxyAddress: masterCopyAddress`. So once requested and found …

Voting Strategies Upgrade + Master Copy Caching

---

src/components/Proposals/MultisigProposalDetails/TxActions.tsx
src/hooks/DAO/proposal/useSubmitProposal.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/hooks/safe/useSafeContracts.ts
src/models/AzoriusTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/FreezeGuardTxBuilder.ts
src/models/MultisigTxBuilder.ts
src/models/TxBuilderFactory.ts
src/models/helpers/fractalModuleData.ts
src/models/helpers/safeData.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/contract.ts
src/types/fractal.ts
src/types/network.ts

This PR swaps all the `GnosisSafe` usages to `GnosisSafeL2` and adds `fallbackHandler` to the create Safe flow, right into `setup` function call.
Closes #1361 
1. Deploy brand new Safe via Fractal
2. Create new Safe via Safe UI, go to Safe's Settings page
3. Go to Safe UI and find Fractal-created Safe, go to Safe's Settings page
4. Compare Safe created via Fractal and Safe created via Safe UI - their version should be exactly the same (`1.3.0+L2`) and attached Fallback Handler (could be found under "Modules" tab) also should be exactly the same. See screenshots below for references on how it should look like

Align deployment of Safe to be of same version as Safe UI-deployed and having fallback handler attached

---

.env
src/providers/NetworkConfig/rainbow-kit.config.ts

To bring some consistency to the environment variable names.
I've already _added_ the new environment variable in Netlify, so this should work in the preview deployments and once merged.
After this code merges into `develop`, it'll be safe to delete `NEXT_PUBLIC_ALCHEMY_API_KEY` from the dev site in Netlify.
After this code merges into `main`, it'll be safe to delete `NEXT_PUBLIC_ALCHEMY_API_KEY` from the prod site in Netlify.
As a side note, I strongly encourage all engineers on the project (@Da-Colon, @mudrila) to set up their own free-tier accounts on Etherscan, Alchemy, Infura, and WalletConnect Cloud, and use those keys in their `.env.local` files.

Include a "MAINNET" identifier in the mainnet Alchemy env var

---

src/components/Proposals/ProposalActions/ProposalAction.tsx

Closes #1396 
The `ProposalAction` buttons, which show up in proposal list cards, no longer needs to be a link.
Testing:
On dev load up any DAO that has proposals. Notice that when the proposal list populates, there's an error in the console talking about how nested anchor tags are not allowed.
Then do the same on this branch, and notice how that error does not appear.
@mudrila I would love your eyes on this, specifically. There are three files where the `ProposalAction` component is instantiated:
- src/components/Activity/ActivityGovernance.tsx
- src/components/Proposals/AzoriusDetails/index.tsx
- src/components/Proposals/SnapshotProposalDetails/index.tsx
The first file, `ActivityGovernance.tsx` is the proposal card that shows up on the DAO Home and Proposals pages. That seems good.
But …

Fix Nested Anchor Tags

---

src/providers/App/hooks/usePriceAPI.ts

Closes #1434 
This won't be testable on the deploy-preview site. Pretty much just for devs.

Don't log or show Pricing API communication errors in development

---

src/hooks/DAO/loaders/governance/useERC20Claim.ts

Branched from #1486 
Multiple re-renders was causing this to run this request more than once. Added a conditional to only allow this to fire once. 
Closes #1456

[Maintenance] Investigate extra requests `useERC20Claim`

---

src/pages/daos/[daoAddress]/proposal-templates/new/index.tsx

While exploring the myosin DAO's template execution error is was discovered that the reason why the template would not execution was caused by an error in the template's creation. The json contains a typo in the `ethValue` property. newer templates doesn't have this typo. 
I did however notice that one more typo still exists though it doesn't seem to affect new templates.
Edit:
This was in fact effecting creation of forked templates.

Fix BigNumber Typo in templates

---

src/components/Activity/ActivityDescriptionGovernance.tsx
src/components/ui/menus/AccountDisplay/MenuButtonDisplay.tsx

Closes #1499 
See attached issue (#1499) for screenshots demonstrating the problem.

Make displayed avatars consistent for same addresses

---

src/components/pages/DaoHierarchy/useFetchNodes.tsx
src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
src/hooks/utils/useAsyncRetry.ts

The `useAsyncRetry` hook returns a function called `requestWithRetries`.
`requestWithRetries` takes a function as an input parameter, and then returns back `Promise<any>`. 
What is happening in `requestWithRetries` is that it calls that input function many times until the function succeeds, and then returns back the result of that function. So, it's kind of generic.
However, I think it would be better if there was stronger typing on `requestWithRetries`. Instead of returning back `Promise<any>`, it should return `Promise<T>`, where `T` is the return type of its input function.
This PR does that, then cleans up a couple of new linter errors from that improvement.

Add better typing to `useAsyncRetry`

---

package-lock.json
package.json
src/components/ui/proposal/Markdown.tsx
src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
src/hooks/DAO/loaders/governance/useAzoriusProposalListeners.ts
src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
src/hooks/DAO/loaders/governance/useERC721LinearStrategy.ts
src/hooks/DAO/loaders/useFractalNode.ts
src/hooks/DAO/loaders/useProposals.ts
src/hooks/DAO/proposal/useSubmitProposal.ts
src/hooks/DAO/useDAOController.ts
src/providers/App/governance/action.ts
src/providers/App/governance/reducer.ts
src/providers/NetworkConfig/web3-modal.config.ts
src/utils/azorius.ts

Closes #1509 
Closes #1457 
Closes #1464
- Loads Azorius proposals sequentially instead of all at once.
- No change to how Multisig or Snapshot proposals / transactions are loaded.
- Moved a handful of event listeners from various places (mostly `useAzoriusProposals`, but also `useERC20LinearStrategy` and `useERC721LinearStrategy`) into their own new top-level hook, `useAzoriusListeners`
- Optimized proposal object creation logic to no longer need to fetch `Voted` events or `ProposalExecuted` events for each proposal. Instead, fetch them all just once before processing each proposal. Because they're not indexed, we have to just get all of them anyway. So just pass them down into the proposal processing and filter the same static set per proposal.
- Plenty of other stuff, but I guess …

Load proposals sequentially

---

src/hooks/DAO/loaders/useFractalFreeze.ts

Closes #1508
This PR fixes a bug preventing the freeze button on a freeze proposal from updating itself when the connected wallet acount changes.
- Make sure to be on a parent DAO with more than one signer
- On a sub-DAO (also with more than one signer), initiate a freeze
- Change account to a signer on the DAO. The button should update itself in time, after which the user can execute their vote.
- The behaviour of a permutation of signers on the parent and child     DAOs where signers on the parent are not necessarily on the child and vice versa is untested
- The parent dao should have at least as many signers as the child dao requires to execute a proposal. If fewer, the freeze proposal can never get executed
- Even if the parent dao requires more than one signer, if the child dao …

Fix freeze button state bug

---

src/components/ui/modals/ForkProposalTemplateModal.tsx

All new query params should now be appended with `&`, because the `dao` param is first with `?` already
Closes #1526

Fix for appending `templateHash` query parameter

---

src/components/ui/page/Header/PageHeader.tsx
src/hooks/DAO/useDAOName.ts
src/hooks/utils/cache/cacheDefaults.ts

This PR removes the local storage of the DAO name. Since this data apparently exists on a subgraph, it's auto-updated (after some time).
There isn't much of a tradeoff in completely removing the DAO name cache. There was a split second where, in the breadcrumbs, the name would be empty while being fetched. I have replaced this with the DAO address substring, so it's less jarring.

Fix DAO name doesn't update after edit

---

src/components/Activity/ActivityDescription.tsx
src/components/Activity/ActivityDescriptionGovernance.tsx
src/components/Proposals/ProposalCard/ProposalCard.tsx
src/components/Proposals/index.tsx
src/components/ui/badges/Badge.tsx
src/components/ui/badges/QuorumBadge.tsx
src/components/ui/page/Header/Breadcrumbs.tsx
src/i18n/locales/en/breadcrumbs.json

Restyle proposals list

---

src/components/ProposalBuilder/ProposalMetadata.tsx

Artifact from previous PR work -- metadata screen lost its padding. Fixed.
before:
after:

Fix ProposalMetadata padding

---

src/components/Proposals/index.tsx
src/components/ui/menus/AccountDisplay/AccountMenuButton.tsx
src/components/ui/menus/AccountDisplay/ConnectedWalletMenuItem.tsx
src/components/ui/menus/AccountDisplay/MenuItemButton.tsx
src/components/ui/menus/AccountDisplay/NetworkSelector.tsx
src/components/ui/menus/AccountDisplay/WalletMenu.tsx
src/components/ui/menus/AccountDisplay/index.tsx
src/components/ui/menus/FavoritesMenu/Favorite.tsx
src/components/ui/menus/FavoritesMenu/FavoritesList.tsx
src/components/ui/menus/OptionMenu/OptionsList.tsx
src/components/ui/menus/OptionMenu/index.tsx
src/components/ui/page/Header/index.tsx
src/components/ui/utils/Sort.tsx
src/constants/common.ts
src/i18n/locales/en/common.json
src/i18n/locales/en/dashboard.json

This PR fixes a few minor UI inconsistencies on some menus around the app. Screenshots below.
First, the sort menu is more consistent with other menus from figma:
Manage safe menu:
Proposal filter menu
Wallet menu (removed some corner artifacts):

Reskin/menu UI

---

src/helpers/crypto.ts
src/hooks/utils/cache/cacheDefaults.ts
src/hooks/utils/useAddress.ts
src/types/daoProposal.ts

Closes #1631 
- Remove an unused type.
- Remove an unused cache key.
- Remove a function which returns if a given network supports ENS or not.
- Remove ENS name resolution caching.
See my review comments for more context.

Remove old stuff

---

src/hooks/DAO/loaders/useFractalNode.ts
src/hooks/DAO/loaders/useLoadDAONode.ts
src/utils/hierarchy.ts

Closes #1632 
The `mapChildNodes` function was typed with lots of `any`s, which I didn't like. Here is a fix for that.
Have tested loading up DAOs with and without children. Things work as expected.

Add proper typing to `mapChildNodes` function

---

src/components/ui/modals/UnwrapToken.tsx
src/components/ui/modals/WrapToken.tsx
src/hooks/utils/useApproval.tsx

Please review and merge https://github.com/decentdao/fractal-interface/pull/1641 first.
Update `useApproval` hook to take address instead of ethers contract object.

Remove ethers from useApproval

---

src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/AzoriusTxBuilder.ts
src/models/TxBuilderFactory.ts
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/baseSepolia.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/fractal.ts
src/types/network.ts
src/types/strategyAzorius.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1642 first.

Remove votesTokenMasterCopyContract from interfaces

---

src/helpers/crypto.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/AzoriusTxBuilder.ts
src/models/BaseTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/FreezeGuardTxBuilder.ts
src/models/TxBuilderFactory.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1644 first.

Remove VotesERC20 from AzoriusTxBuilder

---

src/assets/abi/KeyValuePairs.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/DaoTxBuilder.ts
src/models/TxBuilderFactory.ts
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/baseSepolia.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/contract.ts
src/types/network.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1645 first.

Remove key value pairs contract from base contracts

---

src/hooks/DAO/proposal/useCreateProposalTemplate.ts
src/hooks/DAO/proposal/useRemoveProposalTemplate.ts
src/hooks/safe/useSafeContracts.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1647 first.
Remove keyValuePairsContract from useSafeContracts and resolve downstream issues

Remove key value pairs contract from use safe contracts

---

src/assets/abi/FractalRegistry.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/DaoTxBuilder.ts
src/models/TxBuilderFactory.ts
src/types/contract.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1651 first.

Remove fractal registry contract from base contracts

---

src/components/pages/DaoSettings/components/Metadata/index.tsx
src/components/ui/menus/FavoritesMenu/Favorite.tsx
src/hooks/DAO/useCreateSubDAOProposal.ts
src/hooks/DAO/useDAOName.ts
src/hooks/utils/useMasterCopy.ts
src/types/fractal.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1652 first.
Remove fractalRegistryContract from FractalContracts interface and resolve all downstream issues

Remove fractal registry from fractal contracts

---

src/assets/abi/GnosisSafeProxyFactory.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/TxBuilderFactory.ts
src/models/helpers/safeData.ts
src/types/contract.ts
src/types/fractal.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1654 first.

Remove safe factory contract from fractal contracts and base contracts

---

src/hooks/safe/useSafeContracts.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1655 first.

Remove safeFactoryContract from useSafeContracts

---

src/hooks/safe/useSafeContracts.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1657 first.

Remove zodiacModuleProxyFactoryContract from useSafeContracts

---

src/components/pages/DaoSettings/components/Signers/hooks/useAddSigner.ts
src/components/pages/DaoSettings/components/Signers/hooks/useRemoveSigner.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/TxBuilderFactory.ts
src/models/helpers/safeData.ts
src/types/contract.ts
src/types/fractal.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1658 first.

Remove the safeSingletonContract property from FractalContracts and BaseContracts interfaces

---

src/components/Proposals/MultisigProposalDetails/TxActions.tsx
src/helpers/crypto.ts
src/hooks/DAO/proposal/useSubmitProposal.ts
src/models/AzoriusTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/FreezeGuardTxBuilder.ts
src/models/MultisigTxBuilder.ts
src/models/TxBuilderFactory.ts
src/models/helpers/fractalModuleData.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1661 first.

Remove gnosis safe l2 typechain

---

src/hooks/DAO/loaders/useFractalNode.ts
src/hooks/DAO/loaders/useLoadDAONode.ts

Fixes this inconsistent bugfix (least for me)
Let me know if this pops up for anyone else.

Bugfix graphql type

---

src/components/pages/DaoDashboard/Info/DaoInfoHeader.tsx
src/components/pages/DaoDashboard/Info/InfoGovernance.tsx
src/components/pages/DaoDashboard/Info/ParentLink.tsx

This PR contains following changes:
- Adjust `ParentLink` width to `fit-content` so that it's hover effect doesn't take whole row
- Slightly improve `InfoGovernance` - for long values `justify-content` wasn't working as expected and text was aligned to the left side - fix this
Closes #1714

`Reskin`- hover effect on parent link

---

src/components/ui/page/Layout/index.tsx
src/components/ui/page/Navigation/NavigationLinks.tsx

Add blur to Sidebar. 
Also per a quick conversation with @nicolaus-sherrill, I've updated the Header as well:
- Removed the backdropFilter (blur) from Parent Header
- added `box-shadow` 
- added `neutral-2` bg for Header
These changes allow for the menus to properly have the blur effect applied.
Closes #1730

`Reskin` 1730 add blur sidebar

---

src/components/Proposals/ProposalCard/ProposalCard.tsx
src/components/Proposals/ProposalInfo.tsx
src/components/ui/badges/Badge.tsx
src/components/ui/proposal/ProposalCountdown.tsx

Separate the `ProposalCountdown`  from the `Badge` component
Fixes #1695

`Reskin` Moves ProposalCountdown from the Badge component

---

src/components/pages/DAOTreasury/hooks/useFormatCoins.tsx
src/components/pages/DAOTreasury/hooks/useSendAssets.ts
src/components/ui/modals/SendAssetsModal.tsx
src/components/ui/modals/Stake.tsx
src/hooks/DAO/loaders/useFractalTreasury.ts
src/providers/App/hooks/usePriceAPI.ts
src/providers/App/hooks/useSafeAPI.ts
src/types/createDAO.ts
src/types/daoTreasury.ts
src/types/fractal.ts
src/utils/numberFormats.ts

Safe API just stopped supporting `getUsdBalances` 
However, they weren't returning fiat values there for a long time
So we just swapping out `getUsdBalances` to `getBalances`
Now showing coins works like a charm

Swap out `getUsdBalances` with `getBalances`

---

package-lock.json
package.json
src/components/pages/DAOTreasury/hooks/useSendAssets.ts

Fixes #1818 
Hot fix. Updates replaces  `encodeAbiParameters` with `EncodeFunctionData`

Update useSendAssets to use encodeFunctionData for ERC20 transfer

---

src/pages/home/HomePage.tsx
src/pages/home/MySafes.tsx

closes #1799 
This PR only moves the create home button and "my safes" header. 
Safe row card redesign happens in a different PR that @Da-Colon's cooking

New create safe button

---

src/assets/abi/LinearERC20Voting.ts
src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
src/hooks/DAO/loaders/governance/useERC20LinearStrategy.ts
src/hooks/DAO/loaders/useGovernanceContracts.ts
src/hooks/DAO/proposal/useCastVote.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/hooks/safe/useSafeContracts.ts
src/hooks/utils/useCanUserSubmitProposal.ts
src/hooks/utils/useMasterCopy.ts
src/models/AzoriusTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/TxBuilderFactory.ts
src/types/fractal.ts
src/types/strategyAzorius.ts
src/utils/azorius.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1666 first.

Remove linear erc20 voting

---

src/assets/abi/LinearERC721Voting.ts
src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
src/hooks/DAO/loaders/governance/useERC721LinearStrategy.ts
src/hooks/DAO/loaders/governance/useERC721Tokens.ts
src/hooks/DAO/proposal/useCastVote.ts
src/hooks/DAO/proposal/useUserERC721VotingTokens.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/hooks/safe/useSafeContracts.ts
src/hooks/utils/useCanUserSubmitProposal.ts
src/hooks/utils/useMasterCopy.ts
src/models/AzoriusTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/TxBuilderFactory.ts
src/types/fractal.ts
src/types/strategyAzorius.ts
src/utils/azorius.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1668 first.

Remove linear erc721 voting

---

src/hooks/DAO/loaders/useFractalGuardContracts.ts
src/hooks/DAO/loaders/useFractalModules.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useClawBack.ts
src/hooks/DAO/useDeployAzorius.ts
src/hooks/safe/useSafeContracts.ts
src/hooks/utils/useMasterCopy.ts
src/types/contract.ts
src/types/fractal.ts

Please review and merge https://github.com/decentdao/fractal-interface/pull/1669 first.

Remove FractalModule typechain imports from all files

---

src/components/Proposals/ProposalVotes/index.tsx
src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx

Fixes #1872
Found that `bigint` doesn't support decimals directly. If there is a better way to convert and get these values let me know

convert to number before performing operations to get percentage

---

src/i18n/locales/en/breadcrumbs.json
src/i18n/locales/en/common.json

On the renamed "Organization" page, we were still using the word "Hierarchy" in two places:
1. Main `H1` page title
2. Breadcrumb
This fixes that to use the word "Organization" as it should.
No issue, I just noticed it and decided to fix it right quick.

Finish renaming hierarchy

---

src/i18n/locales/en/home.json
src/pages/home/HomePage.tsx

Closes https://github.com/decentdao/decent-interface/issues/1880
Simply removes the docs link from the home page, as decided upon (see issue thread).

Remove docs link from home page

---

src/pages/home/AllSafesDrawer.tsx

Fixes #1924 
So there is some difference on how the `Menu` component is mounted/unmounted and the `Drawer` component. I'm not entirely sure why when the `Drawer` component is closed, it appears that component isn't getting unmounted and/or is getting cached, the `useAccountFavorites` hook never refreshes between opening and closing. As it works fine in the Menu on desktop.
After many attempts with `useEffect` a `reloadFavorites` function `onOpen`, ultimately the cleanest solution ended up being just replacing the use of `favoritesList` out of `useAccountFavorites` and get the list directly in the component.

`1924` Favorites Drawer reload

---

src/components/pages/DaoSettings/components/Signers/SignersContainer.tsx
src/components/pages/DaoSettings/components/Signers/modals/RemoveSignerModal.tsx

Fixes #1902 
- I move the modal opening `useFractalModal` into the `Signer` Component passing the needed props through. Because of how the modal consumes the address, I was able to use the current state setup in this way, so removed that. 
- I use `Button` component with a `Icon` inside as the size property. `icon-sm` and `icon-lg` for IconButton didn't fit with figma design of `20x20` for Icon.

`1902` Update Signers UX for Multisig

---

src/components/pages/DaoDashboard/Activities/hooks/useActivities.ts
src/components/pages/DaoDashboard/Info/InfoProposals.tsx
src/hooks/utils/useSafeTransactions.ts
src/i18n/locales/en/dashboard.json
src/types/fractal.ts

Closes https://github.com/decentdao/decent-interface/issues/1675
Renames the two properties in the Governance card on DAO Dashboard to be
- Total
- Active
This one was a lot of work to deal with all of the potential permutations of azorius/multisig and snapshot/nonsnapshot.
But I think I got it.
Displays both values as quickly as able to.
- Multisig proposals are loaded in all at once, so we know this total number pretty quickly.
- Azorius proposals are loaded in one at a time, but from newest to oldest, and the proposal ID is incremented by one each time, so we know the total number of proposals as soon as the first one comes in by looking at it's ID.
- Snapshot proposals are loaded in all at once, so we know this total number pretty quickly.
- Finally, we add the total number of …

1675 proposals card updates

---

src/hooks/utils/useCopyText.ts
src/i18n/locales/en/common.json

Fixes #1932 
See: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

`1932`  adds fallback compatibility for older and mobile browsers

---

src/hooks/DAO/useGetDAOName.ts

Closes: https://github.com/decentdao/decent-interface/issues/1942
See: https://github.com/wevm/viem/discussions/781
TL;DR: simply capture the specific known and expected error, then do nothing about it. If the error _isn't_ this `ChainDoesNotSupportContract` error, then we actually do want to throw it up.

1942 ens chain errors

---

src/hooks/DAO/loaders/useFractalTreasury.ts

Closes #1403
Only able to "`excludeSpamToken`" in this PR, not "only include `trusted` tokens".
For more context, see
- https://github.com/decentdao/decent-interface/issues/1403#issuecomment-1976885673
- https://github.com/decentdao/decent-interface/issues/1403#issuecomment-1976970672
- https://github.com/decentdao/decent-interface/issues/1403#issuecomment-1976970672
@decentdao/engineering, please take a look at https://github.com/decentdao/decent-interface/issues/1267 and let me know if you have any ideas...

Exclude spam tokens from Treasury page

---

src/pages/home/MySafes.tsx

Make "no Safes" copy only break to two lines on mobile view

---

src/components/pages/DAOTreasury/sendAssets.ts
src/components/pages/DaoSettings/components/Signers/hooks/useAddSigner.ts
src/components/pages/DaoSettings/components/Signers/hooks/useRemoveSigner.ts
src/components/ui/forms/BigIntInput.tsx
src/components/ui/modals/SendAssetsModal.tsx

Closes #1945 
See also: https://github.com/decentdao/decent-interface/pull/1928#discussion_r1619245208
I have chosen not to formik-ify the custom nonce input as it's got its own validation and wouldn't make sense to force that back outside to be handled by Formik/Yup

Formik-ify more send asset modal form fields

---

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
src/components/DaoCreator/formComponents/GuardDetails.tsx
src/components/ProposalBuilder/index.tsx
src/components/ProposalTemplates/ProposalTemplateCard.tsx
src/components/Proposals/MultisigProposalDetails/TxActions.tsx
src/components/pages/DaoSettings/components/MetadataContainer.tsx
src/components/pages/DaoSettings/components/Signers/modals/AddSignerModal.tsx
src/components/pages/DaoSettings/components/Signers/modals/RemoveSignerModal.tsx
src/components/ui/forms/CustomNonceInput.tsx
src/components/ui/modals/ProposalTemplateModal.tsx
src/components/ui/modals/SendAssetsModal.tsx
src/i18n/locales/en/proposal.json
src/pages/daos/[daoAddress]/new/index.tsx
src/pages/daos/[daoAddress]/proposals/new/index.tsx
src/providers/App/hooks/useSafeAPI.ts
src/types/safeGlobal.ts

Fixes #1536
I left two comments (I'll point them out) on some logic around nonce.
Basically just slightly reverted the change where safe.nonce is replaced by nextNonce. I've added a new property to the typing and place `nextNonce` as its own property so that we still have current nonce on hand that we can use to prevent execution of other proposals of higher nonce

`1536` prevent execute if not next nonce

---

src/hooks/utils/useUpdateSafeData.ts
src/pages/DAOController.tsx
src/pages/daos/[daoAddress]/proposals/new/index.tsx

Fixes #1568
Not sure if we should also cache and/or exclude routes. but move the implementation done in the New Proposals page to the `DAOController` and set it up to make the request whenever the url changes. 
The alternative to this, would be to refactor this hook back to the `isMounted` ref setup and add the hook to the particular pages/models/components that may create a proposal. But then we have to add it to any new pages/components that may need this features. Thoughts?

`1568` nonce page refresh

---

src/components/Proposals/ProposalSummary.tsx
src/components/ui/links/DisplayAddress.tsx
src/components/ui/links/DisplayTransaction.tsx
src/components/ui/links/EtherscanLink.tsx
src/components/ui/links/ExternalLink.tsx
src/components/ui/proposal/InfoRow.tsx
src/components/ui/proposal/ProposalCreatedBy.tsx

closes #1971 
Testing: 
Confirm that links in proposal summary use text link pattern instead of pill design:
Design:

Use the text link pattern in lieu of the pill button

---

src/components/ui/icons/FavoriteIcon.tsx
src/components/ui/menus/DAOSearch/SearchDisplay.tsx
src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
src/components/ui/menus/SafesMenu/SafesList.tsx
src/components/ui/utils/MySafesErrorFallback.tsx
src/hooks/DAO/loaders/useFavorites.ts
src/hooks/DAO/useGetDAOName.ts
src/hooks/utils/useDisplayName.ts
src/i18n/locales/en/common.json
src/pages/home/AllSafesDrawer.tsx
src/pages/home/MySafes.tsx
src/pages/home/SafeDisplayRow.tsx
src/utils/address.ts
src/utils/url.ts

Fixes #1710
Kinda a weird one to fit in the middle but wanted this work to be done prior to the Local Storage migration actually is done so that the typing is setup.
This PR handles adding the network prefix to the cached favorite string. It also adds some helper functions to get the network prefix and chain id via the network prefix to allow for the UI around the favorites.

`1931` Part 2: `1710` Cross network favorites

---

src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
src/hooks/utils/cache/cacheDefaults.ts
src/hooks/utils/cache/useLocalStorage.ts
src/utils/contract.ts

Noticed that I missed the Average Block Time so added that here.

`1930` local storage version control

---

src/components/Proposals/MultisigProposalDetails/TxActions.tsx
src/components/Proposals/ProposalActions/ProposalAction.tsx
src/components/Proposals/ProposalSummary.tsx
src/hooks/DAO/loaders/governance/useAzoriusListeners.ts
src/hooks/DAO/loaders/governance/useSafeMultisigProposals.ts
src/hooks/DAO/loaders/useLoadDAOProposals.ts
src/hooks/utils/useUpdateTimer.tsx
src/i18n/locales/en/proposal.json

Closes #1558
This PR patches up the time delay between when the app indicates a proposal timelock and/or execute transaction has been successfully ran and when the data actually indicates as much.
We have achieved this by simply keeping the execute button disabled after the success toast. If the user chooses to stay on the screen, eventually the node data will be updated, and the button will disappear.
In the case of timelock, the button will re-enable itself after timelock when the proposal becomes executable.
I expect, if the user refreshes the page in that small window where the node hasn't reflected the updated proposal state, the button will then be clickable -- not much we can do in that case beyond localstorage caching, which we _have_ discussed. Problem is multisig safe proposals …

Fix execution button delay

---

src/components/Proposals/AzoriusDetails/index.tsx
src/components/Proposals/ProposalActions/ProposalAction.tsx
src/components/Proposals/ProposalSummary.tsx
src/components/Proposals/SnapshotProposalDetails/index.tsx

This is a follow up PR to #1990 to rename some generic proposal types to specific Azorious or Snapshot proposal types, where the context dictates that those are the only possible types involved.

Some renaming, cleanup on #1990

---

src/components/DaoCreator/formComponents/VotesTokenImport.tsx
src/components/DaoCreator/index.tsx

Closes #1981
edit from Adam: After more product review, this PR should actually be a different implementation. Instead of only allowing numeric input for the given input field, it should _disallow all input_.

Fix token import supply allowing alphanumeric input

---

src/helpers/crypto.ts
src/hooks/DAO/loaders/useFractalFreeze.ts
src/models/AzoriusTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/FreezeGuardTxBuilder.ts
src/models/MultisigTxBuilder.ts
src/models/helpers/fractalModuleData.ts
src/models/helpers/safeData.ts

Depends on https://github.com/decentdao/decent-interface/pull/2002
- Remove unused `buildContractCall` and rename `buildContractCallViem` back to `buildContractCall`

Remove typechain cleanup 2

---

src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/AzoriusTxBuilder.ts
src/models/BaseTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/FreezeGuardTxBuilder.ts
src/models/TxBuilderFactory.ts

Depends on https://github.com/decentdao/decent-interface/pull/2004
- Don't need `signerOrProvider` in transaction builder classes any longer

Remove typechain cleanup 4

---

src/hooks/DAO/useGetDAOName.ts
src/providers/NetworkConfig/NetworkConfigProvider.tsx

Fixes #2043 
Now, all Favorited Safe names will load regardless of the currently connected network.

Fix crosschain favorites names

---

src/components/pages/Roles/RoleCard.tsx
src/components/pages/Roles/RolesTable.tsx
src/components/ui/cards/Card.tsx
src/components/ui/page/Header/Avatar.tsx
src/components/ui/page/Header/PageHeader.tsx
src/hooks/DAO/useGetDAOName.ts
src/i18n/index.ts
src/i18n/locales/en/roles.json
src/pages/daos/[daoAddress]/roles/index.tsx

Closes #2046
Adds the first pass at the main components of the Roles index page. 
This includes:
- `RoleCard`: For Mobile, Will also be used for 'Edit' page. Where a few updates will be made in that PR for the badges
- `RolesTable`: For Desktop, Same as above.
- `roles.json`: translation file added
@decentdao/engineering I added a try/catch to `getDAOName` where it hits the `demoData` as it was causing a uncaught error which would prevent this returning. 
@~Reviewers. This doesn't use live data. I mocked setup by passing in props, I expect this to change as it gets integrated with live data. I also did not add a conditional preventing the 'No Hats exists' UI and the Mocked Cards and Table to show together.
Currently there are no click/navigating interactions and will be added in future …

`2046` roles index page components

---

src/hooks/DAO/loaders/useHatsTree.ts
src/hooks/DAO/useKeyValuePairs.ts

Closes #2083
After hearing live event for new Hat Tree Id, pause 10 seconds before adding that to state

Fix "Top Hat ID is invalid" error that pops up right after new role creation is executed

---

src/components/pages/Roles/forms/RoleFormTabs.tsx

Show "Coming soon" Tooltip for Sablier functionality

---

package-lock.json
package.json
src/hooks/utils/rolesProposalFunctions.ts
src/pages/daos/[daoAddress]/roles/edit/index.tsx
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/network.ts

Roles 0.1.0/decenthats contract

---

src/components/pages/Roles/forms/RoleFormInfo.tsx
src/hooks/schemas/roles/useRolesSchema.ts

`2128` ensure Role Info form validates correctly

---

src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
src/pages/daos/[daoAddress]/roles/edit/summary/index.tsx

Remove Grid component and adjust width to properly size screen
Fixes #2139

`2139` Clean up Create Role Proposal UI

---

src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
src/components/pages/Roles/forms/RoleFormInfo.tsx
src/hooks/schemas/common/useValidationAddress.tsx
src/hooks/schemas/roles/useRolesSchema.ts
src/i18n/locales/en/roles.json
src/pages/daos/[daoAddress]/roles/edit/details/index.tsx

Fixes #2143
- This is fixed by fixing the schema to work properly preventing clicking Save button when its a invalid address
---
Fixes #2144 
- There was a problem with the structure of the schema. 
- `.default(undefined)`: Adding this stopped Yup from changing the initial value from `undefined` to `{}` which was causing the `is` conditional to be true when it should be undefined
- `.nullable()`: allows for the `setFieldValue(undefined)` that we are using to actually clear the field.
---
- I also noticed that there was some left over 'remove' code that no longer is needed and causing a bug.
- I also re-added the `meta.touched` and got that working properly by using the `onBlur` prop

`Roles` | Various role create form bugs

---

package-lock.json
src/components/pages/Roles/RolesTable.tsx

Fixes #2161 
The `EditBadge` wasn't showing up for some reason in table in the extra column, but either way Design had updated with a new position with the Role name. So updated
@decentdao/engineering I have a habit of doing `nvm use` -> `npm install` when pulling in new from develop. `package-lock.json` was out of sync

`2161` roles table edit badge update

---

src/hooks/DAO/loaders/useDecentTreasury.ts

Closes #2185. 
We were using up our allotted Netlify Functions invocations much faster than anticipated (and are almost past our "free tier" usage), and a likely culprit was the fact that when a Safe is loaded, we re-fetch token/nft balances every 20 seconds.
This seems excessive.
This PR removes that timer and simply fetches balances at page load once, then no more.

Don't refetch token balances every 20 seconds

---

.env
netlify/functions/balances.mts
netlify/functions/nftBalances.mts
netlify/functions/tokenBalances.mts
netlify/shared/moralisBalances.mts
tsconfig.json

Fixes https://github.com/decentdao/decent-interface/issues/2192
There are two things happening in this PR:
1. Implement the new logic which fixes the issues encountered with Netlify caching Moralis empty responses which are only empty because it hasn't been indexed yet.
2. DRY the code, because the two functions were super similar.
1. Create new Azorius safe, sending some tokens to the new Safe's treasury
2. Notice that upon initial deployment there are no balances for this Safe. It's because Moralis hasn't indexed this address in the very short amount of time between Safe being deployed and us trying to fetch its token balance.
3. Wait a few seconds, then refresh the page.
4. Notice how there is a token balance now.
These are the various conditions that we may find ourselves in, and what …

Improve token/nft balance caching

---

src/components/pages/Roles/forms/RoleFormCreateProposal.tsx

Roles proposal input alignment

---

src/components/Proposals/ProposalSummary.tsx
src/components/ui/utils/ProgressBar.tsx

Use "useLocaleString" for displaying quorum numbers

---

.env
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/vite-env.d.ts

Closes #2211 
I've added `VITE_APP_ALCHEMY_API_KEY` to both Netlify sites, values being the current "Mainnet" Alchemy App's API key.
As this is merged into `develop` and `main`, I'll remove the unused environment variables from Netlify config, and I'll delete the apps on the Alchemy accounts (leaving the "Mainnet" app, and renaming it to be more generic, of course).

Consolidate Alchemy keys into single environment variable

---

src/components/pages/Roles/forms/RoleFormSectionTitle.tsx

`2173` Add zIndex to RoleFormSectionTitle for better layering

---

src/components/ui/proposal/Markdown.tsx
src/hooks/utils/useSkipTab.ts

Fixes #2170
When proposal descriptions are being displayed in the "collapsed" view (like on the Dashboard, and Proposal pages), using tab to cycle through links in the page will not include the links in the proposal description which are hidden in the collapsed view, which was causing rendering bugs (see video in issue).
Tab selection behavior is unchanged on Proposal Details view. Still want links in that view to be selectable via tab.

No tab selection

---

src/assets/abi/SablierV2LockupLinear.ts
src/components/pages/Roles/RolesDetailsDrawer.tsx
src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
src/hooks/streams/useCreateSablierStream.ts
src/hooks/utils/useCreateRoles.ts
src/i18n/locales/en/common.json
src/i18n/locales/en/roles.json
src/pages/daos/[daoAddress]/roles/details/PaymentDetails.tsx

This PR implements basic UI and logic for withdrawing payment to the hat wearer.
It also fixes filtering of added/edited payments as previously added payment was also considered as edited.
Closes #2186 
Testing steps:
1. Create payment for any given role, where you're a wearer. Make total length of the payment short enough so that you could easily withdraw sufficient amount of tokens (1 hour for 1000 tokens should be good).
2. Vote and execute proposal for creating payment to the role
3. Go to the role details - payment info should appear there
4. Notice "Withdraw" section appearing in the payment details
5. Enter amount to withdraw (do not put maximum amount just yet) and hit "Withdraw" - this will prompt to sign transaction
6. Make sure proper amount of tokens were sent to your wallet …

`[roles-0.2.0]` Claim hat stream

---

src/pages/DAOController.tsx
src/pages/home/HomePage.tsx

In a previous commit, we moved the calls to `resetSafeState` and `resetHatsStore` from the home page to the dao controller component, as that felt like the more logical place to put it. 
While the argument is still valid, this just led to more bugs due to the brittle nature of the flow of safe state changes.
We have tried moving the `reset`s higher up the hierarchy into `Layout/index.tsx` with slightly better result, but far from good enough. 
That said, the decision was made to revert this move for now. This fixes the original bug described in #2084, with the caveat that there are edge cases around switching safes instantly using the search bar, when already on the roles page of the current safe.
This will have to do for now as the most common UX flows to end up on different safes should …

Revert safe reset refactor

---

src/components/ui/page/Layout/index.tsx
src/hooks/DAO/loaders/useFractalNode.ts
src/hooks/DAO/loaders/useHatsTree.ts
src/hooks/DAO/useKeyValuePairs.ts
src/pages/DAOController.tsx

@decentdao/engineering has decided it is time to take a deeper look at the application's state management. 
To that end, this PR will now serve as the first of a series of PRs with the end goal of migrating to Zustand, AND optimising our state management. 
The logs and guard checks in this PR may or may not change after the work is complete.
In any case we're leaving the changes in - to be merged as _part_ of the state overhaul work - so we can validate that the roles loading issues described below have in fact been fixed. Then we can cleanup whatever needs cleaning up, if any, from the changes on this PR.
---
ORIGINAL DESCRIPTION:
I’m making some progress with the safe state stuff. While there still is the issue of repeated calls to the same set of functions (maybe this already existed …

Debug reset safe state

---

src/components/Proposals/ProposalSummary.tsx

Fixes #2244
When calculating voting power per proposal, query the strategy contract, not token contract directly.
See the screenshot in the attached issue for the erroneous "0" voting power displayed.
See this screenshot for the fix

Fix per-proposal voting power display

---

src/components/DaoCreator/formComponents/EstablishEssentials.tsx
src/components/Proposals/ProposalInfo.tsx
src/components/pages/DaoSettings/components/MetadataContainer.tsx
src/components/ui/cards/DAOInfoCard.tsx
src/components/ui/cards/DAONodeInfoCard.tsx
src/components/ui/forms/ABISelector.tsx
src/hooks/DAO/loaders/snapshot/useSnapshotProposal.ts
src/hooks/DAO/loaders/snapshot/useSnapshotProposals.ts
src/hooks/DAO/loaders/snapshot/useSnapshotSpaceName.ts
src/hooks/DAO/loaders/useFractalNode.ts
src/hooks/DAO/loaders/useLoadDAONode.ts
src/hooks/DAO/proposal/useCastVote.ts
src/hooks/DAO/useGetDAOName.ts
src/hooks/utils/useAvatar.ts
src/models/DaoTxBuilder.ts

Normalise `daoSnapshotENS` to lower case

---

src/components/Proposals/ProposalSummary.tsx
src/hooks/utils/cache/cacheDefaults.ts
src/hooks/utils/useMasterCopy.ts
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/baseSepolia.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/network.ts

Closes #1580 
TLDR:
During creation our safes we were using our deployed instant of `ModuleProxyFactory` contract instead of the 'official' deployed version by zodiac.
This PR adds the official version as the main contract while persevering the old. This effects any new safe created will now use the new contract, We will continue to support looking up these master copies on both version of the copy

`1580 | Bugfix` ModuleProxyFactory updated to zodiac deployed contract

---

src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx

Closes #2289 
To test:
1. Create parent DAO (Multisig / ERC-20 / ERC-721)
2. If you created ERC-20 Parent DAO - make sure to delegate votes to yourself
3. Create child DAO (Multisig / ERC-20 / ERC-721). Just for visualization - set voting period to something reasonably high (1 day) and freeze voting period for something way lower (5 minutes). Vote and execute proposal for creating child DAO
4. Navigate to child DAO dashboard, click gear icon, make sure "Initiate a freeze" option appeared there. Hit the button
5. This will create and immediately cast your vote on freezing child DAO. If you have enough votes to reach threshold - child DAO will be immediately frozen

Fix logic for showing option for initiating freeze

---

src/components/ui/utils/TopErrorFallback.tsx

I'm quite sure this was the original intention and was implemented this way - but seems like we've broke it at some point a while ago cause I've seen this shitty error display but for who knows which reason thought it's intentional. Now I checked Figma - and there you go. Center as it should be. I'm not mad or something 🤣 
https://www.figma.com/design/9hUYtvCKjOyB92vt8ukYtD/Product-Handoff?node-id=2599-8113&m=dev
Before:
After:
@decentdao/engineering though I don't really like the way I implemented this - I wasn't able to come up with meaningful implementation without touching too much of surrounding layout. I'm actually OK keeping this implementation long term, but if someone feels we should implemented it better - feel free to create an issue and we'll tackle it (or plz halp to do that …

Center TopErrorFallback in da middle of the screen

---

src/components/Proposals/ProposalInfo.tsx
src/components/pages/DaoSettings/components/Signers/SignersContainer.tsx
src/components/pages/Roles/RolePaymentDetails.tsx
src/components/ui/modals/ModalProvider.tsx
src/components/ui/modals/PaymentWithdrawModal.tsx
src/components/ui/modals/useDecentModal.tsx

As I was looking at the `RolePaymentDetails` component noticed that the typing for the modal props were a `any`, now they are typed. 
This also updates a few other places where variables could have been passed to the Modal props as undefined.

Typing the Push -> The Withdraw Modal+

---

.env
package-lock.json
package.json
src/helpers/errorLogging.ts
src/insights/amplitude.ts
src/insights/analyticsEvents.ts
src/insights/hotjar.ts
src/insights/hotjar.tsx
src/insights/index.ts
src/insights/sentry.ts
src/main.tsx
src/pages/create/index.tsx
src/pages/daos/[daoAddress]/DaoDashboardPage.tsx
src/pages/daos/[daoAddress]/SettingsPage.tsx
src/pages/daos/[daoAddress]/edit/governance/index.tsx
src/pages/daos/[daoAddress]/hierarchy/index.tsx
src/pages/daos/[daoAddress]/new/index.tsx
src/pages/daos/[daoAddress]/proposal-templates/index.tsx
src/pages/daos/[daoAddress]/proposal-templates/new/index.tsx
src/pages/daos/[daoAddress]/proposals/[proposalId]/index.tsx
src/pages/daos/[daoAddress]/proposals/index.tsx
src/pages/daos/[daoAddress]/proposals/new/index.tsx
src/pages/daos/[daoAddress]/proposals/new/sablier/index.tsx
src/pages/daos/[daoAddress]/roles/edit/index.tsx
src/pages/daos/[daoAddress]/roles/index.tsx
src/pages/daos/[daoAddress]/treasury/index.tsx
src/providers/App/useReadOnlyValues.ts
src/providers/Providers.tsx
src/vite-env.d.ts

This PR will enable Hotjar tracking on the websites that will have the `VITE_APP_HOTJAR_SITE_ID` env variable on it (currently decision is to keep this to prod only).
Caveat: _"Hotjar is currently measuring your site's traffic. This requires 7 days worth of data."_ 
We'll need to wait at least a week after merging to prod and setting up the dashboard for any data to be visible.
UPDATE: This PR is being updated to also include Amplitude analytics.

Add Hotjar for them heatmaps + Amplitude for event analysis

---

src/components/pages/DaoSettings/components/Signers/modals/AddSignerModal.tsx
src/components/ui/modals/DelegateModal.tsx
src/hooks/schemas/common/useValidationAddress.tsx
src/i18n/locales/en/common.json
src/utils/address.ts

I found that the `validAddress`-obtaining logic was also needed in 2 places in `DelegateModal`.
So I've refactored that so we can reuse it, as `resolveAddress`.

`state-overhaul` | Refactor resolve address logic

---

src/components/pages/Roles/RolePaymentDetails.tsx
src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
src/components/pages/Roles/types.tsx
src/hooks/DAO/loaders/useHatsTree.ts
src/hooks/utils/useCreateRoles.ts
src/store/roles/rolesStoreUtils.ts
src/store/roles/useRolesStore.ts

Found the issues with the Edit Stream workflow. Looks like code got duplicated in a merge fix and the wrong address was being passed into the `encodeFunctionData` function for flushing the stream.

`Bugfix` | EditStreams

---

src/components/pages/Roles/RoleCard.tsx
src/components/pages/Roles/RolesTable.tsx

These changes are preventing user from clicking on soft-edited role card / table row.
It is not necessary to redirect user from the soft-edited role details as it is only possible through direct navigation, which will essentially reset form's state.
Closes #2292

Do not allow clicking(aka editing) soft-deleted roles

---

netlify/functions/tokenBalances.mts
src/hooks/DAO/loaders/useDecentTreasury.ts

Two things in here:
1. Moralis API doesn't return good price data for the PAX token. We will just hardcode this to $1.
2. While implementing the PAX price override, I noticed that no treasury transactions were loading (on local, dev, or prod). Seems like the Safe API started returning `null` instead of `undefined` for certain datapoints, which was causing this error in our app. Fixed that.

Fix PAX price and treasury transactions

---

src/components/Proposals/MultisigProposalDetails/index.tsx
src/components/Proposals/ProposalActions/AzoriusOrSnapshotProposalAction.tsx
src/components/Proposals/ProposalActions/CastVote.tsx
src/components/Proposals/ProposalActions/ProposalAction.tsx
src/components/Proposals/ProposalInfo.tsx
src/components/Proposals/ProposalSummary.tsx
src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/components/Proposals/SnapshotProposalDetails/SnapshotProposalSummary.tsx
src/components/Proposals/SnapshotProposalDetails/index.tsx
src/components/ui/proposal/ProposalCountdown.tsx
src/components/ui/proposal/useProposalCountdown.tsx
src/hooks/DAO/loaders/snapshot/useSnapshotProposal.ts
src/hooks/DAO/loaders/useLoadDAONode.ts
src/hooks/DAO/proposal/useCastVote.ts
src/hooks/DAO/proposal/useUserERC721VotingTokens.ts
src/pages/daos/[daoAddress]/proposals/[proposalId]/index.tsx
src/types/daoProposal.ts
src/types/fractal.ts
src/utils/azorius.ts

While working on typechain fixes, I found some naming conventions hard to follow around proposal actions. While digging through the code, I noticed an old TODO recommending a refactor. Got lost in the sauce, did some light moving around and type tightening, and here we are -- a new PR.
Untested, but pls review. If changes make sense, I plan to test in the typechain branch.

Rework useSnapshotProposal and usages

---

package-lock.json
package.json
src/assets/abi/DecentHats_0_1_0_Abi.ts
src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
src/components/pages/Roles/forms/RoleFormSectionTitle.tsx
src/components/pages/Roles/forms/RoleFormTabs.tsx
src/components/pages/Roles/types.tsx
src/hooks/utils/useCreateRoles.ts
src/i18n/locales/en/roles.json

This PR is ready for testing!
Now users are able to create Sablier Payment Streams on new Hats which are being created when _no existing Hats Tree exists for the given DAO_, which was previously blocked.

Streams on new hat tree

---

src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVoteItem.tsx
src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVotes.tsx

- Fix Snapshot proposals visualization with multiple strategies
- Providing info about voting weight per strategy for the vote
- Fix `NaN` in the breakdown when there're no votes on snapshot proposal
Note problem with the breakdown:
Note how we weren't showing all the voting strategies that are applicable for the proposal and voting weight per strategy on the specific vote entry:
Updated implementation:

Snapshot proposal breakdown and votes fixes 

---

src/components/pages/DAOTreasury/prepareSendAssetsProposalData.ts
src/components/pages/DAOTreasury/sendAssets.ts
src/components/pages/Roles/RoleCard.tsx
src/components/pages/Roles/RolePaymentDetails.tsx
src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
src/components/pages/Roles/types.tsx
src/components/ui/modals/AddActions.tsx
src/components/ui/modals/ModalBase.tsx
src/components/ui/modals/ModalProvider.tsx
src/components/ui/modals/SendAssetsModal.tsx
src/constants/common.ts
src/hooks/utils/useCreateRoles.ts
src/i18n/index.ts
src/i18n/locales/en/actions.json
src/i18n/locales/en/modals.json
src/pages/daos/[daoAddress]/roles/edit/index.tsx
src/pages/daos/[daoAddress]/treasury/index.tsx
src/utils/dao/prepareSendAssetsProposalData.ts

Add send assets action to roles proposal

---

src/pages/daos/[daoAddress]/proposals/new/sablier/index.tsx

- Fixes decimal places for stream tranche duration on Sablier proposal builder.
- Disable "Submit" button if there're any invalid streams 
- Minor UI fixes for Sablier proposal builder
Testing these changes:
1. Navigate to "Sablier Proposal Builder", example: http://localhost:8888/proposals/new/sablier/metadata?dao=sep:0x7d0E8e93B5785CB4d5c76f65BB798B3d0a3e89Cb (replace with your DAO address
2. Fill out title and description, proceed to next step
3. Create 1 stream. Fill out token address and amount, input tranches. 
4. Try to put 0 as duration for first tranche - make sure "Create proposal" button disabled
5. Now, put all the valid information, create proposal and make it pass. Verify on Sablier that stream was created with proper tranches durations and amounts

Some additional validation and UI fixes for Sablier Proposal builder

---

src/components/ui/forms/BigIntInput.tsx

BigIntInput was broken after (EDIT: a fix from) the typechain merge -- no input was getting registered. This PR fixes that.

Fix BigIntInput

---

src/hooks/DAO/useDAOController.ts
src/pages/DAOController.tsx
src/router.tsx

When user navigates directly to the DAO, which is not on mainnet (base - for instance) - app default to mainnet anyway and displays "wrong network" error.
This PR implements attempt to automatically switch network. Far from being perfect - wrong network screen will be displayed as long as network is not switched. Automatic attempt might fail due to intermittent RPC errors. If wallet is not connected - it pretty much always works. If wallet is connected - some issues might occur depending on specific wallet used (if wallet does not support adding chain alongside with switching at single request).
This is kinda hot-fix and we'll need longer term solution - temporary patch to improve UX for MCON.
1. Try visiting https://app.decentdao.org/home?dao=base:0x0BcC8861d36B610f19492C8E512Ebb9E99BB765 …

Attempt switching chain automatically when on wrong network

---

src/hooks/DAO/loaders/useDecentTreasury.ts

Closes #2369 (~kinda~ fr)
This PR implements a fallback for transferred token data when `safeAPI.getToken` throws.
The cause of the "no token matches given query" exception is still unclear, as the address is quite clearly on etherscan (and Moralis returns its balance if the safe has some). ~While this fallback works for safes that have _some_ balance of the problem token, it doesn't for safes that have a 0-balance even if they at one time had some.~ The fallback retrieves token info from the blockchain directly.
Also the `setTimeout` retry in case of rate limited error was removed because I'm not sure about the end result of this PR yet and didn't want to commit to a lengthy refactor at this point. If needed, this functionality can be restored in some form during review.

Use `fallbackTokenData`

---

src/hooks/utils/useCreateRoles.ts

The dev team discovered a few bugs that will cause the wrong role member to be set in some scenarios, and in one instance, for an edited role to fail to transfer the hat back from the safe to the original/intended wearer. 
This PR addresses those issues.

Fix original wearer bug

---

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
src/hooks/DAO/useDeployAzorius.ts
src/hooks/utils/useVotingStrategyAddress.ts
src/i18n/locales/en/daoCreate.json
src/pages/daos/[daoAddress]/edit/governance/index.tsx
src/types/createDAO.ts

This PR adjusts the way of modifying governance for subDAOs.
There's one issue that I outlined in the code comment - when DAO has subDAOs - that means we also need to swap guard contracts. However, that is possible only when there's `FractalModule` attached. Otherwise - whole Freezing wouldn't work anymore.
Closes #2387 
1. Create parent DAO (ideally - Azorius)
2. Create 2 Multisig child DAOs (for testing with ERC-20 and ERC-721) without attaching `FractalModule` to them
3. Modify governance on 1st child DAO to ERC-20 AND attach Fractal Module during this process 
4. Make sure `FractalModule` get's attached and guard has proper `parentVotingStrategy` and `parentGovernanceToken`
5. Verify Freeze works as expected
6. Modify governance on 2nd child DAO to ERC-721 AND DO NOT ATTACH …

Modifying governance for subDAO

---

src/components/pages/Roles/forms/RoleFormTabs.tsx
src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
src/pages/daos/[daoAddress]/roles/edit/index.tsx

This PR resets blocker state when saving role form.
- Closes #2395 
1. Go to editing some role. Change any field.
2. Click outside of drawer
3. You should see "Unsaved changes" modal - click "Keep Editing"
4. Now hit Save button
5. Verify that changes were saved and you navigated back to roles list.

Fix unsaved changes stuck state

---

src/components/pages/Roles/RolesDetailsDrawer.tsx
src/components/pages/Roles/RolesDetailsDrawerMobile.tsx
src/components/ui/modals/PaymentWithdrawModal.tsx
src/hooks/DAO/loaders/useHatsTree.ts
src/hooks/DAO/useDAOController.ts
src/hooks/DAO/useKeyValuePairs.ts

Fixes #2408 
viem's `getAddress` code:
our code in the place where we're pulling in payment stream data:
results in a checksummed address that doesn't follow "normal" checksumming patterns:

Fix payment stream usd value

---

src/components/DaoCreator/formComponents/AzoriusNFTDetail.tsx
src/components/pages/Roles/RoleCard.tsx
src/components/pages/Roles/RolesDetailsDrawer.tsx
src/components/pages/Roles/RolesTable.tsx
src/components/ui/menus/SafesMenu/SafeMenuItem.tsx
src/hooks/DAO/loaders/useFractalNode.ts
src/hooks/DAO/loaders/useLoadDAONode.ts
src/hooks/utils/useDisplayName.ts
src/hooks/utils/useGetAccountName.ts
src/hooks/utils/useGetSafeName.ts
src/pages/home/SafeDisplayRow.tsx
src/providers/NetworkConfig/NetworkConfigProvider.tsx

Fixes on top of the base PR #2414 that @DarksightKellar is working on:
- Renames `useGetAccountName` to `useGetSafeName`. This hook is _only for getting Safe / DAO names_. We have a different hook, `useDisplayName`, for getting ENS names of accounts.
- This `useGetSafeName` hook will, in order, attempt to get and return the name for a safe: 1) by ENS name of the Safe Address, 2) by FractalRegistry name of the Safe address, 3) by truncating the address
- This `useGetSafeName.ts` file now only exports one function instead of three. Much cleaner. We can use it everywhere we need to get a Safe name, whether on the current network or not (as in the case of Favorites which might be on any network).
- Small cleanups to the `useDisplayName` hook, to remove unused parameters
- Small improvement to …

2411 fix wearer ens continued

---

src/components/pages/Roles/RolesTable.tsx
src/components/pages/Roles/forms/RoleFormAssetSelector.tsx
src/components/pages/Roles/forms/RoleFormCreateProposal.tsx
src/components/pages/Roles/forms/RoleFormInfo.tsx
src/components/pages/Roles/forms/RoleFormPaymentStream.tsx
src/components/pages/Roles/forms/RoleFormPaymentStreams.tsx
src/components/pages/Roles/forms/RoleFormTabs.tsx
src/components/pages/Roles/forms/useRoleFormEditedRole.ts
src/components/ui/utils/DecentDatePicker.tsx
src/pages/daos/[daoAddress]/roles/edit/details/index.tsx
src/pages/daos/[daoAddress]/roles/edit/index.tsx
src/pages/daos/[daoAddress]/roles/edit/summary/index.tsx
src/utils/TypesafeForm.tsx

The Typesafe Formik stuff was actually pretty broken. The `Field` and `FieldArray` props coming out of the hook were `undefined`. Oops!
Attempting to fix it started leading down a path that didn't have a clear end, so, this PR simply undoes all of the usage of `makeTypesafeForm` and `useTypesafeFormikContext`, to give me some more time to debug this while not blocking everyone else.

Undo typesafe formik

---

src/hooks/utils/useCreateRoles.ts

Closes #2446 
So looking into it. 
- `getStreamsWithFundsToClaimFromFromHat`: 
- is used during `member change` action. 
- filters for `withdrawableAmount` and `isCancelling` (which indicates the user has set this payment to be cancelled)
- `getStreamsWithFundsToClaimFromFormHat`:
- is used during `role removed` action
Looking into it. When the role is removed. all streams are cancelled and flushed. so the user can't add in additionally to cancel individual streams. In the case of `member change` we track that if a stream is marked for cancelling that it is ignored  when looking at what streams to flush during that section and handled in the `payments` section

`[BUGFIX]` rename getStreamsWithFundsToClaimFromFromHat -> getStreamsWithFundsToClaimNotCancelling

---

src/hooks/utils/useMasterCopy.ts
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/network.ts

- Includes the COMPLETELY UNUSED (which is probably a bug) `linearVotingErc20WrappedMasterCopy` contract into our network config.
- Still not actually using this anywhere, but we probably should. I bet this should be deployed as the strategy when we wrap a user's existing ERC20 token.
- Re-adds the caching back into `useMasterCopy` (it's been well over a week since it was disabled, which is the time after which those caches went stale, so it's safe to re-enable them).
- Remove an unused `address` property from object returned from `getZodiacModuleProxyMasterCopyData` function which comes from `useMasterCopy` hook
- Add _all_ of the non-singleton contracts to `useMasterCopy`.
- Some are already there, but not all. Why, you ask? Probably because there are lots of places in the app where we …

Add all contract tests to `useMasterCopy`

---

package-lock.json
package.json
src/assets/abi/ZodiacModuleProxyFactoryAbi.ts
src/components/pages/Roles/types.tsx
src/hooks/DAO/loaders/useHatsTree.ts
src/hooks/streams/useCreateSablierStream.ts
src/hooks/utils/useCreateRoles.ts
src/models/AzoriusTxBuilder.ts
src/models/FreezeGuardTxBuilder.ts
src/models/helpers/fractalModuleData.ts
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/network.ts

Brings in the new version of `@fractal-framework/fractal-contracts`, which includes a number of breaking changes, which are fixed in this PR:
- ZodiacModuleProxyFactory (neither address nor ABI) is no longer exported from `fractal-contracts`
- This PR adds the ABI as an import in `src/assets/abis`, and removes the `zodiacModuleProxyFactoryOld` property from Network Config
- Cleanup: removes an unused reference from a `useEffect` dependency
- Adds the `@hatsprotocol/modules-sdk` package, to get access to the "module factory" deployment address
- Updates names of some existing contract addresses in NetworkConfig, and add a few more
- `decentHatsMasterCopy` variable has been broken up into `decentHatsCreationModule` and `decentHatsModificationModule` variables
- !!! It's not a "Master Copy". …

Update fractal contracts package

---

src/hooks/utils/useAddressContractType.ts

Remove DOMAIN_SEPARATOR from `isVotesErc20` and `isVotesErc20Wrapper` fingerprint.
I ran this change through my test repo, and all tests on sepolia still passed. So, this `DOMAIN_SEPARATOR` part of the fingerprint that I removed wasn't required to produce a unique fingerprint.

Fix Shutter not loading on mainnet

---

src/hooks/utils/cache/migrations/2.ts
src/main.tsx
src/types/global.d.ts
src/utils/polyfills.ts

This was causing bad proposal data to get cached in local storage, resulting in crashes on prod.
Also need to delete cached proposal data because yeah, it was cached and it was bad.

Revert global bigint serialization

---

src/hooks/DAO/loaders/useFractalGovernance.ts

`dao` might be undefined despite what the type says

`dao` might be undefined despite what the type says

---

src/components/Proposals/ProposalActions/CastVote.tsx
src/components/Proposals/ProposalVotes/context/VoteContext.tsx

(Mostly) fixes #2471
Still some weirdness around not automatically disabling the voting components after a successful vote, but whatever. It's much more important to actually let people vote, than signal to them they they've already voted _immediately after they just voted_

Don't get stuck in a loop when loading voting components

---

src/insights/amplitude.ts

On prod, get this warning in the console:
This PR exists to silence that warning.

Explicitly enable default tracking to silence browser console warning

---

src/hooks/DAO/loaders/useHatsTree.ts

Noticed that I was passing the `hat.wearerAddress` incorrectly to retrieve payments for normal roles.
This was while exploring a slightly annoying issue of termed payments and tying it to a single hat. But unrelated to this PR so pushed this commit up. See #2479

`BugFix` Pass SmartAddress to retrieve normal roles streams

---

.graphclientrc.yml
src/components/DaoHierarchy/DaoHierarchyNode.tsx
src/components/ui/cards/DAONodeInfoCard.tsx
src/hooks/utils/useGetSafeName.ts
src/pages/dao/hierarchy/SafeHierarchyPage.tsx
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts

Closes #2440 
This PR does two things:
1. Removes unused props (and unused data loaders) from a couple of components.
2. Removes all (only one) direct log reads from FractalRegistry contract.
3. Bumps subgraph version to [v0.1.2](https://github.com/decentdao/decent-subgraph/tree/v0.1.2)

No more directly reading anything from FractalRegsistry

---

src/hooks/utils/useCanUserSubmitProposal.ts

Noticed that the Edit Role Button link was missing from the RolesPage. Noticed that we were using `??` here. For this case we would want `||` to capture the boolean `false`.

`Bugfix` Edit Role Link missing

---

package-lock.json
package.json
src/components/Roles/RoleTerm.tsx

Auto Admin contract now correctly handles case when "next term wearer" is same as "current term wearer", so don't need to do different contract calls based on that

Autonomous admin now works with same term member

---

src/components/DaoCreator/hooks/useParentSafeVotingWeight.ts
src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/hooks/utils/useCanUserSubmitProposal.ts
src/pages/dao/settings/governance/SafeGovernanceSettingsPage.tsx
src/providers/App/useReadOnlyValues.ts
src/types/fractal.ts

@mudrila would especially like your eyes on this one.
The reason why I think this PR is valid is because, the at only places where we're doing:
```ts
action.dispatch({
type: FractalGovernanceAction.SET_GOVERNANCE_TYPE,
payload: ...,
});
```
(which are in `useFractalGovernance.ts`)
the only `payload`s that are being used are
- `GovernanceType.AZORIUS_ERC20`
- `GovernanceType.AZORIUS_ERC721`
- `GovernanceType.MULTISIG`
So it seems like the `type` property on the `FractalGovernance` state is never going to be two enum values that I removed in this PR.

Remove two GovernanceTypes from enum, doesn't seem like they were being used anywhere

---

src/i18n/locales/en/breadcrumbs.json
src/i18n/locales/en/daoCreate.json
src/i18n/locales/en/settings.json

`[PRD | Issue #2618]` Copy updates

---

src/hooks/DAO/loaders/governance/useERC20LinearToken.ts
src/hooks/DAO/loaders/useFractalGovernance.ts
src/hooks/DAO/loaders/useGovernanceContracts.ts
src/providers/App/governance/action.ts
src/providers/App/governance/reducer.ts
src/types/account.ts
src/types/fractal.ts

Closes #2614
`underlyingTokenAddress` was left unused after wrap functionality rip. Removed

Remove `underlyingTokenAddress` and `loadUnderlyingERC20Token`

---

src/hooks/DAO/useSearchDao.ts
src/hooks/utils/useResolveAddressMultiChain.ts
src/hooks/utils/useResolveENSName.ts

@adamgall 
Very similar to `useAddress`. 
Main difference it that the execution the lookup doesn't kickoff via `useEffect` but rather the hook spits out the function to be used as directed. 
if you prefer I just refactor this back and fit `useAddress` in I can do that. I just prefer using a `callback` function to time the execution

Refactor `useResolveAddressMultichain` to `useResolveENSName` 

---

src/components/DaoCreator/formComponents/AzoriusTokenDetails.tsx
src/hooks/DAO/loaders/useHatsTree.ts
src/hooks/DAO/useKeyValuePairs.ts
src/hooks/utils/useGetSafeName.ts
src/store/roles/rolesStoreUtils.ts
src/store/roles/useRolesStore.ts
src/types/roles.tsx

Closes #2638 
Did a little refactor as well as with some additional testing. I noticed there was additional calls when switching DAOs because of the extra `useEffect`. 
So refactored `useHatsTree` a little:
- Extracted the async function into callback, accepting some params
- removed sablier payments `useEffect`
- added payments retrieval to `sanitize` method in `setHatTree` workflow
other change:
- fixed conditional I placed in `useKeyValuePairs` causing some issues.

`[Issue #2638]` "unwanted" toasts - HatsTreeId not getting reset when Network Changes

---

src/components/DaoCreator/formComponents/EstablishEssentials.tsx

Noticed that the wallet wouldn't switch to ethereum on page load and that switching networks via the selection wasn't causing hte network to change

`[Bugfix | No Issue]` Add `useEffect` for when wallet is connected to different network

---

src/components/DaoCreator/formComponents/EstablishEssentials.tsx
src/components/DaoCreator/index.tsx

Closes https://linear.app/decent-labs/issue/ENG-50/dev-error-creating-an-nft-dao
So the problem is that I placed the useEffect within the EstablishEssentials form rather than higher up. 
This move makes it if the User switches there network at some point later in the process, the app switches it back keeping the user on the selected network. 
I did attempt to move this selection and network check to the button, but with the current setup within `useBuildDAOTx` where it pulls contracts from `useNetworkConfigStore` in which is set to the current network. 
A future refactor will be needed to confirm to a new pattern of more fine control over what network the DAO is deployed on. 
- Enter Create DAO workflow
- Select Different network from etherem
- Go to end of which DAO creation workflow you …

`[Eng 50]` | Dao creation network switch

---

src/components/ui/forms/ABISelector.tsx
src/hooks/utils/useSafeDecoder.tsx

This PR introduces alternative way of decoding transaction data as a fallback for Safe Decoder. 
It detects whether target address is proxy or not, then tries to fetch smart contract's ABI from Etherscan and parse it. 
<details>
<summary> Some DRYing might be done, though not sure it's worthy</summary>
Note: This part pretty much replicates what we have in `ABISelector` - so maybe some DRYing could be done, not sure it's worth that for ~5 lines of code though. The only replicated logic would be detecting proxy and fetching ABI, but we can't leverage storing ABI since ABI selector needs state storage and `useSafeDecoder` doesn't. Some further improvements, as caching ABI, also might be done - but seems like that's not an issue right now, so maybe we can list that as a further enhancement …

`[ENG-86]` Try decoding transactions with `viem`'s `decodeFunctionData` when Safe Decoder fails

---

src/constants/common.ts
src/hooks/DAO/loaders/governance/useAzoriusProposals.ts
src/utils/azorius.ts

This PR fixes a bug that was preventing VantaDAO from loading. The fix is in `src/utils/azorius.ts`, where the wrong strategy contract appears to have been used to call `getProposalVotes`.
Need confirmation on the true type of VantaDAO. If it's an ERC-721 type and has just one proposal, all is good.
If not, well. We have a problem on our hands here.
- Using a new Incognito Window on Chrome, go to https://app.decentdao.org/home?dao=eth:0xB14AC30AA97057e2A934c47BDc45171335B91Bd8
- Verify that proposals do not load
- Now go to https://DEPLOY-PREVIEW-URL-PENDING/home?dao=eth:0xB14AC30AA97057e2A934c47BDc45171335B91Bd8
- Verify that proposals load

Fix proposal load bug

---

src/assets/css/Toast.css

`[ENG-5]` Fix misaligned toast loading icon

---

src/pages/create/SafeCreatePage.tsx

Looks like this was set to `infinity`, removed that.
Closes [ENG-84](https://linear.app/decent-labs/issue/ENG-84/cannot-close-toast)
As this particular toast is part of a failure workflow, might take a few tries to reproduce. I have this happen more often when creating Token DAOs, so I'd recommend that, if you are itching to test, otherwise, pretty straight forward fix.
No Screenshots

`[ENG-84]` Toast not closing

---

src/components/ui/menus/DAOSearch/index.tsx

Fix ugly line under search box

---

src/components/DaoDashboard/Activities/ProposalsHome.tsx
src/components/Proposals/ProposalsList.tsx
src/components/ui/utils/PaginationControls.tsx
src/hooks/utils/usePagination.ts
src/i18n/locales/en/common.json

Closes https://linear.app/decent-labs/issue/ENG-108/create-pagination-controls-for-proposals-list
I wanted it to exist, so I told the AI to do it, and it did.
Will create PM artifacts in the AM.

Create pagination on home page proposals list

---

src/components/DAOTreasury/components/Transactions.tsx
src/hooks/DAO/loaders/useDecentTreasury.ts
src/i18n/locales/en/treasury.json
src/types/daoTreasury.ts

Closes [ENG-49](https://linear.app/decent-labs/issue/ENG-49/dev-when-i-created-a-new-dao-in-treasury-transactions-shows-the-mint)
- Create Token DAO and Don't allocate all the token (or go to a newer existing Token DAO). You should now see mint transaction.
- Click on any transaction, should direct you to the transaction details

`[Eng 49]` Show Mint event as seperate transfer event

---

src/hooks/utils/useAutomaticSwitchChain.ts

Closes [ENG-101](https://linear.app/decent-labs/issue/ENG-101/dao-does-not-load-properly-when-on-wrong-network)
While I believe this setup isn't long (hopefully) for this codebase as discussed in @adamgall 's comments in #2658. it should still work. and was not taking in account the fact that mainnet is the default network for our network config. 
This would cause app to think everything was good to go and not switch the wallet's network...
Soooo this will fix that thanks for flagging @DarksightKellar 
- Visit any sepolia DAO. (or be on home page of app and manually switch network to sepolia. and close the tab.
- Then in new tab visit `/home?dao=eth:0xB14AC30AA97057e2A934c47BDc45171335B91Bd8`.
- or just be on Home page and search and visit the above address while connected to sepolia. …

`[ENG-101]` Fix conditional logic preventing switch chain from working properly

---

src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/hooks/DAO/proposal/useCastVote.ts

Closes [ENG-87](https://linear.app/decent-labs/issue/ENG-87/voting-quorum-is-not-updated)
Closes [ENG-4](https://linear.app/decent-labs/issue/ENG-4/vote-button-doesnt-disappear-after-voting-and-refreshes)
Create or use an existing Token DAO with at least 2 accounts (quicker with 3 or 4)
Account 1: Allocated, Self-Delegated
Account 2: Allocated, Self-Delegated
Account 3: Allocated, Delegated to account 4
Account 4: not-allocated, delegated power from account 3
For easy proposal creation, I used update DAO name.
For easy testing, I'd increase voting period.
Use allocated and self-delegated accounts and vote. Vote details should update on screen (quorum and vote summary)
Great ✅,
Next switch between other accounts, to ensure that the button acts properly
- hasVotingPower and hasn't voted -> …

`[Eng-87] | [ENG-4]` voting context updates

---

src/hooks/DAO/proposal/usePrepareProposal.ts
src/utils/crypto.ts

Closes [ENG-116](https://linear.app/decent-labs/issue/ENG-116/from-cannot-use-%5B%5D-or-%5B-%5D-as-param-value)
For testing use this address for the target address `0xB2586A28840dD03Ca3EF402FDeEd835620A2F00B`
You can check [on etherscan](https://sepolia.etherscan.io/address/0xB2586A28840dD03Ca3EF402FDeEd835620A2F00B#code). First create a proposal to add a address to the array using `updateAddresses`. Then create a proposal with an empty array `[]` or `[ ]`. You will see that the length return 0.

`[ENG-116]` Support empty array as param value

---

src/components/ui/page/Global/index.tsx
src/helpers/featureFlags.ts

Closes [ENG-128](https://linear.app/decent-labs/issue/ENG-128/help-migrate-users-from-old-dev-site-to-new-dev-site)
Uses a new Feature Flag (environment variable `VITE_APP_FLAG_LEAVE="on"` set on the Netlify `decent-interface-dev` project) to trigger a persistent toast explaining to users that this domain (app.dev.decentdao.org) is being shut down, and instructions on how to migrate their "My DAOs".

Handicap netlify

---

src/components/Proposals/ProposalActions/CastVote.tsx
src/components/Proposals/ProposalVotes/context/VoteContext.tsx
src/hooks/DAO/proposal/useUserERC721VotingTokens.ts

Closes https://linear.app/decent-labs/issue/ENG-136/contango-couldnt-vote
Currently, users are unable to vote on ERC 721 Token proposals. The "Vote" button does not appear when loading the app with a wallet connected that DOES have voting power on a proposal that already exists is and open for voting.
This PR addresses that bug.
Fixed two bugs, and do some cleanup.
Bugs fixed:
1. "zero is not undefined". When the `tokenId` of an owned NFT by the connected address is `0`, that was returning truthy in a place where we actually want to check if it's `undefined`.
2. Refactor VoteContext to improve voting eligibility checks and update user reference handling
a. Modified getCanVote function to accept remainingTokenIdsLength as a parameter for better clarity and efficiency.
b. Updated user …

Erc721 vote button

---

src/components/ui/forms/ABISelector.tsx

Closes [ENG-90](https://linear.app/decent-labs/issue/ENG-90/proposal-builder-target-address)

`[ENG-90]`  Resetting ABI selector state on failure

---

src/components/Roles/RoleCard.tsx
src/components/Roles/RolesTable.tsx
src/pages/dao/roles/SafeRolesPage.tsx
src/pages/dao/roles/edit/SafeRolesEditPage.tsx
src/types/roles.tsx

Closes [ENG-71](https://linear.app/decent-labs/issue/ENG-71/bugfix-member-field-pending-when-no-terms)
I don't have the before shot, but the logic was missing and was missing an update.

`[ENG-71]` Role Term 'pending' Showing incorrectly

---

src/hooks/schemas/roles/useRolesSchema.ts

Closes [ENG-177](https://linear.app/decent-labs/issue/ENG-177/role-payment-validation-can-be-blocked-by-past-payments)

`[ENG-177]` Existing payment causing validation error

---

src/hooks/useNetworkEnsAddress.ts
src/hooks/useNetworkEnsAvatar.ts
src/hooks/useNetworkEnsName.ts

sorry @DarksightKellar 
Closes [ENG-180](https://linear.app/decent-labs/issue/ENG-180/deployed-a-base-dao-doesnt-load)
Closes [ENG-182](https://linear.app/decent-labs/issue/ENG-182/deployed-a-polygon-dao-does-not-load)
@adamgall Called out about the fallback to mainnet, but I pushed back only thinking about the argument `chainId` and protecting against unintentionally setting it to call an unsupported network.

`[ENG-180 | ENG-182]` Unsupported ENS networks

---

src/providers/App/hooks/useSafeAPI.ts

Closes [ENG-190](https://linear.app/decent-labs/issue/ENG-190/multisig-cannot-execute-proposal)
Traced the weird conditional failure all the way back to the nonce we receive from Safe's API. The API's `SafeInfoResponse` type for nonce `number` but actually typed a `string` on the response...Something has changed as of like yesterday?
This change is basically causing any `===` comparison to fail comparing against the proposal's nonce
Edit: Updated the SafeApi SDK to latest reveals this change to `SafeInfoResponse`. nonce is indeed a string

`[ENG-190] | Hotfix v0.5.2` Nonce typing from Safe incorrect

---

src/providers/App/hooks/useSafeAPI.ts

Closes [ENG-190](https://linear.app/decent-labs/issue/ENG-190/multisig-cannot-execute-proposal)
Traced the weird conditional failure all the way back to the nonce we receive from Safe's API. The API's `SafeInfoResponse` type for nonce `number` but actually typed a `string` on the response...Something has changed as of like yesterday?
This change is basically causing any `===` comparison to fail comparing against the proposal's nonce
Edit: Updated the SafeApi SDK to latest reveals this change to `SafeInfoResponse`. nonce is indeed a string

`[ENG-190]` Nonce typing from Safe incorrect (develop)

---

src/hooks/DAO/loaders/governance/useERC721Tokens.ts

Closes [ENG-198](https://linear.app/decent-labs/issue/ENG-198/proposal-details-not-loading-in-overview-for-specific-dao)
`useERC721Tokens` hook was not looking for the `linearVotingErc721WithHatsWhitelistingAddress` being set. so DAOs with this strategy would not load the tokens correctly.

`[ENG-198]` Whitelist erc721 tokens not loading

---

functions/balances/index.ts
functions/balances/transformers.ts
functions/shared/moralisApi.ts
functions/shared/moralisTypes.ts

Closes https://linear.app/decent-labs/issue/ENG-196/moralis-defi-positions-api-is-currently-broken
- Update Moralis API to support non-paginated endpoints
- Enhance DefiResponse transformer to map Moralis response to a more structured format
- Add fetchMoralisDefi helper function for DeFi-specific API calls
- Improve type definitions for DeFi-related responses

Fix DeFi Positions fetching and transforming

---

src/hooks/DAO/proposal/useUserERC721VotingTokens.ts

Close [ENG-210](https://linear.app/decent-labs/issue/ENG-210/erc-721-dao-with-proposer-whitelist-doesnt-allow-voting)
- (Main fix) Ensure `linearVotingErc721WithHatsWhitelistingAddress` contract address is checked for loading erc721 tokens
- extracted logic for readibility
- refactored nested promises with a flatmap

`[ENG-210]` ERC-721 Whitelisting; Voting section not showing

---

src/components/DaoCreator/StepWrapper.tsx

Adjust progress indicator alignment and font size

---

src/components/ProposalBuilder/ProposalBuilder.tsx
src/components/ProposalBuilder/StepButtons.tsx
src/constants/routes.ts
src/pages/dao/proposal-templates/new/SafeCreateProposalTemplatePage.tsx
src/pages/dao/proposals/actions/new/SafeProposalWithActionsCreatePage.tsx
src/pages/dao/proposals/new/SafeProposalCreatePage.tsx
src/pages/dao/proposals/new/sablier/SafeSablierProposalCreatePage.tsx
src/router.tsx

Closes https://linear.app/decent-labs/issue/ENG-186/remove-url-page-state-from-proposal-builder
refactor: simplify proposal builder step management
- Remove URL path params for managing proposal builder steps
- Replace URL-based navigation with local React state in ProposalBuilder
- Update StepButtons component to use props instead of reading URL
- Rename contentRoute prop to mainContent for clarity
- Remove redundant redirects and path wildcards from router
- Update all proposal creation pages to use new step management pattern
This change simplifies the step management in the proposal creation flow by 
using React state instead of URL parameters. This makes the code more 
maintainable and removes unnecessary URL complexity while keeping the same 
functionality.

refactor: simplify proposal builder step management

---

src/components/Roles/forms/RoleFormPaymentStreamTermed.tsx

Closes [ENG-199](https://linear.app/decent-labs/issue/ENG-199/selecting-a-term-in-role-payments-workflow-triggers-proposal-creation)
Before:
After:
Scratched my head a little, it APPEARS when a type is not defined for the `MenuButton` it gives it the `submit` type. which in this case as this `Menu` is nested within a `form`, tries to submit the form. Defining it as type button seems to work with no side-effects

`[ENG-199]` Prevent proposal submission when selecting term

---

package.json
src/components/ui/page/Layout/index.tsx

Add app down banner

---

src/providers/App/hooks/useSafeAPI.ts

Remove as many calls to safe-transaction-service as possible, leave comments where not
Fixes https://linear.app/decent-labs/issue/ENG-334/with-multi-sig-second-signer-doesnt-see-sign-cta
Fixes https://linear.app/decent-labs/issue/ENG-335/with-multi-sig-signer-is-not-able-to-execute-a-transaction-after-it

Remove Safe Transaction Service calls

---

src/providers/App/hooks/useSafeAPI.ts

Closes https://linear.app/decent-labs/issue/ENG-343/app-not-displaying-correct-list-of-modules-attached-to-a-safe
This PR improves the implementation of module retrieval in the `getSafeInfo` method to properly handle all installed modules in a Safe account. The changes ensure we correctly traverse the linked list structure used by Safe contracts to store modules, guaranteeing that we retrieve all installed modules regardless of how many exist.
In Safe contracts, modules are stored in a linked list structure:
- Modules are stored in a mapping where each entry points to the next module
- A special sentinel address (`0x1`) marks both the start and end of the list
- The `getModulesPaginated` function returns a subset of modules and the next address to continue pagination
From …

Refactor Safe modules retrieval to use paginated fetching

---

src/components/ProposalBuilder/ProposalActionCard.tsx
src/components/ProposalBuilder/ProposalTransaction.tsx
src/components/SafeInjectIframe/context/SafeInjectContext.tsx
src/components/SafeInjectIframe/context/SafeInjectProvider.tsx
src/components/ui/cards/DappInteractionActionCard.tsx
src/components/ui/forms/ABISelector.tsx
src/components/ui/modals/ConfirmTransactionModal.tsx
src/components/ui/modals/IframeModal.tsx
src/components/ui/modals/ModalProvider.tsx
src/helpers/transactionDecoder.ts
src/hooks/utils/useABI.ts
src/i18n/locales/en/common.json
src/i18n/locales/en/modals.json
src/types/proposalBuilder.ts

- new modal `ConfirmTransactionModal` that list all transactions from dApp, navigate to proposalWithAction page if user choose to continue.
- new callback `onTransactionsReceived` in props of `SafeInjectProvider`
- updated `IframeModal` to decode transactions within `onTransactionReceived` and then open `ConfirmTransactionModal`
- new action and action card for `DAPP_INTEGRATION`, which display dapp name. (it's now only app url, once we got `dapp.json` imported in later PR, we can display app name easily.)

`ENG-361` take dApp transaction, decode and then create a proposal

---

src/hooks/DAO/loaders/useFractalFreeze.ts

Closes [ENG-237](https://linear.app/decent-labs/issue/ENG-237/initiate-a-freeze-option-can-appear-for-parent-dao)
Tested with ERC20 and Multisig type DAOs

`[ENG-237]` prevent freeze option from showing on parent dao

---

src/hooks/DAO/proposal/useSubmitProposal.ts
src/hooks/utils/useTransaction.ts

Closes fully [ENG-370](https://github.com/decentdao/decent-app/compare/eng-370-update-user-rejected-error-handling-part-2?expand=1)
Covers these other areas mentioned in this comment https://linear.app/decent-labs/issue/ENG-370/sentry-transactionexecutionerror-user-rejected-the-request#comment-d6fac422

`[ENG-370]` update user rejection logic (part 2)

---

src/components/Proposals/MultisigProposalDetails/TxActions.tsx

Closes [ENG-444](https://linear.app/decent-labs/issue/ENG-444/allow-reject-even-if-approval-threshold-has-been-reached)
As well as this short series. I hope
So the UI as is left to be wanting. These components are wrapped in `ContentBox` which is used in a few different places. But isn't alof ot properties, easily make a new container component for these two sections so they don't look so weirdly separate

`[ENG-444]` Update Voter Actions UX

---

src/hooks/utils/useCreateRoles.ts
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/network.ts

- Refactor role creation references to use updated naming convention for HatsWhitelisting master copies

Rename master copy variables for new strategy addresses

---

src/components/Proposals/ProposalActions/CastVote.tsx
src/i18n/locales/en/proposal.json

Adds an automatic call to `castVote` on `castGaslessVote` error, after a 5-second delay.
Closes ENG-492

Add cast vote fallback pending hiFi UX design

---

tsconfig.json

This tsconfig flag fully expands types and typescript errors in IDE
before:
after (you get a scroll bar):
credit:
https://stackoverflow.com/questions/62059942/how-to-extract-a-large-type-with-vs-code-without-the-19-more-truncate

Expand types and typescript errors

---

src/pages/dao/proposal-templates/new/SafeCreateProposalTemplatePage.tsx

`SafeCreateProposalTemplatePage` should display loader until `safe` is ready just like other create proposal flow pages do. so it can get `safe.nextNonce` for `ProposalBuilder.initialValues`.

`[ENG-604-plus]` cannot fork template

---

src/types/createDAO.ts

Minor types cleanup -- removed unneeded exports and an unused type. Stuff I happened to notice while working on ENG-687.

Eng 687 cleanup

---

src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/providers/NetworkConfig/useNetworkConfigStore.ts
src/types/network.ts

Closes [ENG-689](https://linear.app/decent-labs/issue/ENG-689/add-stronger-type-safety-between-account-abstraction-contracts-and)
This PR introduces explicit configuration for Account Abstraction (AA) support on a per-network basis and refactors the `NetworkConfig` type for improved type safety.
1.  **Added `accountAbstractionSupported` Flag:**
*   A new boolean flag, `accountAbstractionSupported`, has been added to the `NetworkConfig` type (`src/types/network.ts`).
*   Each network configuration file (`src/providers/NetworkConfig/networks/*.ts`) has been updated to include this flag, specifying whether AA is supported on that network (e.g., `true` for Mainnet and Sepolia, `false` for Base, Optimism, Polygon).
2.  **Refactored `NetworkConfig` Type:**
*   The `NetworkConfig` type in …

chore(types): Enforce consistency for Account Abstraction config

---

src/hooks/DAO/proposal/useCastVote.ts

Refactor useCastVote hook by removing unused account abstraction and address checks for gasless voting. Simplified the prepareGaslessVoteOperation function and updated dependencies in the hook's effect dependencies.

Clean up unused dependencies in various dependency arrays in `useCastVote`

---

src/components/Activity/ActivityAddress.tsx
src/components/Proposals/ProposalVotes/ProposalERC20VoteItem.tsx
src/components/Proposals/SnapshotProposalDetails/SnapshotProposalVoteItem.tsx
src/components/ui/links/EtherscanLink.tsx
src/components/ui/utils/Sort.tsx
src/components/ui/utils/TopErrorFallback.tsx
src/helpers/dateTime.ts
src/pages/dao/dapps/SafeProposalDappsPage.tsx
src/pages/dao/dapps/details/SafeProposalDappDetailPage.tsx
src/pages/dao/proposal-templates/SafeProposalTemplatesPage.tsx

Fixes [ENG-691](https://linear.app/decent-labs/issue/ENG-691/localization-string-parsing-issues-in-various-places)
Updates various components and helpers to explicitly provide the relevant namespace(s) when calling the `useTranslation` hook from `react-i18next`.
Previously, some calls relied on the default namespace. Specifying namespaces improves clarity, helps with managing translations, and potentially enables better code splitting or loading strategies for translation files.
I asked the AI to help identify which "pages" are affected by these changes, and this is what it gave me, which looks more or less accurate:
> In summary, the pages most likely affected are:
> - DAO Proposal Dapps Page
> - DAO Proposal Dapp Detail Page
> - DAO Proposal Templates Page
> - DAO Activity/Transactions …

fix(i18n): Explicitly specify namespaces for useTranslation

---

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
src/components/GaslessVoting/GaslessVotingToggle.tsx
src/helpers/featureFlags.ts
src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx

Closes [ENG-690](https://linear.app/decent-labs/issue/ENG-690/remove-flag-gasless-staking)
Depends on https://github.com/decentdao/decent-app/pull/2917#pullrequestreview-2778960757
Removes the `flag_gasless_staking` feature flag and associated logic.
The gasless staking functionality is now enabled by default on any network that supports account abstraction (determined by the presence of `bundlerMinimumStake` in the network configuration). This simplifies the configuration and makes the feature consistently available where the underlying infrastructure supports it.

feat(gasless): Remove flag_gasless_staking feature flag

---

src/components/DaoCreator/constants.ts
src/hooks/DAO/useBuildDAOTx.ts
src/hooks/DAO/useDeployAzorius.ts
src/models/AzoriusTxBuilder.ts
src/models/DaoTxBuilder.ts
src/models/TxBuilderFactory.ts
src/pages/dao/edit/governance/SafeEditGovernancePage.tsx
src/types/createDAO.ts

Fixes [ENG-695](https://linear.app/decent-labs/issue/ENG-695/remove-gasless-voting-contracts-and-configurations-from-deploy-dao)
**Description:**
This change removes the option and associated logic for setting up gasless voting features (including paymaster deployment and V1 voting strategy configuration) during the initial DAO creation and deployment process. The setup of these features is intended to be handled separately, likely post-deployment via DAO settings.
**Motivation:**
Bundling the setup of gasless voting (which involves deploying a paymaster contract, setting specific key-value pairs, and potentially using different V1 strategy master copies) into the core DAO deployment transaction batch significantly increased its complexity. This complexity wasn't strictly necessary for …

`[ENG-695]` feat: Remove gasless voting setup from initial DAO deployment

---

src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/types/network.ts

Fixes [ENG-696](https://linear.app/decent-labs/issue/ENG-696/remove-unnecessary-accountabstractionsupported-flag-from-network)
This commit removes the explicit `accountAbstractionSupported` boolean flag from the `NetworkConfig` type definition (`src/types/network.ts`) and all individual network configuration files (`src/providers/NetworkConfig/networks/*.ts`).
**Reasoning:**
The `NetworkConfig` type was previously refactored into a discriminated union, where the presence or absence of the `contracts.accountAbstraction` and `bundlerMinimumStake` properties already served to distinguish between networks that support Account Abstraction (AA) and those that do not.
The `accountAbstractionSupported` boolean flag became redundant, as its value was directly tied to the structure defined by the …

`[ENG-696]` refactor(network-config): Remove explicit accountAbstractionSupported flag

---

src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx

Fixes [ENG-697](https://linear.app/decent-labs/issue/ENG-697/refactor-aa-support-and-staking-logic-in-general-settings-for-clarity)
This commit refactors variable naming and logic within `SafeGeneralSettingsPage.tsx` related to Account Abstraction (AA) support and bundler staking requirements for improved clarity and accuracy.
**Changes:**
1.  **Renamed `gaslessStakingFeatureEnabled` to `accountAbstractionSupported`:**
*   This variable, derived from `bundlerMinimumStake !== undefined`, now more accurately reflects that its purpose is to indicate whether the current network *supports* AA features based on the presence of related configuration. The previous name implied it was solely about enabling staking.
2.  **Introduced `stakingRequired`:**
*   A new boolean variable `stakingRequired` …

`[ENG-697]` refactor(settings): Improve clarity of AA support and staking logic

---

src/store/daoInfo/useDaoInfoStore.ts
src/types/fractal.ts

Fixes [ENG-699](https://linear.app/decent-labs/issue/ENG-699/standardize-paymasteraddress-state-in-dao-info-store-to-use-null)
This change modifies the `paymasterAddress` property in the `IDAO` interface and the initial DAO info store to use `null` instead of `undefined`. This adjustment clarifies the intended state of the paymaster address, ensuring consistency in how it is represented across the codebase.

`[ENG-699]` refactor: Update paymasterAddress type to null in DAO info store

---

src/hooks/utils/useCreateRoles.ts
src/pages/dao/settings/permissions/SafePermissionsCreateProposal.tsx

Fixes [ENG-698](https://linear.app/decent-labs/issue/ENG-698/ensure-aa-config-exists-before-setting-up-gasless-hats-strategies)
Refactors the logic for encoding setup parameters for Hats-whitelisted voting strategies (both ERC20 and ERC721) in `useCreateRoles` and `SafePermissionsCreateProposal`.
Previously, the code implicitly relied on a non-null assertion (`!`) on the `accountAbstraction` configuration when `gaslessVotingFeatureEnabled` was true. This could lead to runtime errors if the feature was enabled on a network lacking the necessary AA configuration, without an explicit check beforehand.
This change introduces an explicit check:
1.  If `gaslessVotingFeatureEnabled` is true, it now verifies that `accountAbstraction` configuration exists.
2.  If AA config is missing when gasless …

`[ENG-698]` fix(strategy): Explicitly check for AA config when setting up gasless Hats strategies

---

src/components/ProposalBuilder/ProposalStream.tsx

Stream deletion is pass to trigger update of `formikProps` outside `BigIntInput` component, which cause `value` prop and internal state `inputValue` to be un-synced.
State `inputValue` state was initialized with `value` and then managed by component logic, so we need to sync it with outside changes. And then I found there's a prop `parentFormikValue` designed for this purpose, so I just add this prop in `ProposalStream` and it works now.
```typescript
/**
...
* @param parentFormikValue This needs to be set to `values.yourFormValue` if the value of the Input control is changed outside of the component, for example via `setFieldValue`. This will update the value of the underlying Input control.
*/
export function BigIntInput({
value,
...
parentFormikValue = { value: '', bigintValue: …
```

`[ENG-716]` use parentFormikValue to keep inputValue of BigIntInput to be synced with outside changes

---

src/hooks/DAO/proposal/useCreateProposalTemplate.ts
src/hooks/DAO/proposal/useRemoveProposalTemplate.ts
src/utils/bigintSerializer.ts

* Extract `bigintSerializer` from `useCreateProposalTemplate` to be shared/re-use.
* Add `bigintSerializer` to `useRemoveProposalTemplate -> json.stringify`, so it can properly handle the bigint.
```javascript
Uncaught (in promise) TypeError: Do not know how to serialize a BigInt
at JSON.stringify (<anonymous>)
at useRemoveProposalTemplate.ts:35:48
at Object.onClick (ProposalTemplateCard.tsx:56:32)
at OptionsList.tsx:19:14
```

`[ENG-342]` unable to remove a custom template

---

src/components/ProposalBuilder/ProposalBuilder.tsx
src/components/ui/modals/AddActions.tsx
src/pages/dao/proposals/actions/new/ActionsExperience.tsx

I realized that the way I originally set this up was causing more problems than it solved and moving the `ActionsExperience` actually had fixed the dupe issue we had saw with the `reEnableInitialization` on the Formik form. After some trial and error with trying a more direct approach, and some testing I think its safe from dupes and we don't need to manually groom the transactions. 
@johnqh This needs to make it in next release with the other work to ensure no this feature goes out working correctly and allowing users to remove created transactions without refresh.

`[ENG-680]` Remove Actions bugfix 

---

src/hooks/DAO/loaders/useDecentTreasury.ts
src/hooks/utils/useFilterSpamTokens.ts

- Check if token symbol is using normal ASCII char, treat it as spam token if not
- Filter ERC20 tokens in `useDecentTreasury` loader, ensure the asset pass [Moralis spam detection](https://docs.moralis.com/web3-data-api/evm/spam-detection) and is using normal (`< 128`) ASCII char. (DAO's native governance token will always pass the check.)

`[ENG-642]` Filter spam ERC20 tokens

---

src/components/ProposalBuilder/ProposalBuilder.tsx
src/components/ProposalBuilder/ProposalMetadata.tsx
src/components/ProposalBuilder/constants.ts
src/hooks/schemas/proposalBuilder/useCreateProposalSchema.ts
src/pages/dao/proposal-templates/new/SafeCreateProposalTemplatePage.tsx
src/pages/dao/proposals/actions/new/SafeProposalWithActionsCreatePage.tsx
src/pages/dao/proposals/new/sablier/SafeSablierProposalCreatePage.tsx
src/store/actions/useProposalActionsStore.ts
src/types/proposalBuilder.ts

I've pushed nonce into the useProposalActionsStore as well and lives within the proposalMetaData property to allow for updates to be saved across form rerenders

`[Eng 823]` Bugfix nonce input

---

src/components/Proposals/MultisigProposalDetails/TxDetails.tsx

- src/components/Proposals/MultisigProposalDetails/TxDetails.tsx:
- Removed display of current signers count (`txDetailsSignersCurrent`)
- Removed display of required signers threshold (`txDetailsSignersRequired`)
- Removed display of proposal nonce (`nonce`)
- Retained essential details: proposal ID, creation date, proposer, and transaction hash
This refactor streamlines the proposal transaction details view by focusing on the most relevant information and reducing visual clutter. In favor of #3010

`[ENG-533]` [refactor]: simplify TxDetails by removing redundant InfoRows

---

public/locales/de/proposal.json
public/locales/en/proposal.json
public/locales/es/proposal.json
public/locales/fr/proposal.json
public/locales/it/proposal.json
public/locales/ja/proposal.json
public/locales/ko/proposal.json
public/locales/pt/proposal.json
public/locales/ru/proposal.json
public/locales/uk/proposal.json
public/locales/zh/proposal.json
public/locales/zh_hant/proposal.json
src/components/Proposals/MultisigProposalDetails/MultisigConflictingProposals.tsx
src/components/Proposals/ProposalCard/SimpleProposalCard.tsx
src/components/Proposals/ProposalInfo.tsx
src/components/ui/containers/AccordionDropdown.tsx
src/components/ui/proposal/ProposalExecutableCode.tsx

Actual changed files: **6**
- Extracted out UI `AccordianDropdown` component code from `ProposalExecutionCode` component for reuse
- Update AccordianDropdown with smaller padding
- Added new section 'Conflictiing Proposals` for multisig type proposals
- Update copy files
- When there are no conflicting proposal section isn't shown
- When a nonce has been rejected a different banner is shown
- When the viewing proposal has been executed conflicting proposal section is hidden

`[ENG-809]` Add Conflicting Proposals section

---

.env
src/hooks/DAO/useKeyValuePairs.ts
src/providers/App/AppProvider.tsx
src/providers/App/governance/action.ts
src/providers/App/governance/reducer.ts
src/store/daoInfo/useDaoInfoStore.ts

So looked like `gaslessVotingData` was split between places. The components were looking for it in governance, and the new globalStore sets in there. But the old setup has it in `useDAOStore` as well as the setters. 
So for now I moved it out of `useDAOStore` and remove the typing. I've added the new action to the governance reducer/actions and set the action up in `useKeyValuePairs` with a TODO to replace it with the correct setter when the `useGlobalStore` feature is released

`[ENG-844 ~ to Release]` BugFix Paymaster deposit info missing

---

public/locales/de/proposal.json
public/locales/en/proposal.json
public/locales/es/proposal.json
public/locales/fr/proposal.json
public/locales/it/proposal.json
public/locales/ja/proposal.json
public/locales/ko/proposal.json
public/locales/pt/proposal.json
public/locales/ru/proposal.json
public/locales/uk/proposal.json
public/locales/zh/proposal.json
public/locales/zh_hant/proposal.json
src/components/Proposals/MultisigProposalDetails/ExectionSection.tsx
src/components/Proposals/MultisigProposalDetails/SignatureSection.tsx
src/components/ui/modals/ConfirmationModal.tsx
src/components/ui/modals/ModalProvider.tsx
src/constants/common.ts

Actual File change (6)
Branched from #3028 
- Modal that pops up when executing a proposal with multiple sharing nonce (non-rejection)
- Modal that pops up when executing a rejection proposal with multiple sharing nonce

`[ENG-846]` Add confirmation modals

---

.env
src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/providers/NetworkConfig/networks/utils.ts
src/vite-env.d.ts

- Update url of etherscan API to V2 which unify all chain access with same url
- All chain will use same `VITE_APP_ETHERSCAN_MAINNET_API_KEY` for Etherscan API V2, no longer need to specify different key for different network.
- Migration doc: https://docs.etherscan.io/etherscan-v2/v2-quickstart

`[ENG-883]` Update to Etherscan V2 by May 31, 2025

---

package-lock.json
package.json
src/components/Markdown/MarkdownEditor.tsx
src/components/ProposalBuilder/ProposalMetadata.tsx
src/providers/App/hooks/useIPFSClient.ts

Note: this PR should act like a refactor which introduce no new feature or break things.
- Use Editor from package [@toast-ui/react-editor](https://www.npmjs.com/package/@toast-ui/react-editor) directly instead of indirectly through [@nance/nance-editor](https://www.npmjs.com/package/@nance/nance-editor).
- Specify type for `useIPFSClient.add`, re-throw error to ensure type-safety. (it's by default return `undefined` when error get caught before)
- Add `onProgress` callback to `useIPFSClient.add` which can be used by `Editor` to display a progress bar when uploading file to IPFS.

`[ENG-899]` move code of nance editor into our repo for easier customization

---

src/components/Markdown/MarkdownEditor.tsx

1. toolbar item consolidation
* remove vertical bars separating subsections of toolbar
* move horizontal line and blockquote to the end of toolbar
2. vertical markdown preview
3. open links in new tab

`[ENG-911]` Editor hot fixes

---

src/components/ui/menus/DAOSearch/index.tsx

- Not to trim DAOSearch input which forbids space.

`[ENG-1074]` Allow for searching with terms that include spaces

---

src/pages/dao/settings/permissions/SafePermissionsSettingsContent.tsx

Whoopsies. I know I tested this, so I must've fat-finger-changed that variable just before pushing the original PR.
Unedited:
Edited (current):
Edited (fixed):

Fix inconsistent proposer threshold bigint display

---

src/components/DAOTreasury/hooks/useTreasuryLidoInteractions.ts
src/components/DaoDashboard/Activities/ProposalsHome.tsx
src/components/GaslessVoting/GaslessVotingToggle.tsx
src/components/ProposalDapps/DappCard.tsx
src/components/ProposalTemplates/ProposalTemplateCard.tsx
src/components/Proposals/MultisigProposalDetails/ExecutionSection.tsx
src/components/Proposals/MultisigProposalDetails/SignatureSection.tsx
src/components/Proposals/ProposalActions/CastVote.tsx
src/components/Proposals/ProposalInfo.tsx
src/components/Roles/RolePaymentDetails.tsx
src/components/Roles/forms/RoleFormPaymentStream.tsx
src/components/SafeSettings/Signers/SignersContainer.tsx
src/components/ui/menus/CreateProposalMenu/index.tsx
src/components/ui/menus/ManageDAO/ManageDAOMenu.tsx
src/components/ui/modals/AddActions.tsx
src/components/ui/modals/ModalProvider.tsx
src/components/ui/modals/PaymentCancelConfirmModal.tsx
src/components/ui/modals/PaymentWithdrawModal.tsx
src/components/ui/modals/useDecentModal.tsx
src/hooks/DAO/proposal/useCastVote.ts
src/hooks/DAO/useSendAssetsActionModal.tsx
src/hooks/useUnsavedChangesBlocker.ts
src/pages/dao/proposal-templates/SafeProposalTemplatesPage.tsx
src/pages/dao/settings/permissions/AddCreateProposalPermissionModal.tsx
src/pages/dao/settings/permissions/SafePermissionsCreateProposal.tsx
src/pages/dao/settings/permissions/SafePermissionsSettingsContent.tsx
src/pages/dao/settings/permissions/SafePermissionsSettingsPage.tsx
src/pages/dao/treasury/SafeTreasuryPage.tsx

While re-working the modal experience, I did not like the way ModalType.NONE was being shoehorned into a "close modal" functionality. This has led to scenarios where visually there's no modal on-screen, but there actually IS one, just invisible -- NONE, thus causing other attempts to open some other modal to simply not work.
I've attempted to fix this in the past by closing the modal in the NONE switch handler. This PR attempts a more comprehensive and explicit fix.
I've completely removed the NONE type, and exposed an explicit `close` function from `useDecentModal`.

`ENG-826` | Remove Modal.NONE

---

public/locales/en/gaslessVoting.json
src/components/GaslessVoting/GaslessVotingToggle.tsx
src/components/ProposalBuilder/ProposalActionCard.tsx
src/components/SafeSettings/SettingsNavigation.tsx
src/components/ui/forms/BigIntInput.tsx
src/components/ui/modals/GaslessVoting/RefillGasTankModal.tsx
src/components/ui/modals/GaslessVoting/WithdrawGasTankModal.tsx
src/components/ui/modals/ModalProvider.tsx
src/components/ui/modals/SafeSettingsModal.tsx
src/pages/dao/settings/general/SafeGeneralSettingsPage.tsx
src/store/settings/useSettingsFormStore.ts
src/utils/dao/prepareRefillPaymasterActionData.ts
src/utils/dao/prepareWithdrawPaymasterActionData.ts
src/utils/dao/prepareWithdrawToDAOActionData.ts

The deposit/withdraw modals apparently exist outside the context of the settings modal context, so error and value update were not propagating onto the form. So:
- Introduced a new settings form store for better state handling
- Replaced Formik context with setFieldValue for improved state management
- Streamlined form state management and validation across modals
- Updated WithdrawGasTankModal and RefillGasTankModal to use the new form state management
- Improved validation and error handling for deposit/withdraw actions
- Added proper balance checks and error messages for insufficient funds
- Added direct deposit functionality that bypasses the settings modal, because that does not go to a proposal
- Added validation for paymaster address and amount
- Added proper edit detection and …

`ENG-1137 ~ Release`: [FIX] Option to refill paymaster using DAO treasury bypasses settings modal

---

.github/workflows/ui-automation.yaml

This makes two changes:
1. Updates the workflow to make it so that the test results comment can be posted on a PR post merge. The original workflow was written expecting the trigger to be `on: pull-request`, making the target of the comment implicit. The update here attempts to locate the PR associated with a push and adds the comment to it, retroactively.
2. Updates the workflow to add a link to the build artifacts to the test results comment. I think this might be more necessary with the workflow not being used as a check on the PR. If I'm wrong about this, the change will still make it easier and is worthwhile if it works.

[ENG-1277] Fix automation workflow for `pull` trigger

---

.github/workflows/ui-automation.yaml

Turns out `peter-evans/find-pull-request@v5` is not a real thing! Or at least, thankfully, it's just the version that is wrong. Or hopefully I should say, that is all that is wrong here.
This just changes it to the version that I double and triple checked is the latest stable version: v3

Update ui-automation.yaml - Update find-pull-request version

---

src/components/ui/modals/ModalProvider.tsx
src/components/ui/modals/SafeSettingsModal.tsx
src/pages/dao/settings/token/SafeTokenSettingsPage.tsx

* **ModalContext** now exposes a `closeAllModals` function. This is useful for pages embedded within a modal that don’t have direct access to the `closeAll` prop—they can now access it via context.
* Added an optional `closeBaseModal` prop to `ModalProvider`. This allows customizing how to close the base modal, even if it exists outside the current `ModalContext`.
* Updated `SafeTokenSettingsPage.tsx` to use `closeAllModals` when navigating to the deploy token page. This ensures all modals are properly closed during navigation.

`[ENG-1270]` expose closeAllModals and add closeBaseModal optional prop in ModalContext

---

src/providers/NetworkConfig/networks/base.ts
src/providers/NetworkConfig/networks/mainnet.ts
src/providers/NetworkConfig/networks/optimism.ts
src/providers/NetworkConfig/networks/polygon.ts
src/providers/NetworkConfig/networks/sepolia.ts
src/store/fetchers/governance.ts
src/types/network.ts
src/utils/stakingContractUtils.ts

Depends on #3194 
- Update `NetworkConfig` to add `votesERC20StakedV1MasterCopy` address which is specified in contracts package.
- Update `getStakingContractAddress` to calculate instead return fixed test value

`[ENG-1154]` get staking address from create2 instead of fixed test value

---

src/hooks/DAO/useLockedToken.ts
src/pages/dao/settings/token/SafeTokenSettingsPage.tsx
src/store/fetchers/governance.ts

* Added `isImportedToken` field to the `useLockedToken` hook to determine whether a token was deployed using the locked token contract.
* Hid token management UI for imported ERC20 tokens in the Token Settings tab.
* Updated `fetchMultisigERC20Token` to tolerate failures in multicall, allowing support for imported tokens that do not implement `maxTotalSupply` without reverting.

`[ENG-1339]` Display token information in Token tab for existing token contract

---

src/components/SafeSettings/SettingsNavigation.tsx

This is in essence what this change, and future changes of this nature, will look like:
Note that the divs where the ID is now present on had nothing else stable to refer to. For automated browser testing, you ideally want an ID type parameter to refer to, since it is unlikely to change and is unique to the element it's tied to.
If you're reduced to locating the text, such as the word "General" from the above, you risk flakiness or tests that require frequent maintenance. An example from recent history is from this modal, where the word "Governance" appears underneath the modal, at the top of the homepage, which means there's a race condition where that element may be selected instead of the correct one.

`[ENG-1347]` Add test IDs to the settings modal tabs

---

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
src/components/DaoCreator/index.tsx
src/components/ui/forms/DurationUnitStepperInput.tsx

* Updated `DurationUnitStepperInput` styling and logic to choose the largest unit that evenly divides the input value.
* Replaced `DayInput` with `UnitInput` on the create page to match the settings page, which already supports units beyond just "Days".
* Refactored to use form state variables directly instead of separate local state and effects — this improves efficiency and reduces potential bugs.
* Consolidated form defaults by updating `initialValues` directly, instead of setting them in multiple places.

`[ENG-1348]` Use DurationUnitStepper for governance settings when creating new DAO

---

public/locales/en/treasury.json
src/components/Roles/forms/RoleFormAssetSelector.tsx
src/components/ui/menus/DropdownMenu.tsx
src/components/ui/utils/AssetSelector.tsx

* Use `space-between` instead of manually calculating `margin-left` to ensure the CaretDown icon is always correctly positioned on the right.

`[ENG-1352]` Fix: Chevron drifts for populated 'Select Asset' menu

---

src/components/SafeSettings/SettingsProposalPermissionForm.tsx
src/pages/dao/settings/permissions/AddCreateProposalPermissionModal.tsx

- Introduced a new component, `SettingsProposalPermissionForm`, by copying and modifying the existing `SettingsPermissionStrategyForm`.
- The new form interacts directly with Formik form values for both reading and writing, while the original component should only be used with simple state (not with Formik values).
- In the previous implementation, `proposerThreshold` was passed as a prop two levels deep, which caused the input to lose focus after each user input.
- The original component still has valid use cases, so a new dedicated component was created to address these specific issues.
- The previous implementation of `setProposerThreshold` always called `setFieldValue`, even when the value hadn’t changed.
- The `BigIntInput` component triggers its `onChange` handler on mount via a …

`[ENG-1349]` Can't edit in the modal of create proposal permission

---

public/locales/en/common.json
src/components/GaslessVoting/GaslessVotingToggle.tsx
src/components/SafeSettings/RevenueShare/RevenueSharingContent.tsx
src/components/SafeSettings/RevenueShare/RevenueSplitWallets.tsx
src/components/SafeSettings/Signers/SignersContainer.tsx
src/components/SafeSettings/TabContents/general/SafeGeneralSettingTab.tsx
src/components/SafeSettings/TabContents/governance/GovernanceParams.tsx
src/components/SafeSettings/TabContents/permissions/SafePermissionsSettingTab.tsx
src/components/SafeSettings/TabContents/staking/SafeStakingSettingTab.tsx
src/components/SafeSettings/TabContents/token/SafeTokenSettingTab.tsx
src/components/ui/forms/AddressInputInfo.tsx
src/components/ui/forms/DurationUnitStepperInput.tsx
src/components/ui/forms/EditableInput.tsx
src/components/ui/forms/InputComponent.tsx
src/components/ui/forms/NumberInputPercentage.tsx
src/components/ui/modals/FormReadOnlyController.tsx
src/components/ui/modals/SafeSettingsModal.tsx
src/hooks/utils/useCanUserSubmitProposal.ts

two improvements:
- Removes redundent `useCanUserSubmitProposal` hook mounts, each mount was making several requests
- setting form now uses `status` property to put form in read-only (disabled) state
- update button from 'Discard' to 'Close' when readonly

`[ENG-1373]` Refactor; Settings Modal with readOnly status

---

src/components/SafeSettings/TabContents/staking/SafeStakingSettingTab.tsx

To avoid click area too big for AssetSelector inside Staking setting tab, move it out of label wrapper.

`[ENG-1361]` fix AssetSelector click area by moving it out of LabelComponent wrapper

---

src/components/SafeSettings/TabContents/general/SafeGeneralSettingTab.tsx

> Let's say I wanted to change my DAO name from "Decent" to "Decent DAO". You can't do that right now without doing some weird stuff, moving the cursor to between the "n" and the "t", for example, and adding the space there. Even worse, if you want to start from scratch, you delete "Decent" and start typing in the name, you still get stuck at the part where you need to enter a space.
To fix the issue described above.

`[ENG-1134]` Only trim DAO name input on blur, so user can input name with spaces normally

---

src/components/DaoCreator/formComponents/AzoriusGovernance.tsx
src/components/DaoCreator/formComponents/AzoriusNFTDetails.tsx
src/components/DaoCreator/formComponents/AzoriusTokenAllocation.tsx
src/components/DaoCreator/formComponents/AzoriusTokenAllocations.tsx
src/components/DaoCreator/formComponents/GuardDetails.tsx
src/components/DaoCreator/formComponents/VotesTokenNew.tsx
src/components/DaoDashboard/Info/InfoProposals.tsx
src/components/ProposalBuilder/ProposalTransaction.tsx
src/components/SafeSettings/SettingsPermissionsStrategyForm.tsx
src/components/SafeSettings/SettingsProposalPermissionForm.tsx
src/components/SafeSettings/TabContents/governance/GovernanceParams.tsx
src/components/ui/modals/ProposalTemplateModal.tsx

I actually had ran into this issue when I was using it for staking. `parentFormikValue` was added as a property with a optional status but not passing this value was breaking things.

`[ENG-1443]` Bugfix `BigIntInput`

---

src/store/fetcher.ts

Reorder state updates so `setAzoriusGovernance` runs immediately after `setDaoNode`, unblocked by slower requests (`getDaoRevenueSharingWallets` and `fetchStakingDAOData`), improving data load speed for the user.

`[ENG-1475]` Run `setAzoriusGovernance` earlier to improve data load speed

---

src/assets/theme/components/alert/alert.variants.ts
src/components/TokenSales/TokenSaleBanner.tsx
src/components/TokenSales/TokenSalesTable.tsx
src/hooks/DAO/proposal/useTokenSaleClaimFunds.ts
src/pages/dao/token-sale/SafeTokenSaleDetailsPage.tsx
src/types/tokenSale.ts

Note: Left a TODO to update `saleState` into a ENUM to match the contract enum. I'll do that in a future PR so I don't have to make changes down the stack
(Not shown at same time in real world)

`[ENG-1489]` Implement Claim Fund Banners
